package com.ey.advisory.app.services.common;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import org.springframework.stereotype.Component;

@Component
public class CustomisedReportCommonUtility {
	private static Map<String, String> JAVA_MAPPING = null;

	static {
		Map<String, String> map = new HashMap<>();
		map.put("DigiGSTStatus", "DigiGSTStatus");
		map.put("EINVStatus", "IrnStatus");
		map.put("EWBStatus", "EwbStatus");
		map.put("GSTNStatus", "GstnStatus");
		map.put("ErrorPoint", "ErrorPoint");
		map.put("DigiGSTErrorDescription", "AspErrorDesc");
		map.put("DigiGSTInformationDescription","AspInformationDesc");
		map.put("EINVErrorCode", "IrpErrorCode");
		map.put("EINVErrorDescription", "IrpErrorDescription");
		map.put("EWBInformationCode", "InfoErrorCode");
		map.put("EWBInformationDescription", "InfoErrorMsg");
		map.put("EWBErrorCode", "EwbErrorCode");
		map.put("EWBErrorDescription", "EwbErrorDescription");
		map.put("IRN(IRP)", "IrnNo");
		map.put("EINVAcknowledgmentNo", "IrnAcknowledgmentNo");
		map.put("EINVAcknowledgmentDate", "IrnAcknowledgmentDate");
		map.put("EINVAcknowledgmentTime", "IrnAcknowledgmentTime");
		map.put("SignedQRCode", "SignedQRCode");
		map.put("SignedInvoice", "SignedInvoice");
		map.put("EINVCancellationDate", "IrnCancellationDate");
		map.put("EINVCancellationTime", "IrnCancellationTime");
		map.put("EWBNo", "EwbNo");
		map.put("EWBRespDate", "EwbRespDate");
		map.put("EWBTime", "EwbTime");
		map.put("EWBValidUpToDate", "EwbValidupto");
		map.put("EWBValidUpToTime", "EwbValiduptoTime");
		map.put("EWBCancellationDate", "eWBCancellationDate");
		map.put("EWBCancellationTime", "eWBCancellationTime");
		map.put("ReturnType", "ReturnType");
		map.put("TableNumber", "TableNumber");
		map.put("GSTNRefid", "GstnRefid");
		map.put("GSTNRefidDate", "GstnRefidDate");
		map.put("GSTNRefidTime", "GstnRefidTime");
		map.put("GSTNErrorCode", "GstnErrorCode");
		map.put("GSTNErrorDescription", "GstnErrorDescription");
		map.put("IRN", "Irn");
		map.put("IRNDate", "IrnDate");
		map.put("TaxScheme", "TaxScheme");
		map.put("CancellationReason", "CancellationReason");
		map.put("CancellationRemarks", "CancellationRemarks");
		map.put("SupplyType", "SupplyType");
		map.put("DocCategory", "DocCategory");
		map.put("DocumentType", "DocumentType");
		map.put("DocumentNumber", "DocumentNumber");
		map.put("DocumentDate", "DocumentDate");
		map.put("ReverseChargeFlag", "ReverseChargeFlag");
		map.put("SupplierGSTIN", "SupplierGSTIN");
		map.put("SupplierTradeName", "SupplierTradeName");
		map.put("SupplierLegalName", "SupplierLegalName");
		map.put("SupplierAddress1", "SupplierAddress1");
		map.put("SupplierAddress2", "SupplierAddress2");
		map.put("SupplierLocation", "SupplierLocation");
		map.put("SupplierPincode", "SupplierPincode");
		map.put("SupplierStateCode", "SupplierStateCode");
		map.put("SupplierPhone", "SupplierPhone");
		map.put("SupplierEmail", "SupplierEmail");
		map.put("CustomerGSTIN", "CustomerGSTIN");
		map.put("CustomerTradeName", "CustomerTradeName");
		map.put("CustomerLegalName", "CustomerLegalName");
		map.put("CustomerAddress1", "CustomerAddress1");
		map.put("CustomerAddress2", "customerAddress2");
		map.put("CustomerLocation", "CustomerLocation");
		map.put("CustomerPincode", "CustomerPincode");
		map.put("CustomerStateCode", "CustomerStateCode");
		map.put("BillingPOS", "BillingPOS");
		map.put("CustomerPhone", "CustomerPhone");
		map.put("CustomerEmail", "CustomerEmail");
		map.put("DispatcherGSTIN", "DispatcherGSTIN");
		map.put("DispatcherTradeName", "DispatcherTradeName");
		map.put("DispatcherAddress1", "DispatcherAddress1");
		map.put("DispatcherAddress2", "DispatcherAddress2");
		map.put("DispatcherLocation", "DispatcherLocation");
		map.put("DispatcherPincode", "DispatcherPincode");
		map.put("DispatcherStateCode", "DispatcherStateCode");
		map.put("ShipToGSTIN", "ShipToGSTIN");
		map.put("ShipToTradeName", "ShipToTradeName");
		map.put("ShipToLegalName", "ShipToLegalName");
		map.put("ShipToAddress1", "ShipToAddress1");
		map.put("ShipToAddress2", "ShipToAddress2");
		map.put("ShipToLocation", "ShipToLocation");
		map.put("ShipToPincode", "ShipToPincode");
		map.put("ShipToStateCode", "ShipToStateCode");
		map.put("ItemSerialNumber", "ItemSerialNumber");
		map.put("ProductSerialNumber", "ProductSerialNumber");
		map.put("ProductName", "ProductName");
		map.put("ProductDescription", "ProductDescription");
		map.put("IsService", "IsService");
		map.put("HSN", "Hsn");
		map.put("Barcode", "Barcode");
		map.put("BatchName", "BatchName");
		map.put("BatchExpiryDate", "BatchExpiryDate");
		map.put("WarrantyDate", "WarrantyDate");
		map.put("OrderLineReference", "OrderlineReference");
		map.put("AttributeName", "AttributeName");
		map.put("AttributeValue", "AttributeValue");
		map.put("OriginCountry", "OriginCountry");
		map.put("UQC", "uQC");
		map.put("Quantity", "Quantity");
		map.put("FreeQuantity", "FreeQuantity");
		map.put("UnitPrice", "UnitPrice");
		map.put("ItemAmount", "ItemAmount");
		map.put("ItemDiscount", "ItemDiscount");
		map.put("PreTaxAmount", "PreTaxAmount");
		map.put("ItemAssessableAmount", "ItemAssessableAmount");
		map.put("IGSTRate", "iGSTRate");
		map.put("IGSTAmount", "iGSTAmount");
		map.put("CGSTRate", "cGSTRate");
		map.put("CGSTAmount", "cGSTAmount");
		map.put("SGSTRate", "sGSTRate");
		map.put("SGSTAmount", "sGSTAmount");
		map.put("CessAdvaloremRate", "CessAdvaloremRate");
		map.put("CessAdvaloremAmount", "CessAdvaloremAmount");
		map.put("CessSpecificRate", "CessSpecificRate");
		map.put("CessSpecificAmount", "CessSpecificAmount");
		map.put("StateCessAdvaloremRate", "StateCessAdvaloremRate");
		map.put("StateCessAdvaloremAmount", "StateCessAdvaloremAmount");
		map.put("StateCessSpecificRate", "StateCessSpecificRate");
		map.put("StateCessSpecificAmount", "StateCessSpecificAmount");
		map.put("ItemOtherCharges", "ItemOtherCharges");
		map.put("TotalItemAmount", "TotalItemAmount");
		map.put("InvoiceOtherCharges", "InvoiceOtherCharges");
		map.put("InvoiceAssessableAmount", "InvoiceAssessableAmount");
		map.put("InvoiceIGSTAmount", "InvoiceIGSTAmount");
		map.put("InvoiceCGSTAmount", "InvoiceCGSTAmount");
		map.put("InvoiceSGSTAmount", "InvoiceSGSTAmount");
		map.put("InvoiceCessAdvaloremAmount", "InvoiceCessAdvaloremAmount");
		map.put("InvoiceCessSpecificAmount", "InvoiceCessSpecificAmount");
		map.put("InvoiceStateCessSpecificAmount",
				"InvoiceStateCessSpecificAmount");
		map.put("InvoiceValue", "InvoiceValue");
		map.put("RoundOff", "RoundOff");
		map.put("TotalInvoiceValue(InWords)", "TotalInvoiceValue");
		map.put("TCSFlagIncomeTax", "tCSFlagIncomeTax");
		map.put("TCSRateIncomeTax", "tCSRateIncomeTax");
		map.put("TCSAmountIncomeTax", "tCSAmountIncomeTax");
		map.put("CustomerPANOrAadhaar", "CustomerPANOrAadhaar");
		map.put("CurrencyCode", "CurrencyCode");
		map.put("CountryCode", "CountryCode");
		map.put("InvoiceValueFC", "InvoiceValueFC");
		map.put("PortCode", "PortCode");
		map.put("ShippingBillNumber", "ShippingBillNumber");
		map.put("ShippingBillDate", "ShippingBillDate");
		map.put("InvoiceRemarks", "InvoiceRemarks");
		map.put("InvoicePeriodStartDate", "InvoicePeriodStartDate");
		map.put("InvoicePeriodEndDate", "InvoicePeriodEndDate");
		map.put("PreceedingInvoiceNumber", "PreceedingInvoiceNumber");
		map.put("PreceedingInvoiceDate", "PreceedingInvoiceDate");
		map.put("OtherReference", "OtherReference");
		map.put("ReceiptAdviceReference", "ReceiptAdviceReference");
		map.put("ReceiptAdviceDate", "ReceiptAdviceDate");
		map.put("TenderReference", "TenderReference");
		map.put("ContractReference", "ContractReference");
		map.put("ExternalReference", "ExternalReference");
		map.put("ProjectReference", "ProjectReference");
		map.put("CustomerPOReferenceNumber", "CustomerPOReferenceNumber");
		map.put("CustomerPOReferenceDate", "CustomerPOReferenceDate");
		map.put("PayeeName", "PayeeName");
		map.put("ModeOfPayment", "ModeOfPayment");
		map.put("BranchOrIFSCCode", "BranchOrIFSCCode");
		map.put("PaymentTerms", "PaymentTerms");
		map.put("PaymentInstruction", "PaymentInstruction");
		map.put("CreditTransfer", "CreditTransfer");
		map.put("DirectDebit", "DirectDebit");
		map.put("CreditDays", "CreditDays");
		map.put("PaidAmount", "PaidAmount");
		map.put("BalanceAmount", "BalanceAmount");
		map.put("PaymentDueDate", "PaymentDueDate");
		map.put("AccountDetail", "AccountDetail");
		map.put("EcomGSTIN", "EcomGSTIN");
		map.put("EcomTransactionID", "EcomTransactionID");
		map.put("SupportingDocURL", "SupportingDocURL");
		map.put("SupportingDocument", "SupportingDocument");
		map.put("AdditionalInformation", "AdditionalInformation");
		map.put("TransactionType", "TransactionType");
		map.put("SubSupplyType", "SubSupplyType");
		map.put("OtherSupplyTypeDescription", "OtherSupplyTypeDescription");
		map.put("TransporterID", "TransporterID");
		map.put("TransporterName", "TransporterName");
		map.put("TransportMode", "TransportMode");
		map.put("TransportDocNo", "TransportDocNo");
		map.put("TransportDocDate", "TransportDocDate");
		map.put("Distance", "Distance");
		map.put("VehicleNo", "VehicleNo");
		map.put("VehicleType", "VehicleType");
		map.put("ReturnPeriod", "ReturnPeriod");
		map.put("OriginalDocumentType", "OriginalDocumentType");
		map.put("OriginalCustomerGSTIN", "OriginalCustomerGSTIN");
		map.put("DifferentialPercentageFlag", "DifferentialPercentageFlag");
		map.put("Section7OfIGSTFlag", "Sec7ofIGSTFlag");
		map.put("ClaimRefundFlag", "ClaimRefndFlag");
		map.put("AutoPopulateToRefund", "AutoPopltToRefund");
		map.put("CRDRPreGST", "cRDRPreGST");
		map.put("CustomerType", "CustomerType");
		map.put("CustomerCode", "CustomerCode");
		map.put("ProductCode", "ProductCode");
		map.put("CategoryOfProduct", "CategoryOfProduct");
		map.put("ITCFlag", "iTCFlag");
		map.put("StateApplyingCess", "StateApplyingCess");
		map.put("FOB", "fOB");
		map.put("ExportDuty", "ExportDuty");
		map.put("ExchangeRate", "ExchangeRate");
		map.put("ReasonForCreditDebitNote", "ReasonForCreditDebitNote");
		map.put("TCSFlagGST", "tCSFlagGST");
		map.put("TCSIGSTAmount", "tCSIGSTAmount");
		map.put("TCSCGSTAmount", "tCSCGSTAmount");
		map.put("TCSSGSTAmount", "tCSSGSTAmount");
		map.put("TDSFlagGST", "tDSFlagGST");
		map.put("TDSIGSTAmount", "tDSIGSTAmount");
		map.put("TDSCGSTAmount", "tDSSGSTAmount");
		map.put("TDSSGSTAmount", "StateApplyingCess");
		map.put("UserID", "UserId");
		map.put("CompanyCode", "CompanyCode");
		map.put("SourceIdentifier", "SourceIdentifier");
		map.put("SourceFileName", "SourceFileName");
		map.put("PlantCode", "PlantCode");
		map.put("Division", "Division");
		map.put("SubDivision", "SubDivision");
		map.put("Location", "Location");
		map.put("SalesOrganisation", "SalesOrganisation");
		map.put("DistributionChannel", "DistributionChannel");
		map.put("ProfitCentre1", "ProfitCentre1");
		map.put("ProfitCentre2", "ProfitCentre2");
		map.put("ProfitCentre3", "ProfitCentre3");
		map.put("ProfitCentre4", "ProfitCentre4");
		map.put("ProfitCentre5", "ProfitCentre5");
		map.put("ProfitCentre6", "ProfitCentre6");
		map.put("ProfitCentre7", "ProfitCentre7");
		map.put("ProfitCentre8", "ProfitCentre8");
		map.put("GLAssessableValue", "GlAssessableValue");
		map.put("GLIGST", "GlIGST");
		map.put("GLCGST", "GlCGST");
		map.put("GLSGST", "GlSGST");
		map.put("GLAdvaloremCess", "GlAdvaloremCess");
		map.put("GLSpecificCess", "GlSpecificCess");
		map.put("GLStateCessAdvalorem", "GLStateCessAdvalorem");
		map.put("GLStateCessSpecific", "GLStateCessSpecific");
		map.put("GLPostingDate", "GlPostingDate");
		map.put("SalesOrderNumber", "SalesOrderNumber");
		map.put("EWBNumber", "eWBNumber");
		map.put("EWBDate", "EWBDate");
		map.put("AccountingVoucherNumber", "AccountingVoucherNumber");
		map.put("AccountingVoucherDate", "AccountingVoucherDate");
		map.put("CustomerTAN", "CustomerTAN");
		map.put("DocumentReferenceNumber", "DocumentReferenceNumber");
		map.put("UserDefinedField1", "UserDefField1");
		map.put("UserDefinedField2", "UserDefField2");
		map.put("UserDefinedField3", "UserDefField3");
		map.put("UserDefinedField4", "UserDefField4");
		map.put("UserDefinedField5", "UserDefField5");
		map.put("UserDefinedField6", "UserDefField6");
		map.put("UserDefinedField7", "UserDefField7");
		map.put("UserDefinedField8", "UserDefField8");
		map.put("UserDefinedField9", "UserDefField9");
		map.put("UserDefinedField10", "UserDefField10");
		map.put("UserDefinedField11", "UserDefField11");
		map.put("UserDefinedField12", "UserDefField12");
		map.put("UserDefinedField13", "UserDefField13");
		map.put("UserDefinedField14", "UserDefField14");
		map.put("UserDefinedField15", "UserDefField15");
		map.put("UserDefinedField16", "UserDefField16");
		map.put("UserDefinedField17", "UserDefField17");
		map.put("UserDefinedField18", "UserDefField18");
		map.put("UserDefinedField19", "UserDefField19");
		map.put("UserDefinedField20", "UserDefField20");
		map.put("UserDefinedField21", "UserDefField21");
		map.put("UserDefinedField22", "userDefField22");
		map.put("UserDefinedField23", "UserDefField23");
		map.put("UserDefinedField24", "UserDefField24");
		map.put("UserDefinedField25", "UserDefField25");
		map.put("UserDefinedField26", "UserDefField26");
		map.put("UserDefinedField27", "UserDefField27");
		map.put("UserDefinedField28", "UserDefField28");
		map.put("UserDefinedField29", "UserDefField29");
		map.put("UserDefinedField30", "UserDefField30");
		map.put("DerivedSupplyType-DigiGST", "SupplyTypeASP");
		map.put("Distance(Provided by user)", "Distance");
		map.put("Distance (Computed by DigiGST)", "ApproximateDistanceASP");
		map.put("Distance (NIC)", "DistanceSavedtoEWB");
		map.put("USER_ID", "UserID");
		map.put("FileID", "FileID");
		map.put("FileName", "FileName");
		map.put("InvoiceOtherCharges-DigiGST", "InvoiceOtherChargesASP");
		map.put("InvoiceAssessableAmount-DigiGST",
				"InvoiceAssessableAmountASP");
		map.put("InvoiceIGSTAmount-DigiGST", "InvoiceIGSTAmountASP");
		map.put("InvoiceCGSTAmount-DigiGST", "InvoiceCGSTAmountASP");
		map.put("InvoiceSGSTAmount-DigiGST", "InvoiceSGSTAmountASP");
		map.put("InvoiceCessAdvaloremAmount-DigiGST",
				"InvoiceCessAdvaloremAmountASP");
		map.put("InvoiceCessSpecificAmount-DigiGST",
				"InvoiceCessSpecificAmountASP");
		map.put("InvoiceStateCessAdvaloremAmount",
				"InvoiceStateCessAdvaloremAmountASP");
		map.put("InvoiceStateCessSpecificAmount-DigiGST",
				"InvoiceStateCessSpecificAmountASP");
		map.put("InvoiceValue-DigiGST", "InvoiceValueASP");
		map.put("IGSTAmount-DigiGST", "IntegratedTaxAmountASP");
		map.put("CGSTAmount-DigiGST", "CentralTaxAmountASP");
		map.put("SGSTAmount-DigiGST", "StateUTTaxAmountASP");
		map.put("CessAdvaloremAmount-DigiGST", "CessAdvaloremAmountASP");
		map.put("StateCessAdvaloremAmount-DigiGST",
				"StateCessAdvaloremAmountASP");
		map.put("IGSTAmount-Difference", "IntegratedTaxAmountRET1Impact");
		map.put("CGSTAmount-Difference", "CentralTaxAmountRET1Impact");
		map.put("SGSTAmount-Difference", "StateUTTaxAmountRET1Impact");
		map.put("CessAdvaloremAmount-Difference",
				"CessAdvaloremAmountDifference");
		map.put("StateCessAdvaloremAmount-Difference",
				"StateCessAdvaloremAmountDifference");
		map.put("RecordStatus", "RecordStatus");

		JAVA_MAPPING = Collections.unmodifiableMap(map);
	}

	public static String getJavaMappingFromField(String field) {
		return JAVA_MAPPING.get(field);
	}

}
