package com.ey.advisory.domain.client;

import java.sql.Clob;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import lombok.Data;

/**
 * This entity class is responsible for storing gstn batch details in the
 * database
 * 
 * @author Hemasundar.J
 *
 * @param <T>
 */

@Entity
@Table(name = "TBL_GSTR2B_REGENERATE_SAVE_BATCH")
@Data
public class Gstr2bRegenerateSaveBatchEntity {


	//need columns "ID" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL , "GSTN_RESP_DATE" LONGDATE CS_LONGDATE, "GSTN_SAVE_REF_ID" VARCHAR(512), "CREATED_BY" VARCHAR(100), "CREATED_ON" LONGDATE CS_LONGDATE, "MODIFIED_BY" VARCHAR(200), "MODIFIED_ON" LONGDATE CS_LONGDATE, "SUPPLIER_GSTIN" VARCHAR(25), "RETURN_PERIOD" VARCHAR(10), "GSTN_SAVE_STATUS" VARCHAR(10), "RETURN_TYPE" VARCHAR(50), "ERROR_DESC" VARCHAR(2048), "GROUP_CODE" VARCHAR(10), "IS_DELETE" BOOLEAN CS_INT DEFAULT FALSE NOT NULL , "DERIVED_RET_PERIOD" INTEGER CS_INT, "TXN_ID" VARCHAR(100), "GET_RESPONSE_PAYLOAD" CLOB MEMORY THRESHOLD 1000,"RETRY_COUNT" INTEGER CS_INT, "ERROR_CODE" VARCHAR(150)
	//need columns "ID" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL , "GSTN_RESP_DATE" LONGDATE CS_LONGDATE, "GSTN_SAVE_REF_ID" VARCHAR(512), "CREATED_BY" VARCHAR(100), "CREATED_ON" LONGDATE CS_LONGDATE, "MODIFIED_BY" VARCHAR(200), "MODIFIED_ON" LONGDATE CS_LONGDATE, "SUPPLIER_GSTIN" VARCHAR(25), "RETURN_PERIOD" VARCHAR(10), "GSTN_SAVE_STATUS" VARCHAR(10), "RETURN_TYPE" VARCHAR(50), "ERROR_DESC" VARCHAR(2048), "GROUP_CODE" VARCHAR(10), "IS_DELETE" BOOLEAN CS_INT DEFAULT FALSE NOT NULL , "DERIVED_RET_PERIOD" INTEGER CS_INT, "TXN_ID" VARCHAR(100), "GET_RESPONSE_PAYLOAD" CLOB MEMORY THRESHOLD 1000,"RETRY_COUNT" INTEGER CS_INT, "ERROR_CODE" VARCHAR(150)
	//need columns "ID" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL , "GSTN_RESP_DATE" LONGDATE CS_LONGDATE, "GSTN_SAVE_REF_ID" VARCHAR(512), "CREATED_BY" VARCHAR(100), "CREATED_ON" LONGDATE CS_LONGDATE, "MODIFIED_BY" VARCHAR(200), "MODIFIED_ON" LONGDATE CS_LONGDATE, "SUPPLIER_GSTIN" VARCHAR(25), "RETURN_PERIOD" VARCHAR(10), "GSTN_SAVE_STATUS" VARCHAR(10), "RETURN_TYPE" VARCHAR(50), "ERROR_DESC" VARCHAR(2048), "GROUP_CODE" VARCHAR(10), "IS_DELETE" BOOLEAN CS_INT DEFAULT FALSE NOT NULL , "DERIVED_RET_PERIOD" INTEGER CS_INT, "TXN_ID" VARCHAR(100), "GET_RESPONSE_PAYLOAD" CLOB MEMORY THRESHOLD 1000,"RETRY_COUNT" INTEGER CS_INT, "ERROR_CODE" VARCHAR(150)



	    @Id
	    @GeneratedValue(strategy = GenerationType.IDENTITY)
	    @Column(name = "ID")
	    private Long id;

	    @Column(name = "GSTN_RESP_DATE")
	    private LocalDateTime gstnRespDate;

	    @Column(name = "GSTN_SAVE_REF_ID")
	    private String gstnSaveRefId;

	    @Column(name = "CREATED_BY")
	    private String createdBy;

	    @Column(name = "CREATED_ON")
	    private LocalDateTime createdOn;

	    @Column(name = "MODIFIED_BY")
	    private String modifiedBy;

	    @Column(name = "MODIFIED_ON")
	    private LocalDateTime modifiedOn;

	    @Column(name = "SUPPLIER_GSTIN")
	    private String supplierGstin;

	    @Column(name = "RETURN_PERIOD")
	    private String returnPeriod;

	    @Column(name = "GSTN_SAVE_STATUS")
	    private String gstnSaveStatus;

	    @Column(name = "RETURN_TYPE")
	    private String returnType;

	    @Column(name = "ERROR_DESC")
	    private String errorDesc;

	    @Column(name = "GROUP_CODE")
	    private String groupCode;

	    @Column(name = "IS_DELETE")
	    private boolean isDelete;

	    @Column(name = "DERIVED_RET_PERIOD")
	    private Integer derivedRetPeriod;

	    @Column(name = "TXN_ID")
	    private String txnId;

	    @Column(name = "GET_RESPONSE_PAYLOAD")
	    private Clob getResponsePayload;

	    @Column(name = "RETRY_COUNT")
	    private Long retryCount;

	    @Column(name = "ERROR_CODE")
	    private String errorCode;
	    
	    @Column(name = "BATCH_ID")
	    private Long batchId;
	    

		@Column(name = "STATUS")
		private String status;
		
	    
	}

