package com.ey.advisory.app.services.search.simplified.docsummary;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.ey.advisory.app.docs.dto.simplified.Annexure1SummaryDto;
import com.ey.advisory.app.docs.dto.simplified.RefundSummaryDto;
import com.ey.advisory.app.docs.dto.simplified.Ret1LateFeeSummaryDto;
import com.ey.advisory.app.docs.dto.simplified.Ret1SummaryRespDto;
import com.ey.advisory.app.docs.dto.simplified.TaxPaymentSummaryDto;
import com.ey.advisory.common.GsonUtil;
import com.ey.advisory.core.dto.Annexure1SummaryReqDto;
import com.google.gson.Gson;
import com.google.gson.JsonElement;

import lombok.extern.slf4j.Slf4j;

/**
 * 
 * @author Balakrishna.S
 *
 */
@Slf4j
@Service("Ret1aReqRespHandler")
public class Ret1aReqRespHandler {

	
	@SuppressWarnings("unchecked")
	public Map<String, JsonElement> handleRet1aReqAndResp(
			Annexure1SummaryReqDto annexure1SummaryRequest) {
		List<Ret1SummaryRespDto> b2cSummaryRespList = new ArrayList<>();
		Ret1SummaryRespDto summaryTotalResp = new Ret1SummaryRespDto();
		summaryTotalResp.setTable("3A");
		summaryTotalResp.setSupplyType("outwardSupplies_a");
		summaryTotalResp.setAspValue(new BigDecimal(0.0));
		summaryTotalResp.setAspSgst(new BigDecimal(0.0));
		summaryTotalResp.setAspIgst(new BigDecimal(0.0));
		summaryTotalResp.setAspCgst(new BigDecimal(0.0));
		summaryTotalResp.setAspSgst(new BigDecimal(0.0));
		summaryTotalResp.setAspCess(new BigDecimal(0.0));
		summaryTotalResp.setUsrValue(new BigDecimal(0.0));
		summaryTotalResp.setUsrSgst(new BigDecimal(0.0));
		summaryTotalResp.setUsrIgst(new BigDecimal(0.0));
		summaryTotalResp.setUsrCgst(new BigDecimal(0.0));
		summaryTotalResp.setUsrCess(new BigDecimal(0.0));
		summaryTotalResp.setGstnValue(new BigDecimal(0.0));
		summaryTotalResp.setGstnSgst(new BigDecimal(0.0));
		summaryTotalResp.setGstnIgst(new BigDecimal(0.0));
		summaryTotalResp.setGstnCgst(new BigDecimal(0.0));
		summaryTotalResp.setGstnCess(new BigDecimal(0.0));
		summaryTotalResp.setDiffValue(new BigDecimal(0.0));
		summaryTotalResp.setDiffSgst(new BigDecimal(0.0));
		summaryTotalResp.setDiffIgst(new BigDecimal(0.0));
		summaryTotalResp.setDiffCgst(new BigDecimal(0.0));
		summaryTotalResp.setDiffCess(new BigDecimal(0.0));

		Ret1SummaryRespDto summaryB2CaResp = new Ret1SummaryRespDto();
		summaryB2CaResp.setTable("3A1");
		summaryB2CaResp.setSection("1");
		summaryB2CaResp.setSupplyType("b2c_a");
		summaryB2CaResp.setAspValue(new BigDecimal(0.0));
		summaryB2CaResp.setAspSgst(new BigDecimal(0.0));
		summaryB2CaResp.setAspIgst(new BigDecimal(0.0));
		summaryB2CaResp.setAspCgst(new BigDecimal(0.0));
		summaryB2CaResp.setAspSgst(new BigDecimal(0.0));
		summaryB2CaResp.setAspCess(new BigDecimal(0.0));
		summaryB2CaResp.setUsrValue(new BigDecimal(0.0));
		summaryB2CaResp.setUsrSgst(new BigDecimal(0.0));
		summaryB2CaResp.setUsrIgst(new BigDecimal(0.0));
		summaryB2CaResp.setUsrCgst(new BigDecimal(0.0));
		summaryB2CaResp.setUsrCess(new BigDecimal(0.0));
		summaryB2CaResp.setGstnValue(new BigDecimal(0.0));
		summaryB2CaResp.setGstnSgst(new BigDecimal(0.0));
		summaryB2CaResp.setGstnIgst(new BigDecimal(0.0));
		summaryB2CaResp.setGstnCgst(new BigDecimal(0.0));
		summaryB2CaResp.setGstnCess(new BigDecimal(0.0));
		summaryB2CaResp.setDiffValue(new BigDecimal(0.0));
		summaryB2CaResp.setDiffSgst(new BigDecimal(0.0));
		summaryB2CaResp.setDiffIgst(new BigDecimal(0.0));
		summaryB2CaResp.setDiffCgst(new BigDecimal(0.0));
		summaryB2CaResp.setDiffCess(new BigDecimal(0.0));

		Ret1SummaryRespDto expwta = new Ret1SummaryRespDto();
		expwta.setTable("3A2");
		expwta.setSection("2");
		expwta.setSupplyType("expwt_a");
		expwta.setAspValue(new BigDecimal(0.0));
		expwta.setAspSgst(new BigDecimal(0.0));
		expwta.setAspIgst(new BigDecimal(0.0));
		expwta.setAspCgst(new BigDecimal(0.0));
		expwta.setAspSgst(new BigDecimal(0.0));
		expwta.setAspCess(new BigDecimal(0.0));
		expwta.setUsrValue(new BigDecimal(0.0));
		expwta.setUsrSgst(new BigDecimal(0.0));
		expwta.setUsrIgst(new BigDecimal(0.0));
		expwta.setUsrCgst(new BigDecimal(0.0));
		expwta.setUsrCess(new BigDecimal(0.0));
		expwta.setGstnValue(new BigDecimal(0.0));
		expwta.setGstnSgst(new BigDecimal(0.0));
		expwta.setGstnIgst(new BigDecimal(0.0));
		expwta.setGstnCgst(new BigDecimal(0.0));
		expwta.setGstnCess(new BigDecimal(0.0));
		expwta.setDiffValue(new BigDecimal(0.0));
		expwta.setDiffSgst(new BigDecimal(0.0));
		expwta.setDiffIgst(new BigDecimal(0.0));
		expwta.setDiffCgst(new BigDecimal(0.0));
		expwta.setDiffCess(new BigDecimal(0.0));

		Ret1SummaryRespDto expwota = new Ret1SummaryRespDto();
		expwota.setTable("3A3");
		expwota.setSection("3");
		expwota.setSupplyType("expwot_a");
		expwota.setAspValue(new BigDecimal(0.0));
		expwota.setAspSgst(new BigDecimal(0.0));
		expwota.setAspIgst(new BigDecimal(0.0));
		expwota.setAspCgst(new BigDecimal(0.0));
		expwota.setAspSgst(new BigDecimal(0.0));
		expwota.setAspCess(new BigDecimal(0.0));
		expwota.setUsrValue(new BigDecimal(0.0));
		expwota.setUsrSgst(new BigDecimal(0.0));
		expwota.setUsrIgst(new BigDecimal(0.0));
		expwota.setUsrCgst(new BigDecimal(0.0));
		expwota.setUsrCess(new BigDecimal(0.0));
		expwota.setGstnValue(new BigDecimal(0.0));
		expwota.setGstnSgst(new BigDecimal(0.0));
		expwota.setGstnIgst(new BigDecimal(0.0));
		expwota.setGstnCgst(new BigDecimal(0.0));
		expwota.setGstnCess(new BigDecimal(0.0));
		expwota.setDiffValue(new BigDecimal(0.0));
		expwota.setDiffSgst(new BigDecimal(0.0));
		expwota.setDiffIgst(new BigDecimal(0.0));
		expwota.setDiffCgst(new BigDecimal(0.0));
		expwota.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto priorPerioda = new Ret1SummaryRespDto();
		priorPerioda.setTable("3A4");
		priorPerioda.setSection("4");
		priorPerioda.setSupplyType("priorPeriod_a");
		priorPerioda.setAspValue(new BigDecimal(0.0));
		priorPerioda.setAspSgst(new BigDecimal(0.0));
		priorPerioda.setAspIgst(new BigDecimal(0.0));
		priorPerioda.setAspCgst(new BigDecimal(0.0));
		priorPerioda.setAspSgst(new BigDecimal(0.0));
		priorPerioda.setAspCess(new BigDecimal(0.0));
		priorPerioda.setUsrValue(new BigDecimal(0.0));
		priorPerioda.setUsrSgst(new BigDecimal(0.0));
		priorPerioda.setUsrIgst(new BigDecimal(0.0));
		priorPerioda.setUsrCgst(new BigDecimal(0.0));
		priorPerioda.setUsrCess(new BigDecimal(0.0));
		priorPerioda.setGstnValue(new BigDecimal(0.0));
		priorPerioda.setGstnSgst(new BigDecimal(0.0));
		priorPerioda.setGstnIgst(new BigDecimal(0.0));
		priorPerioda.setGstnCgst(new BigDecimal(0.0));
		priorPerioda.setGstnCess(new BigDecimal(0.0));
		priorPerioda.setDiffValue(new BigDecimal(0.0));
		priorPerioda.setDiffSgst(new BigDecimal(0.0));
		priorPerioda.setDiffIgst(new BigDecimal(0.0));
		priorPerioda.setDiffCgst(new BigDecimal(0.0));
		priorPerioda.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto summary3bResp = new Ret1SummaryRespDto();
		summary3bResp.setTable("3B");
		//summaryB2BResp.setSection("2");
		summary3bResp.setSupplyType("inwardSupplies_a");
		summary3bResp.setAspValue(new BigDecimal(0.0));
		summary3bResp.setAspSgst(new BigDecimal(0.0));
		summary3bResp.setAspIgst(new BigDecimal(0.0));
		summary3bResp.setAspCgst(new BigDecimal(0.0));
		summary3bResp.setAspSgst(new BigDecimal(0.0));
		summary3bResp.setAspCess(new BigDecimal(0.0));
		summary3bResp.setUsrValue(new BigDecimal(0.0));
		summary3bResp.setUsrSgst(new BigDecimal(0.0));
		summary3bResp.setUsrIgst(new BigDecimal(0.0));
		summary3bResp.setUsrCgst(new BigDecimal(0.0));
		summary3bResp.setUsrCess(new BigDecimal(0.0));
		summary3bResp.setGstnValue(new BigDecimal(0.0));
		summary3bResp.setGstnSgst(new BigDecimal(0.0));
		summary3bResp.setGstnIgst(new BigDecimal(0.0));
		summary3bResp.setGstnCgst(new BigDecimal(0.0));
		summary3bResp.setGstnCess(new BigDecimal(0.0));
		summary3bResp.setDiffValue(new BigDecimal(0.0));
		summary3bResp.setDiffSgst(new BigDecimal(0.0));
		summary3bResp.setDiffIgst(new BigDecimal(0.0));
		summary3bResp.setDiffCgst(new BigDecimal(0.0));
		summary3bResp.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto rcInwardResp = new Ret1SummaryRespDto();
		rcInwardResp.setTable("3B1");
		rcInwardResp.setSection("1");
		rcInwardResp.setSupplyType("rcInward_a");
		rcInwardResp.setAspValue(new BigDecimal(0.0));
		rcInwardResp.setAspSgst(new BigDecimal(0.0));
		rcInwardResp.setAspIgst(new BigDecimal(0.0));
		rcInwardResp.setAspCgst(new BigDecimal(0.0));
		rcInwardResp.setAspSgst(new BigDecimal(0.0));
		rcInwardResp.setAspCess(new BigDecimal(0.0));
		rcInwardResp.setUsrValue(new BigDecimal(0.0));
		rcInwardResp.setUsrSgst(new BigDecimal(0.0));
		rcInwardResp.setUsrIgst(new BigDecimal(0.0));
		rcInwardResp.setUsrCgst(new BigDecimal(0.0));
		rcInwardResp.setUsrCess(new BigDecimal(0.0));
		rcInwardResp.setGstnValue(new BigDecimal(0.0));
		rcInwardResp.setGstnSgst(new BigDecimal(0.0));
		rcInwardResp.setGstnIgst(new BigDecimal(0.0));
		rcInwardResp.setGstnCgst(new BigDecimal(0.0));
		rcInwardResp.setGstnCess(new BigDecimal(0.0));
		rcInwardResp.setDiffValue(new BigDecimal(0.0));
		rcInwardResp.setDiffSgst(new BigDecimal(0.0));
		rcInwardResp.setDiffIgst(new BigDecimal(0.0));
		rcInwardResp.setDiffCgst(new BigDecimal(0.0));
		rcInwardResp.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto imps = new Ret1SummaryRespDto();
		imps.setTable("3B2");
		imps.setSection("2");
		imps.setSupplyType("imps_a");
		imps.setAspValue(new BigDecimal(0.0));
		imps.setAspSgst(new BigDecimal(0.0));
		imps.setAspIgst(new BigDecimal(0.0));
		imps.setAspCgst(new BigDecimal(0.0));
		imps.setAspSgst(new BigDecimal(0.0));
		imps.setAspCess(new BigDecimal(0.0));
		imps.setUsrValue(new BigDecimal(0.0));
		imps.setUsrSgst(new BigDecimal(0.0));
		imps.setUsrIgst(new BigDecimal(0.0));
		imps.setUsrCgst(new BigDecimal(0.0));
		imps.setUsrCess(new BigDecimal(0.0));
		imps.setGstnValue(new BigDecimal(0.0));
		imps.setGstnSgst(new BigDecimal(0.0));
		imps.setGstnIgst(new BigDecimal(0.0));
		imps.setGstnCgst(new BigDecimal(0.0));
		imps.setGstnCess(new BigDecimal(0.0));
		imps.setDiffValue(new BigDecimal(0.0));
		imps.setDiffSgst(new BigDecimal(0.0));
		imps.setDiffIgst(new BigDecimal(0.0));
		imps.setDiffCgst(new BigDecimal(0.0));
		imps.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto summery3c = new Ret1SummaryRespDto();
		summery3c.setTable("3C");
		//imps.setSection("2");
		summery3c.setSupplyType("drCrNotes_a");
		summery3c.setAspValue(new BigDecimal(0.0));
		summery3c.setAspSgst(new BigDecimal(0.0));
		summery3c.setAspIgst(new BigDecimal(0.0));
		summery3c.setAspCgst(new BigDecimal(0.0));
		summery3c.setAspSgst(new BigDecimal(0.0));
		summery3c.setAspCess(new BigDecimal(0.0));
		summery3c.setUsrValue(new BigDecimal(0.0));
		summery3c.setUsrSgst(new BigDecimal(0.0));
		summery3c.setUsrIgst(new BigDecimal(0.0));
		summery3c.setUsrCgst(new BigDecimal(0.0));
		summery3c.setUsrCess(new BigDecimal(0.0));
		summery3c.setGstnValue(new BigDecimal(0.0));
		summery3c.setGstnSgst(new BigDecimal(0.0));
		summery3c.setGstnIgst(new BigDecimal(0.0));
		summery3c.setGstnCgst(new BigDecimal(0.0));
		summery3c.setGstnCess(new BigDecimal(0.0));
		summery3c.setDiffValue(new BigDecimal(0.0));
		summery3c.setDiffSgst(new BigDecimal(0.0));
		summery3c.setDiffIgst(new BigDecimal(0.0));
		summery3c.setDiffCgst(new BigDecimal(0.0));
		summery3c.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto summery3c1 = new Ret1SummaryRespDto();
		summery3c1.setTable("3C1");
		summery3c1.setSection("1");
		summery3c1.setSupplyType("otherReductions_a");
		summery3c1.setAspValue(new BigDecimal(0.0));
		summery3c1.setAspSgst(new BigDecimal(0.0));
		summery3c1.setAspIgst(new BigDecimal(0.0));
		summery3c1.setAspCgst(new BigDecimal(0.0));
		summery3c1.setAspSgst(new BigDecimal(0.0));
		summery3c1.setAspCess(new BigDecimal(0.0));
		summery3c1.setUsrValue(new BigDecimal(0.0));
		summery3c1.setUsrSgst(new BigDecimal(0.0));
		summery3c1.setUsrIgst(new BigDecimal(0.0));
		summery3c1.setUsrCgst(new BigDecimal(0.0));
		summery3c1.setUsrCess(new BigDecimal(0.0));
		summery3c1.setGstnValue(new BigDecimal(0.0));
		summery3c1.setGstnSgst(new BigDecimal(0.0));
		summery3c1.setGstnIgst(new BigDecimal(0.0));
		summery3c1.setGstnCgst(new BigDecimal(0.0));
		summery3c1.setGstnCess(new BigDecimal(0.0));
		summery3c1.setDiffValue(new BigDecimal(0.0));
		summery3c1.setDiffSgst(new BigDecimal(0.0));
		summery3c1.setDiffIgst(new BigDecimal(0.0));
		summery3c1.setDiffCgst(new BigDecimal(0.0));
		summery3c1.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto summery3d = new Ret1SummaryRespDto();
		summery3d.setTable("3D");
		//summery3d.setSection("1");
		summery3d.setSupplyType("suppliesNoLiability_a");
		summery3d.setAspValue(new BigDecimal(0.0));
		summery3d.setAspSgst(new BigDecimal(0.0));
		summery3d.setAspIgst(new BigDecimal(0.0));
		summery3d.setAspCgst(new BigDecimal(0.0));
		summery3d.setAspSgst(new BigDecimal(0.0));
		summery3d.setAspCess(new BigDecimal(0.0));
		summery3d.setUsrValue(new BigDecimal(0.0));
		summery3d.setUsrSgst(new BigDecimal(0.0));
		summery3d.setUsrIgst(new BigDecimal(0.0));
		summery3d.setUsrCgst(new BigDecimal(0.0));
		summery3d.setUsrCess(new BigDecimal(0.0));
		summery3d.setGstnValue(new BigDecimal(0.0));
		summery3d.setGstnSgst(new BigDecimal(0.0));
		summery3d.setGstnIgst(new BigDecimal(0.0));
		summery3d.setGstnCgst(new BigDecimal(0.0));
		summery3d.setGstnCess(new BigDecimal(0.0));
		summery3d.setDiffValue(new BigDecimal(0.0));
		summery3d.setDiffSgst(new BigDecimal(0.0));
		summery3d.setDiffIgst(new BigDecimal(0.0));
		summery3d.setDiffCgst(new BigDecimal(0.0));
		summery3d.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto exemptNil_a = new Ret1SummaryRespDto();
		exemptNil_a.setTable("3D1");
		exemptNil_a.setSection("1");
		exemptNil_a.setSupplyType("exemptNil_a");
		exemptNil_a.setAspValue(new BigDecimal(0.0));
		exemptNil_a.setAspSgst(new BigDecimal(0.0));
		exemptNil_a.setAspIgst(new BigDecimal(0.0));
		exemptNil_a.setAspCgst(new BigDecimal(0.0));
		exemptNil_a.setAspSgst(new BigDecimal(0.0));
		exemptNil_a.setAspCess(new BigDecimal(0.0));
		exemptNil_a.setUsrValue(new BigDecimal(0.0));
		exemptNil_a.setUsrSgst(new BigDecimal(0.0));
		exemptNil_a.setUsrIgst(new BigDecimal(0.0));
		exemptNil_a.setUsrCgst(new BigDecimal(0.0));
		exemptNil_a.setUsrCess(new BigDecimal(0.0));
		exemptNil_a.setGstnValue(new BigDecimal(0.0));
		exemptNil_a.setGstnSgst(new BigDecimal(0.0));
		exemptNil_a.setGstnIgst(new BigDecimal(0.0));
		exemptNil_a.setGstnCgst(new BigDecimal(0.0));
		exemptNil_a.setGstnCess(new BigDecimal(0.0));
		exemptNil_a.setDiffValue(new BigDecimal(0.0));
		exemptNil_a.setDiffSgst(new BigDecimal(0.0));
		exemptNil_a.setDiffIgst(new BigDecimal(0.0));
		exemptNil_a.setDiffCgst(new BigDecimal(0.0));
		exemptNil_a.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto nonGst_a = new Ret1SummaryRespDto();
		nonGst_a.setTable("3D2");
		nonGst_a.setSection("2");
		nonGst_a.setSupplyType("nonGstexemptNil_a");
		nonGst_a.setAspValue(new BigDecimal(0.0));
		nonGst_a.setAspSgst(new BigDecimal(0.0));
		nonGst_a.setAspIgst(new BigDecimal(0.0));
		nonGst_a.setAspCgst(new BigDecimal(0.0));
		nonGst_a.setAspSgst(new BigDecimal(0.0));
		nonGst_a.setAspCess(new BigDecimal(0.0));
		nonGst_a.setUsrValue(new BigDecimal(0.0));
		nonGst_a.setUsrSgst(new BigDecimal(0.0));
		nonGst_a.setUsrIgst(new BigDecimal(0.0));
		nonGst_a.setUsrCgst(new BigDecimal(0.0));
		nonGst_a.setUsrCess(new BigDecimal(0.0));
		nonGst_a.setGstnValue(new BigDecimal(0.0));
		nonGst_a.setGstnSgst(new BigDecimal(0.0));
		nonGst_a.setGstnIgst(new BigDecimal(0.0));
		nonGst_a.setGstnCgst(new BigDecimal(0.0));
		nonGst_a.setGstnCess(new BigDecimal(0.0));
		nonGst_a.setDiffValue(new BigDecimal(0.0));
		nonGst_a.setDiffSgst(new BigDecimal(0.0));
		nonGst_a.setDiffIgst(new BigDecimal(0.0));
		nonGst_a.setDiffCgst(new BigDecimal(0.0));
		nonGst_a.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto rcOutward_a = new Ret1SummaryRespDto();
		rcOutward_a.setTable("3D3");
		rcOutward_a.setSection("3");
		rcOutward_a.setSupplyType("rcOutward_a");
		rcOutward_a.setAspValue(new BigDecimal(0.0));
		rcOutward_a.setAspSgst(new BigDecimal(0.0));
		rcOutward_a.setAspIgst(new BigDecimal(0.0));
		rcOutward_a.setAspCgst(new BigDecimal(0.0));
		rcOutward_a.setAspSgst(new BigDecimal(0.0));
		rcOutward_a.setAspCess(new BigDecimal(0.0));
		rcOutward_a.setUsrValue(new BigDecimal(0.0));
		rcOutward_a.setUsrSgst(new BigDecimal(0.0));
		rcOutward_a.setUsrIgst(new BigDecimal(0.0));
		rcOutward_a.setUsrCgst(new BigDecimal(0.0));
		rcOutward_a.setUsrCess(new BigDecimal(0.0));
		rcOutward_a.setGstnValue(new BigDecimal(0.0));
		rcOutward_a.setGstnSgst(new BigDecimal(0.0));
		rcOutward_a.setGstnIgst(new BigDecimal(0.0));
		rcOutward_a.setGstnCgst(new BigDecimal(0.0));
		rcOutward_a.setGstnCess(new BigDecimal(0.0));
		rcOutward_a.setDiffValue(new BigDecimal(0.0));
		rcOutward_a.setDiffSgst(new BigDecimal(0.0));
		rcOutward_a.setDiffIgst(new BigDecimal(0.0));
		rcOutward_a.setDiffCgst(new BigDecimal(0.0));
		rcOutward_a.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto sezDta_a = new Ret1SummaryRespDto();
		sezDta_a.setTable("3D4");
		sezDta_a.setSection("4");
		sezDta_a.setSupplyType("sezDta_a");
		sezDta_a.setAspValue(new BigDecimal(0.0));
		sezDta_a.setAspSgst(new BigDecimal(0.0));
		sezDta_a.setAspIgst(new BigDecimal(0.0));
		sezDta_a.setAspCgst(new BigDecimal(0.0));
		sezDta_a.setAspSgst(new BigDecimal(0.0));
		sezDta_a.setAspCess(new BigDecimal(0.0));
		sezDta_a.setUsrValue(new BigDecimal(0.0));
		sezDta_a.setUsrSgst(new BigDecimal(0.0));
		sezDta_a.setUsrIgst(new BigDecimal(0.0));
		sezDta_a.setUsrCgst(new BigDecimal(0.0));
		sezDta_a.setUsrCess(new BigDecimal(0.0));
		sezDta_a.setGstnValue(new BigDecimal(0.0));
		sezDta_a.setGstnSgst(new BigDecimal(0.0));
		sezDta_a.setGstnIgst(new BigDecimal(0.0));
		sezDta_a.setGstnCgst(new BigDecimal(0.0));
		sezDta_a.setGstnCess(new BigDecimal(0.0));
		sezDta_a.setDiffValue(new BigDecimal(0.0));
		sezDta_a.setDiffSgst(new BigDecimal(0.0));
		sezDta_a.setDiffIgst(new BigDecimal(0.0));
		sezDta_a.setDiffCgst(new BigDecimal(0.0));
		sezDta_a.setDiffCess(new BigDecimal(0.0));
		
		
		Ret1SummaryRespDto summery3e = new Ret1SummaryRespDto();
		summery3e.setTable("3E");
		//summery3e.setSection("4");
		summery3e.setSupplyType("valueNLiability_a");
		summery3e.setAspValue(new BigDecimal(0.0));
		summery3e.setAspSgst(new BigDecimal(0.0));
		summery3e.setAspIgst(new BigDecimal(0.0));
		summery3e.setAspCgst(new BigDecimal(0.0));
		summery3e.setAspSgst(new BigDecimal(0.0));
		summery3e.setAspCess(new BigDecimal(0.0));
		summery3e.setUsrValue(new BigDecimal(0.0));
		summery3e.setUsrSgst(new BigDecimal(0.0));
		summery3e.setUsrIgst(new BigDecimal(0.0));
		summery3e.setUsrCgst(new BigDecimal(0.0));
		summery3e.setUsrCess(new BigDecimal(0.0));
		summery3e.setGstnValue(new BigDecimal(0.0));
		summery3e.setGstnSgst(new BigDecimal(0.0));
		summery3e.setGstnIgst(new BigDecimal(0.0));
		summery3e.setGstnCgst(new BigDecimal(0.0));
		summery3e.setGstnCess(new BigDecimal(0.0));
		summery3e.setDiffValue(new BigDecimal(0.0));
		summery3e.setDiffSgst(new BigDecimal(0.0));
		summery3e.setDiffIgst(new BigDecimal(0.0));
		summery3e.setDiffCgst(new BigDecimal(0.0));
		summery3e.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto summery4a = new Ret1SummaryRespDto();
		summery4a.setTable("4A");
		//summery3e.setSection("4");
		summery4a.setSupplyType("itcNOtherClaims_a");
		summery4a.setAspValue(new BigDecimal(0.0));
		summery4a.setAspSgst(new BigDecimal(0.0));
		summery4a.setAspIgst(new BigDecimal(0.0));
		summery4a.setAspCgst(new BigDecimal(0.0));
		summery4a.setAspSgst(new BigDecimal(0.0));
		summery4a.setAspCess(new BigDecimal(0.0));
		summery4a.setUsrValue(new BigDecimal(0.0));
		summery4a.setUsrSgst(new BigDecimal(0.0));
		summery4a.setUsrIgst(new BigDecimal(0.0));
		summery4a.setUsrCgst(new BigDecimal(0.0));
		summery4a.setUsrCess(new BigDecimal(0.0));
		summery4a.setGstnValue(new BigDecimal(0.0));
		summery4a.setGstnSgst(new BigDecimal(0.0));
		summery4a.setGstnIgst(new BigDecimal(0.0));
		summery4a.setGstnCgst(new BigDecimal(0.0));
		summery4a.setGstnCess(new BigDecimal(0.0));
		summery4a.setDiffValue(new BigDecimal(0.0));
		summery4a.setDiffSgst(new BigDecimal(0.0));
		summery4a.setDiffIgst(new BigDecimal(0.0));
		summery4a.setDiffCgst(new BigDecimal(0.0));
		summery4a.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto summery4a1 = new Ret1SummaryRespDto();
		summery4a1.setTable("4A1");
		summery4a1.setSection("1");
		summery4a1.setSupplyType("rcInward_a");
		summery4a1.setAspValue(new BigDecimal(0.0));
		summery4a1.setAspSgst(new BigDecimal(0.0));
		summery4a1.setAspIgst(new BigDecimal(0.0));
		summery4a1.setAspCgst(new BigDecimal(0.0));
		summery4a1.setAspSgst(new BigDecimal(0.0));
		summery4a1.setAspCess(new BigDecimal(0.0));
		summery4a1.setUsrValue(new BigDecimal(0.0));
		summery4a1.setUsrSgst(new BigDecimal(0.0));
		summery4a1.setUsrIgst(new BigDecimal(0.0));
		summery4a1.setUsrCgst(new BigDecimal(0.0));
		summery4a1.setUsrCess(new BigDecimal(0.0));
		summery4a1.setGstnValue(new BigDecimal(0.0));
		summery4a1.setGstnSgst(new BigDecimal(0.0));
		summery4a1.setGstnIgst(new BigDecimal(0.0));
		summery4a1.setGstnCgst(new BigDecimal(0.0));
		summery4a1.setGstnCess(new BigDecimal(0.0));
		summery4a1.setDiffValue(new BigDecimal(0.0));
		summery4a1.setDiffSgst(new BigDecimal(0.0));
		summery4a1.setDiffIgst(new BigDecimal(0.0));
		summery4a1.setDiffCgst(new BigDecimal(0.0));
		summery4a1.setDiffCess(new BigDecimal(0.0));
		Ret1SummaryRespDto summery42 = new Ret1SummaryRespDto();
		summery42.setTable("4A2");
		summery42.setSection("2");
		summery42.setSupplyType("imps_a");
		summery42.setAspValue(new BigDecimal(0.0));
		summery42.setAspSgst(new BigDecimal(0.0));
		summery42.setAspIgst(new BigDecimal(0.0));
		summery42.setAspCgst(new BigDecimal(0.0));
		summery42.setAspSgst(new BigDecimal(0.0));
		summery42.setAspCess(new BigDecimal(0.0));
		summery42.setUsrValue(new BigDecimal(0.0));
		summery42.setUsrSgst(new BigDecimal(0.0));
		summery42.setUsrIgst(new BigDecimal(0.0));
		summery42.setUsrCgst(new BigDecimal(0.0));
		summery42.setUsrCess(new BigDecimal(0.0));
		summery42.setGstnValue(new BigDecimal(0.0));
		summery42.setGstnSgst(new BigDecimal(0.0));
		summery42.setGstnIgst(new BigDecimal(0.0));
		summery42.setGstnCgst(new BigDecimal(0.0));
		summery42.setGstnCess(new BigDecimal(0.0));
		summery42.setDiffValue(new BigDecimal(0.0));
		summery42.setDiffSgst(new BigDecimal(0.0));
		summery42.setDiffIgst(new BigDecimal(0.0));
		summery42.setDiffCgst(new BigDecimal(0.0));
		summery42.setDiffCess(new BigDecimal(0.0));
		Ret1SummaryRespDto summery4a3 = new Ret1SummaryRespDto();
		summery4a3.setTable("4A3");
		summery4a3.setSection("3");
		summery4a3.setSupplyType("impg_a");
		summery4a3.setAspValue(new BigDecimal(0.0));
		summery4a3.setAspSgst(new BigDecimal(0.0));
		summery4a3.setAspIgst(new BigDecimal(0.0));
		summery4a3.setAspCgst(new BigDecimal(0.0));
		summery4a3.setAspSgst(new BigDecimal(0.0));
		summery4a3.setAspCess(new BigDecimal(0.0));
		summery4a3.setUsrValue(new BigDecimal(0.0));
		summery4a3.setUsrSgst(new BigDecimal(0.0));
		summery4a3.setUsrIgst(new BigDecimal(0.0));
		summery4a3.setUsrCgst(new BigDecimal(0.0));
		summery4a3.setUsrCess(new BigDecimal(0.0));
		summery4a3.setGstnValue(new BigDecimal(0.0));
		summery4a3.setGstnSgst(new BigDecimal(0.0));
		summery4a3.setGstnIgst(new BigDecimal(0.0));
		summery4a3.setGstnCgst(new BigDecimal(0.0));
		summery4a3.setGstnCess(new BigDecimal(0.0));
		summery4a3.setDiffValue(new BigDecimal(0.0));
		summery4a3.setDiffSgst(new BigDecimal(0.0));
		summery4a3.setDiffIgst(new BigDecimal(0.0));
		summery4a3.setDiffCgst(new BigDecimal(0.0));
		summery4a3.setDiffCess(new BigDecimal(0.0));
		Ret1SummaryRespDto summery4a4 = new Ret1SummaryRespDto();
		summery4a4.setTable("4A4");
		summery4a4.setSection("4");
		summery4a4.setSupplyType("impgSez_a");
		summery4a4.setAspValue(new BigDecimal(0.0));
		summery4a4.setAspSgst(new BigDecimal(0.0));
		summery4a4.setAspIgst(new BigDecimal(0.0));
		summery4a4.setAspCgst(new BigDecimal(0.0));
		summery4a4.setAspSgst(new BigDecimal(0.0));
		summery4a4.setAspCess(new BigDecimal(0.0));
		summery4a4.setUsrValue(new BigDecimal(0.0));
		summery4a4.setUsrSgst(new BigDecimal(0.0));
		summery4a4.setUsrIgst(new BigDecimal(0.0));
		summery4a4.setUsrCgst(new BigDecimal(0.0));
		summery4a4.setUsrCess(new BigDecimal(0.0));
		summery4a4.setGstnValue(new BigDecimal(0.0));
		summery4a4.setGstnSgst(new BigDecimal(0.0));
		summery4a4.setGstnIgst(new BigDecimal(0.0));
		summery4a4.setGstnCgst(new BigDecimal(0.0));
		summery4a4.setGstnCess(new BigDecimal(0.0));
		summery4a4.setDiffValue(new BigDecimal(0.0));
		summery4a4.setDiffSgst(new BigDecimal(0.0));
		summery4a4.setDiffIgst(new BigDecimal(0.0));
		summery4a4.setDiffCgst(new BigDecimal(0.0));
		summery4a4.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto summery4a5 = new Ret1SummaryRespDto();
		summery4a5.setTable("4A5");
		summery3e.setSection("5");
		summery4a5.setSupplyType("adjustments_a");
		summery4a5.setAspValue(new BigDecimal(0.0));
		summery4a5.setAspSgst(new BigDecimal(0.0));
		summery4a5.setAspIgst(new BigDecimal(0.0));
		summery4a5.setAspCgst(new BigDecimal(0.0));
		summery4a5.setAspSgst(new BigDecimal(0.0));
		summery4a5.setAspCess(new BigDecimal(0.0));
		summery4a5.setUsrValue(new BigDecimal(0.0));
		summery4a5.setUsrSgst(new BigDecimal(0.0));
		summery4a5.setUsrIgst(new BigDecimal(0.0));
		summery4a5.setUsrCgst(new BigDecimal(0.0));
		summery4a5.setUsrCess(new BigDecimal(0.0));
		summery4a5.setGstnValue(new BigDecimal(0.0));
		summery4a5.setGstnSgst(new BigDecimal(0.0));
		summery4a5.setGstnIgst(new BigDecimal(0.0));
		summery4a5.setGstnCgst(new BigDecimal(0.0));
		summery4a5.setGstnCess(new BigDecimal(0.0));
		summery4a5.setDiffValue(new BigDecimal(0.0));
		summery4a5.setDiffSgst(new BigDecimal(0.0));
		summery4a5.setDiffIgst(new BigDecimal(0.0));
		summery4a5.setDiffCgst(new BigDecimal(0.0));
		summery4a5.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto summery4b = new Ret1SummaryRespDto();
		summery4b.setTable("4B");
		//summery3e.setSection("5");
		summery4b.setSupplyType("creditReversal_a");
		summery4b.setAspValue(new BigDecimal(0.0));
		summery4b.setAspSgst(new BigDecimal(0.0));
		summery4b.setAspIgst(new BigDecimal(0.0));
		summery4b.setAspCgst(new BigDecimal(0.0));
		summery4b.setAspSgst(new BigDecimal(0.0));
		summery4b.setAspCess(new BigDecimal(0.0));
		summery4b.setUsrValue(new BigDecimal(0.0));
		summery4b.setUsrSgst(new BigDecimal(0.0));
		summery4b.setUsrIgst(new BigDecimal(0.0));
		summery4b.setUsrCgst(new BigDecimal(0.0));
		summery4b.setUsrCess(new BigDecimal(0.0));
		summery4b.setGstnValue(new BigDecimal(0.0));
		summery4b.setGstnSgst(new BigDecimal(0.0));
		summery4b.setGstnIgst(new BigDecimal(0.0));
		summery4b.setGstnCgst(new BigDecimal(0.0));
		summery4b.setGstnCess(new BigDecimal(0.0));
		summery4b.setDiffValue(new BigDecimal(0.0));
		summery4b.setDiffSgst(new BigDecimal(0.0));
		summery4b.setDiffIgst(new BigDecimal(0.0));
		summery4b.setDiffCgst(new BigDecimal(0.0));
		summery4b.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto summery4b1 = new Ret1SummaryRespDto();
		summery4b1.setTable("4B1");
		summery4b1.setSection("1");
		summery4b1.setSupplyType("ineligibleCredit_a");
		summery4b1.setAspValue(new BigDecimal(0.0));
		summery4b1.setAspSgst(new BigDecimal(0.0));
		summery4b1.setAspIgst(new BigDecimal(0.0));
		summery4b1.setAspCgst(new BigDecimal(0.0));
		summery4b1.setAspSgst(new BigDecimal(0.0));
		summery4b1.setAspCess(new BigDecimal(0.0));
		summery4b1.setUsrValue(new BigDecimal(0.0));
		summery4b1.setUsrSgst(new BigDecimal(0.0));
		summery4b1.setUsrIgst(new BigDecimal(0.0));
		summery4b1.setUsrCgst(new BigDecimal(0.0));
		summery4b1.setUsrCess(new BigDecimal(0.0));
		summery4b1.setGstnValue(new BigDecimal(0.0));
		summery4b1.setGstnSgst(new BigDecimal(0.0));
		summery4b1.setGstnIgst(new BigDecimal(0.0));
		summery4b1.setGstnCgst(new BigDecimal(0.0));
		summery4b1.setGstnCess(new BigDecimal(0.0));
		summery4b1.setDiffValue(new BigDecimal(0.0));
		summery4b1.setDiffSgst(new BigDecimal(0.0));
		summery4b1.setDiffIgst(new BigDecimal(0.0));
		summery4b1.setDiffCgst(new BigDecimal(0.0));
		summery4b1.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto summery4b2 = new Ret1SummaryRespDto();
		summery4b2.setTable("4B2");
		summery4b2.setSection("2");
		summery4b2.setSupplyType("itcReversal_a");
		summery4b2.setAspValue(new BigDecimal(0.0));
		summery4b2.setAspSgst(new BigDecimal(0.0));
		summery4b2.setAspIgst(new BigDecimal(0.0));
		summery4b2.setAspCgst(new BigDecimal(0.0));
		summery4b2.setAspSgst(new BigDecimal(0.0));
		summery4b2.setAspCess(new BigDecimal(0.0));
		summery4b2.setUsrValue(new BigDecimal(0.0));
		summery4b2.setUsrSgst(new BigDecimal(0.0));
		summery4b2.setUsrIgst(new BigDecimal(0.0));
		summery4b2.setUsrCgst(new BigDecimal(0.0));
		summery4b2.setUsrCess(new BigDecimal(0.0));
		summery4b2.setGstnValue(new BigDecimal(0.0));
		summery4b2.setGstnSgst(new BigDecimal(0.0));
		summery4b2.setGstnIgst(new BigDecimal(0.0));
		summery4b2.setGstnCgst(new BigDecimal(0.0));
		summery4b2.setGstnCess(new BigDecimal(0.0));
		summery4b2.setDiffValue(new BigDecimal(0.0));
		summery4b2.setDiffSgst(new BigDecimal(0.0));
		summery4b2.setDiffIgst(new BigDecimal(0.0));
		summery4b2.setDiffCgst(new BigDecimal(0.0));
		summery4b2.setDiffCess(new BigDecimal(0.0));
		
		Ret1SummaryRespDto summery4c = new Ret1SummaryRespDto();
		summery4c.setTable("4C");
	//	summery4b2.setSection("2");
		summery4c.setSupplyType("itcAvailable_a");
		summery4c.setAspValue(new BigDecimal(0.0));
		summery4c.setAspSgst(new BigDecimal(0.0));
		summery4c.setAspIgst(new BigDecimal(0.0));
		summery4c.setAspCgst(new BigDecimal(0.0));
		summery4c.setAspSgst(new BigDecimal(0.0));
		summery4c.setAspCess(new BigDecimal(0.0));
		summery4c.setUsrValue(new BigDecimal(0.0));
		summery4c.setUsrSgst(new BigDecimal(0.0));
		summery4c.setUsrIgst(new BigDecimal(0.0));
		summery4c.setUsrCgst(new BigDecimal(0.0));
		summery4c.setUsrCess(new BigDecimal(0.0));
		summery4c.setGstnValue(new BigDecimal(0.0));
		summery4c.setGstnSgst(new BigDecimal(0.0));
		summery4c.setGstnIgst(new BigDecimal(0.0));
		summery4c.setGstnCgst(new BigDecimal(0.0));
		summery4c.setGstnCess(new BigDecimal(0.0));
		summery4c.setDiffValue(new BigDecimal(0.0));
		summery4c.setDiffSgst(new BigDecimal(0.0));
		summery4c.setDiffIgst(new BigDecimal(0.0));
		summery4c.setDiffCgst(new BigDecimal(0.0));
		summery4c.setDiffCess(new BigDecimal(0.0));
		
		List<Ret1LateFeeSummaryDto> LateSummaryResp = new ArrayList<>();
		Ret1LateFeeSummaryDto LateSummaryRespList = new Ret1LateFeeSummaryDto();

		LateSummaryRespList.setTable("5");
		LateSummaryRespList.setDesc("interestNLateFee_a");
		LateSummaryRespList.setUsrSgst(new BigDecimal(0.0));
		LateSummaryRespList.setUsrLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList.setUsrLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList.setUsrIgst(new BigDecimal(0.0));
		LateSummaryRespList.setUsrCgst(new BigDecimal(0.0));
		LateSummaryRespList.setUsrCess(new BigDecimal(0.0));
		LateSummaryRespList.setGstnSgst(new BigDecimal(0.0));
		LateSummaryRespList.setGstnLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList.setGstnLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList.setGstnIgst(new BigDecimal(0.0));
		LateSummaryRespList.setGstnCgst(new BigDecimal(0.0));
		LateSummaryRespList.setGstnCess(new BigDecimal(0.0));
		LateSummaryRespList.setDiffSgst(new BigDecimal(0.0));
		LateSummaryRespList.setDiffLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList.setDiffLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList.setDiffIgst(new BigDecimal(0.0));
		LateSummaryRespList.setDiffCgst(new BigDecimal(0.0));
		LateSummaryRespList.setDiffCess(new BigDecimal(0.0));
		LateSummaryResp.add(LateSummaryRespList);

		Ret1LateFeeSummaryDto LateSummaryRespList1 = new Ret1LateFeeSummaryDto();

		LateSummaryRespList1.setTable("5");
		LateSummaryRespList1.setSection("5.1");
		LateSummaryRespList1.setDesc("interestNFeeLateFiling_a");
		LateSummaryRespList1.setUsrSgst(new BigDecimal(0.0));
		LateSummaryRespList1.setUsrLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList1.setUsrLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList1.setUsrIgst(new BigDecimal(0.0));
		LateSummaryRespList1.setUsrCgst(new BigDecimal(0.0));
		LateSummaryRespList1.setUsrCess(new BigDecimal(0.0));
		LateSummaryRespList1.setGstnSgst(new BigDecimal(0.0));
		LateSummaryRespList1.setGstnLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList1.setGstnLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList1.setGstnIgst(new BigDecimal(0.0));
		LateSummaryRespList1.setGstnCgst(new BigDecimal(0.0));
		LateSummaryRespList1.setGstnCess(new BigDecimal(0.0));
		LateSummaryRespList1.setDiffSgst(new BigDecimal(0.0));
		LateSummaryRespList1.setDiffLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList1.setDiffLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList1.setDiffIgst(new BigDecimal(0.0));
		LateSummaryRespList1.setDiffCgst(new BigDecimal(0.0));
		LateSummaryRespList1.setDiffCess(new BigDecimal(0.0));
		LateSummaryResp.add(LateSummaryRespList1);

		Ret1LateFeeSummaryDto LateSummaryRespList2 = new Ret1LateFeeSummaryDto();

		LateSummaryRespList2.setTable("5");
		LateSummaryRespList2.setSection("5.2");
		LateSummaryRespList2.setDesc("interestItcReversal_a");
		LateSummaryRespList2.setUsrSgst(new BigDecimal(0.0));
		LateSummaryRespList2.setUsrLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList2.setUsrLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList2.setUsrIgst(new BigDecimal(0.0));
		LateSummaryRespList2.setUsrCgst(new BigDecimal(0.0));
		LateSummaryRespList2.setUsrCess(new BigDecimal(0.0));
		LateSummaryRespList2.setGstnSgst(new BigDecimal(0.0));
		LateSummaryRespList2.setGstnLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList2.setGstnLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList2.setGstnIgst(new BigDecimal(0.0));
		LateSummaryRespList2.setGstnCgst(new BigDecimal(0.0));
		LateSummaryRespList2.setGstnCess(new BigDecimal(0.0));
		LateSummaryRespList2.setDiffSgst(new BigDecimal(0.0));
		LateSummaryRespList2.setDiffLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList2.setDiffLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList2.setDiffIgst(new BigDecimal(0.0));
		LateSummaryRespList2.setDiffCgst(new BigDecimal(0.0));
		LateSummaryRespList2.setDiffCess(new BigDecimal(0.0));
		LateSummaryResp.add(LateSummaryRespList2);

		Ret1LateFeeSummaryDto LateSummaryRespList3 = new Ret1LateFeeSummaryDto();

		LateSummaryRespList3.setTable("5");
		LateSummaryRespList3.setSection("5.3");
		LateSummaryRespList3.setDesc("lateReportingRCM");
		LateSummaryRespList3.setUsrSgst(new BigDecimal(0.0));
		LateSummaryRespList3.setUsrLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList3.setUsrLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList3.setUsrIgst(new BigDecimal(0.0));
		LateSummaryRespList3.setUsrCgst(new BigDecimal(0.0));
		LateSummaryRespList3.setUsrCess(new BigDecimal(0.0));
		LateSummaryRespList3.setGstnSgst(new BigDecimal(0.0));
		LateSummaryRespList3.setGstnLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList3.setGstnLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList3.setGstnIgst(new BigDecimal(0.0));
		LateSummaryRespList3.setGstnCgst(new BigDecimal(0.0));
		LateSummaryRespList3.setGstnCess(new BigDecimal(0.0));
		LateSummaryRespList3.setDiffSgst(new BigDecimal(0.0));
		LateSummaryRespList3.setDiffLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList3.setDiffLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList3.setDiffIgst(new BigDecimal(0.0));
		LateSummaryRespList3.setDiffCgst(new BigDecimal(0.0));
		LateSummaryRespList3.setDiffCess(new BigDecimal(0.0));
		LateSummaryResp.add(LateSummaryRespList3);

		Ret1LateFeeSummaryDto LateSummaryRespList4 = new Ret1LateFeeSummaryDto();

		LateSummaryRespList4.setTable("5");
		LateSummaryRespList4.setSection("5.4");
		LateSummaryRespList4.setDesc("otherInterest");
		LateSummaryRespList4.setUsrSgst(new BigDecimal(0.0));
		LateSummaryRespList4.setUsrLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList4.setUsrLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList4.setUsrIgst(new BigDecimal(0.0));
		LateSummaryRespList4.setUsrCgst(new BigDecimal(0.0));
		LateSummaryRespList4.setUsrCess(new BigDecimal(0.0));
		LateSummaryRespList4.setGstnSgst(new BigDecimal(0.0));
		LateSummaryRespList4.setGstnLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList4.setGstnLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList4.setGstnIgst(new BigDecimal(0.0));
		LateSummaryRespList4.setGstnCgst(new BigDecimal(0.0));
		LateSummaryRespList4.setGstnCess(new BigDecimal(0.0));
		LateSummaryRespList4.setDiffSgst(new BigDecimal(0.0));
		LateSummaryRespList4.setDiffLateFeeSgst(new BigDecimal(0.0));
		LateSummaryRespList4.setDiffLateFeeCgst(new BigDecimal(0.0));
		LateSummaryRespList4.setDiffIgst(new BigDecimal(0.0));
		LateSummaryRespList4.setDiffCgst(new BigDecimal(0.0));
		LateSummaryRespList4.setDiffCess(new BigDecimal(0.0));
		LateSummaryResp.add(LateSummaryRespList4);

		List<TaxPaymentSummaryDto> taxPaymentList = new ArrayList<>();
		TaxPaymentSummaryDto taxSummaryRespList = new TaxPaymentSummaryDto();
		taxSummaryRespList.setTable("6");
		taxSummaryRespList.setDesc("paymentTax");
		taxSummaryRespList.setUsrCashPaidInterest(new BigDecimal(0.0));
		taxSummaryRespList.setUsrCashPaidLateFee(new BigDecimal(0.0));
		taxSummaryRespList.setUsrCashPaidTax(new BigDecimal(0.0));
		taxSummaryRespList.setUsrItcPaidCess(new BigDecimal(0.0));
		taxSummaryRespList.setUsrItcPaidCgst(new BigDecimal(0.0));
		taxSummaryRespList.setUsrItcPaidIgst(new BigDecimal(0.0));
		taxSummaryRespList.setUsrItcPaidSgst(new BigDecimal(0.0));
		taxSummaryRespList.setUsrLiability(new BigDecimal(0.0));
		taxSummaryRespList.setUsrOtherLiability(new BigDecimal(0.0));
		taxSummaryRespList.setUsrOtherPaid(new BigDecimal(0.0));
		taxSummaryRespList.setUsrOtherPayable(new BigDecimal(0.0));
		taxSummaryRespList.setUsrPaid(new BigDecimal(0.0));
		taxSummaryRespList.setUsrPayable(new BigDecimal(0.0));

		taxSummaryRespList.setGstnCashPaidInterest(new BigDecimal(0.0));
		taxSummaryRespList.setGstnCashPaidLateFee(new BigDecimal(0.0));
		taxSummaryRespList.setGstnCashPaidTax(new BigDecimal(0.0));
		taxSummaryRespList.setGstnItcPaidCess(new BigDecimal(0.0));
		taxSummaryRespList.setGstnItcPaidCgst(new BigDecimal(0.0));
		taxSummaryRespList.setGstnItcPaidIgst(new BigDecimal(0.0));
		taxSummaryRespList.setGstnItcPaidSgst(new BigDecimal(0.0));
		taxSummaryRespList.setGstnLiability(new BigDecimal(0.0));
		taxSummaryRespList.setGstnOtherLiability(new BigDecimal(0.0));
		taxSummaryRespList.setGstnOtherPaid(new BigDecimal(0.0));
		taxSummaryRespList.setGstnOtherPayable(new BigDecimal(0.0));
		taxSummaryRespList.setGstnPaid(new BigDecimal(0.0));
		taxSummaryRespList.setGstnPayable(new BigDecimal(0.0));

		taxSummaryRespList.setDiffCashPaidInterest(new BigDecimal(0.0));
		taxSummaryRespList.setDiffCashPaidLateFee(new BigDecimal(0.0));
		taxSummaryRespList.setDiffCashPaidTax(new BigDecimal(0.0));
		taxSummaryRespList.setDiffItcPaidCess(new BigDecimal(0.0));
		taxSummaryRespList.setDiffItcPaidCgst(new BigDecimal(0.0));
		taxSummaryRespList.setDiffItcPaidIgst(new BigDecimal(0.0));
		taxSummaryRespList.setDiffItcPaidSgst(new BigDecimal(0.0));
		taxSummaryRespList.setDiffLiability(new BigDecimal(0.0));
		taxSummaryRespList.setDiffOtherLiability(new BigDecimal(0.0));
		taxSummaryRespList.setDiffOtherPaid(new BigDecimal(0.0));
		taxSummaryRespList.setDiffOtherPayable(new BigDecimal(0.0));
		taxSummaryRespList.setDiffPaid(new BigDecimal(0.0));
		taxSummaryRespList.setDiffPayable(new BigDecimal(0.0));
		taxPaymentList.add(taxSummaryRespList);

		TaxPaymentSummaryDto igstSummaryRespList = new TaxPaymentSummaryDto();
		igstSummaryRespList.setTable("6");
		igstSummaryRespList.setSection("6.1");
		igstSummaryRespList.setDesc("IGST");
		igstSummaryRespList.setUsrCashPaidInterest(new BigDecimal(0.0));
		igstSummaryRespList.setUsrCashPaidLateFee(new BigDecimal(0.0));
		igstSummaryRespList.setUsrCashPaidTax(new BigDecimal(0.0));
		igstSummaryRespList.setUsrItcPaidCess(new BigDecimal(0.0));
		igstSummaryRespList.setUsrItcPaidCgst(new BigDecimal(0.0));
		igstSummaryRespList.setUsrItcPaidIgst(new BigDecimal(0.0));
		igstSummaryRespList.setUsrItcPaidSgst(new BigDecimal(0.0));
		igstSummaryRespList.setUsrLiability(new BigDecimal(0.0));
		igstSummaryRespList.setUsrOtherLiability(new BigDecimal(0.0));
		igstSummaryRespList.setUsrOtherPaid(new BigDecimal(0.0));
		igstSummaryRespList.setUsrOtherPayable(new BigDecimal(0.0));
		igstSummaryRespList.setUsrPaid(new BigDecimal(0.0));
		igstSummaryRespList.setUsrPayable(new BigDecimal(0.0));

		igstSummaryRespList.setGstnCashPaidInterest(new BigDecimal(0.0));
		igstSummaryRespList.setGstnCashPaidLateFee(new BigDecimal(0.0));
		igstSummaryRespList.setGstnCashPaidTax(new BigDecimal(0.0));
		igstSummaryRespList.setGstnItcPaidCess(new BigDecimal(0.0));
		igstSummaryRespList.setGstnItcPaidCgst(new BigDecimal(0.0));
		igstSummaryRespList.setGstnItcPaidIgst(new BigDecimal(0.0));
		igstSummaryRespList.setGstnItcPaidSgst(new BigDecimal(0.0));
		igstSummaryRespList.setGstnLiability(new BigDecimal(0.0));
		igstSummaryRespList.setGstnOtherLiability(new BigDecimal(0.0));
		igstSummaryRespList.setGstnOtherPaid(new BigDecimal(0.0));
		igstSummaryRespList.setGstnOtherPayable(new BigDecimal(0.0));
		igstSummaryRespList.setGstnPaid(new BigDecimal(0.0));
		igstSummaryRespList.setGstnPayable(new BigDecimal(0.0));

		igstSummaryRespList.setDiffCashPaidInterest(new BigDecimal(0.0));
		igstSummaryRespList.setDiffCashPaidLateFee(new BigDecimal(0.0));
		igstSummaryRespList.setDiffCashPaidTax(new BigDecimal(0.0));
		igstSummaryRespList.setDiffItcPaidCess(new BigDecimal(0.0));
		igstSummaryRespList.setDiffItcPaidCgst(new BigDecimal(0.0));
		igstSummaryRespList.setDiffItcPaidIgst(new BigDecimal(0.0));
		igstSummaryRespList.setDiffItcPaidSgst(new BigDecimal(0.0));
		igstSummaryRespList.setDiffLiability(new BigDecimal(0.0));
		igstSummaryRespList.setDiffOtherLiability(new BigDecimal(0.0));
		igstSummaryRespList.setDiffOtherPaid(new BigDecimal(0.0));
		igstSummaryRespList.setDiffOtherPayable(new BigDecimal(0.0));
		igstSummaryRespList.setDiffPaid(new BigDecimal(0.0));
		igstSummaryRespList.setDiffPayable(new BigDecimal(0.0));
		taxPaymentList.add(igstSummaryRespList);

		TaxPaymentSummaryDto cgstSummaryRespList = new TaxPaymentSummaryDto();
		cgstSummaryRespList.setTable("6");
		cgstSummaryRespList.setSection("6.2");
		cgstSummaryRespList.setDesc("CGST");
		cgstSummaryRespList.setUsrCashPaidInterest(new BigDecimal(0.0));
		cgstSummaryRespList.setUsrCashPaidLateFee(new BigDecimal(0.0));
		cgstSummaryRespList.setUsrCashPaidTax(new BigDecimal(0.0));
		cgstSummaryRespList.setUsrItcPaidCess(new BigDecimal(0.0));
		cgstSummaryRespList.setUsrItcPaidCgst(new BigDecimal(0.0));
		cgstSummaryRespList.setUsrItcPaidIgst(new BigDecimal(0.0));
		cgstSummaryRespList.setUsrItcPaidSgst(new BigDecimal(0.0));
		cgstSummaryRespList.setUsrLiability(new BigDecimal(0.0));
		cgstSummaryRespList.setUsrOtherLiability(new BigDecimal(0.0));
		cgstSummaryRespList.setUsrOtherPaid(new BigDecimal(0.0));
		cgstSummaryRespList.setUsrOtherPayable(new BigDecimal(0.0));
		cgstSummaryRespList.setUsrPaid(new BigDecimal(0.0));
		cgstSummaryRespList.setUsrPayable(new BigDecimal(0.0));

		cgstSummaryRespList.setGstnCashPaidInterest(new BigDecimal(0.0));
		cgstSummaryRespList.setGstnCashPaidLateFee(new BigDecimal(0.0));
		cgstSummaryRespList.setGstnCashPaidTax(new BigDecimal(0.0));
		cgstSummaryRespList.setGstnItcPaidCess(new BigDecimal(0.0));
		cgstSummaryRespList.setGstnItcPaidCgst(new BigDecimal(0.0));
		cgstSummaryRespList.setGstnItcPaidIgst(new BigDecimal(0.0));
		cgstSummaryRespList.setGstnItcPaidSgst(new BigDecimal(0.0));
		cgstSummaryRespList.setGstnLiability(new BigDecimal(0.0));
		cgstSummaryRespList.setGstnOtherLiability(new BigDecimal(0.0));
		cgstSummaryRespList.setGstnOtherPaid(new BigDecimal(0.0));
		cgstSummaryRespList.setGstnOtherPayable(new BigDecimal(0.0));
		cgstSummaryRespList.setGstnPaid(new BigDecimal(0.0));
		cgstSummaryRespList.setGstnPayable(new BigDecimal(0.0));

		cgstSummaryRespList.setDiffCashPaidInterest(new BigDecimal(0.0));
		cgstSummaryRespList.setDiffCashPaidLateFee(new BigDecimal(0.0));
		cgstSummaryRespList.setDiffCashPaidTax(new BigDecimal(0.0));
		cgstSummaryRespList.setDiffItcPaidCess(new BigDecimal(0.0));
		cgstSummaryRespList.setDiffItcPaidCgst(new BigDecimal(0.0));
		cgstSummaryRespList.setDiffItcPaidIgst(new BigDecimal(0.0));
		cgstSummaryRespList.setDiffItcPaidSgst(new BigDecimal(0.0));
		cgstSummaryRespList.setDiffLiability(new BigDecimal(0.0));
		cgstSummaryRespList.setDiffOtherLiability(new BigDecimal(0.0));
		cgstSummaryRespList.setDiffOtherPaid(new BigDecimal(0.0));
		cgstSummaryRespList.setDiffOtherPayable(new BigDecimal(0.0));
		cgstSummaryRespList.setDiffPaid(new BigDecimal(0.0));
		cgstSummaryRespList.setDiffPayable(new BigDecimal(0.0));
		taxPaymentList.add(cgstSummaryRespList);

		TaxPaymentSummaryDto sgstSummaryRespList = new TaxPaymentSummaryDto();
		sgstSummaryRespList.setTable("6");
		sgstSummaryRespList.setSection("6.3");
		sgstSummaryRespList.setDesc("SGST");
		sgstSummaryRespList.setUsrCashPaidInterest(new BigDecimal(0.0));
		sgstSummaryRespList.setUsrCashPaidLateFee(new BigDecimal(0.0));
		sgstSummaryRespList.setUsrCashPaidTax(new BigDecimal(0.0));
		sgstSummaryRespList.setUsrItcPaidCess(new BigDecimal(0.0));
		sgstSummaryRespList.setUsrItcPaidCgst(new BigDecimal(0.0));
		sgstSummaryRespList.setUsrItcPaidIgst(new BigDecimal(0.0));
		sgstSummaryRespList.setUsrItcPaidSgst(new BigDecimal(0.0));
		sgstSummaryRespList.setUsrLiability(new BigDecimal(0.0));
		sgstSummaryRespList.setUsrOtherLiability(new BigDecimal(0.0));
		sgstSummaryRespList.setUsrOtherPaid(new BigDecimal(0.0));
		sgstSummaryRespList.setUsrOtherPayable(new BigDecimal(0.0));
		sgstSummaryRespList.setUsrPaid(new BigDecimal(0.0));
		sgstSummaryRespList.setUsrPayable(new BigDecimal(0.0));

		sgstSummaryRespList.setGstnCashPaidInterest(new BigDecimal(0.0));
		sgstSummaryRespList.setGstnCashPaidLateFee(new BigDecimal(0.0));
		sgstSummaryRespList.setGstnCashPaidTax(new BigDecimal(0.0));
		sgstSummaryRespList.setGstnItcPaidCess(new BigDecimal(0.0));
		sgstSummaryRespList.setGstnItcPaidCgst(new BigDecimal(0.0));
		sgstSummaryRespList.setGstnItcPaidIgst(new BigDecimal(0.0));
		sgstSummaryRespList.setGstnItcPaidSgst(new BigDecimal(0.0));
		sgstSummaryRespList.setGstnLiability(new BigDecimal(0.0));
		sgstSummaryRespList.setGstnOtherLiability(new BigDecimal(0.0));
		sgstSummaryRespList.setGstnOtherPaid(new BigDecimal(0.0));
		sgstSummaryRespList.setGstnOtherPayable(new BigDecimal(0.0));
		sgstSummaryRespList.setGstnPaid(new BigDecimal(0.0));
		sgstSummaryRespList.setGstnPayable(new BigDecimal(0.0));

		sgstSummaryRespList.setDiffCashPaidInterest(new BigDecimal(0.0));
		sgstSummaryRespList.setDiffCashPaidLateFee(new BigDecimal(0.0));
		sgstSummaryRespList.setDiffCashPaidTax(new BigDecimal(0.0));
		sgstSummaryRespList.setDiffItcPaidCess(new BigDecimal(0.0));
		sgstSummaryRespList.setDiffItcPaidCgst(new BigDecimal(0.0));
		sgstSummaryRespList.setDiffItcPaidIgst(new BigDecimal(0.0));
		sgstSummaryRespList.setDiffItcPaidSgst(new BigDecimal(0.0));
		sgstSummaryRespList.setDiffLiability(new BigDecimal(0.0));
		sgstSummaryRespList.setDiffOtherLiability(new BigDecimal(0.0));
		sgstSummaryRespList.setDiffOtherPaid(new BigDecimal(0.0));
		sgstSummaryRespList.setDiffOtherPayable(new BigDecimal(0.0));
		sgstSummaryRespList.setDiffPaid(new BigDecimal(0.0));
		sgstSummaryRespList.setDiffPayable(new BigDecimal(0.0));
		taxPaymentList.add(sgstSummaryRespList);

		TaxPaymentSummaryDto cessSummaryRespList = new TaxPaymentSummaryDto();
		cessSummaryRespList.setTable("6");
		cessSummaryRespList.setSection("6.4");
		cessSummaryRespList.setDesc("CESS");
		cessSummaryRespList.setUsrCashPaidInterest(new BigDecimal(0.0));
		cessSummaryRespList.setUsrCashPaidLateFee(new BigDecimal(0.0));
		cessSummaryRespList.setUsrCashPaidTax(new BigDecimal(0.0));
		cessSummaryRespList.setUsrItcPaidCess(new BigDecimal(0.0));
		cessSummaryRespList.setUsrItcPaidCgst(new BigDecimal(0.0));
		cessSummaryRespList.setUsrItcPaidIgst(new BigDecimal(0.0));
		cessSummaryRespList.setUsrItcPaidSgst(new BigDecimal(0.0));
		cessSummaryRespList.setUsrLiability(new BigDecimal(0.0));
		cessSummaryRespList.setUsrOtherLiability(new BigDecimal(0.0));
		cessSummaryRespList.setUsrOtherPaid(new BigDecimal(0.0));
		cessSummaryRespList.setUsrOtherPayable(new BigDecimal(0.0));
		cessSummaryRespList.setUsrPaid(new BigDecimal(0.0));
		cessSummaryRespList.setUsrPayable(new BigDecimal(0.0));

		cessSummaryRespList.setGstnCashPaidInterest(new BigDecimal(0.0));
		cessSummaryRespList.setGstnCashPaidLateFee(new BigDecimal(0.0));
		cessSummaryRespList.setGstnCashPaidTax(new BigDecimal(0.0));
		cessSummaryRespList.setGstnItcPaidCess(new BigDecimal(0.0));
		cessSummaryRespList.setGstnItcPaidCgst(new BigDecimal(0.0));
		cessSummaryRespList.setGstnItcPaidIgst(new BigDecimal(0.0));
		cessSummaryRespList.setGstnItcPaidSgst(new BigDecimal(0.0));
		cessSummaryRespList.setGstnLiability(new BigDecimal(0.0));
		cessSummaryRespList.setGstnOtherLiability(new BigDecimal(0.0));
		cessSummaryRespList.setGstnOtherPaid(new BigDecimal(0.0));
		cessSummaryRespList.setGstnOtherPayable(new BigDecimal(0.0));
		cessSummaryRespList.setGstnPaid(new BigDecimal(0.0));
		cessSummaryRespList.setGstnPayable(new BigDecimal(0.0));

		cessSummaryRespList.setDiffCashPaidInterest(new BigDecimal(0.0));
		cessSummaryRespList.setDiffCashPaidLateFee(new BigDecimal(0.0));
		cessSummaryRespList.setDiffCashPaidTax(new BigDecimal(0.0));
		cessSummaryRespList.setDiffItcPaidCess(new BigDecimal(0.0));
		cessSummaryRespList.setDiffItcPaidCgst(new BigDecimal(0.0));
		cessSummaryRespList.setDiffItcPaidIgst(new BigDecimal(0.0));
		cessSummaryRespList.setDiffItcPaidSgst(new BigDecimal(0.0));
		cessSummaryRespList.setDiffLiability(new BigDecimal(0.0));
		cessSummaryRespList.setDiffOtherLiability(new BigDecimal(0.0));
		cessSummaryRespList.setDiffOtherPaid(new BigDecimal(0.0));
		cessSummaryRespList.setDiffOtherPayable(new BigDecimal(0.0));
		cessSummaryRespList.setDiffPaid(new BigDecimal(0.0));
		cessSummaryRespList.setDiffPayable(new BigDecimal(0.0));
		taxPaymentList.add(cessSummaryRespList);		
		
		
		
		List<Ret1SummaryRespDto> summaryTotalRespList = new ArrayList<>();
		summaryTotalRespList.add(summaryTotalResp);
		summaryTotalRespList.add(summaryB2CaResp);
		summaryTotalRespList.add(expwta);
		summaryTotalRespList.add(expwota);
		summaryTotalRespList.add(priorPerioda);
		
		
		List<Ret1SummaryRespDto> summary3bResplist = new ArrayList<>();
		summary3bResplist.add(summary3bResp);
		summary3bResplist.add(rcInwardResp);
		summary3bResplist.add(imps);
		
		List<Ret1SummaryRespDto> summery3clist = new ArrayList<>();
		summery3clist.add(summery3c);
		summery3clist.add(summery3c1);
		
		List<Ret1SummaryRespDto> summery3dlist = new ArrayList<>();
		summery3dlist.add(summery3d);
		summery3dlist.add(exemptNil_a);
		summery3dlist.add(nonGst_a);
		summery3dlist.add(rcOutward_a);
		summery3dlist.add(sezDta_a);
		
		List<Ret1SummaryRespDto> summery3elist = new ArrayList<>();
		summery3elist.add(summery3e);
		
		List<Ret1SummaryRespDto> summery4alist = new ArrayList<>();
		summery4alist.add(summery4a);
		summery4alist.add(summery4a1);
		summery4alist.add(summery42);
		summery4alist.add(summery4a3);
		summery4alist.add(summery4a4);
		summery4alist.add(summery4a5);
		
		List<Ret1SummaryRespDto> summery4blist = new ArrayList<>();
		summery4blist.add(summery4b1);
		summery4blist.add(summery4b2);
	
		List<Ret1SummaryRespDto> summery4clist = new ArrayList<>();
		summery4clist.add(summery4c);
		
		
		
		
		
		
		Gson gson = GsonUtil.newSAPGsonInstance();

		JsonElement summary3ARespbody = gson.toJsonTree(summaryTotalRespList);
		JsonElement summary3BRespbody = gson.toJsonTree(summary3bResplist);
		JsonElement summary3CRespbody = gson.toJsonTree(summery3clist);
		JsonElement summary3DRespbody = gson.toJsonTree(summery3dlist);
		JsonElement summary3ERespbody = gson.toJsonTree(summery3elist);
		JsonElement summary4ARespbody = gson.toJsonTree(summery4alist);
		JsonElement summary4BRespbody = gson.toJsonTree(summery4blist);
		JsonElement summary4CRespbody = gson.toJsonTree(summery4clist);
		JsonElement summary5Respbody = gson.toJsonTree(LateSummaryResp);
		JsonElement summary6Respbody = gson.toJsonTree(taxPaymentList);

		Map<String, JsonElement> combinedMap = new HashMap<>();
		Map<String, JsonElement> combinedMap5 = new HashMap<>();
		Map<String, JsonElement> combinedMap6 = new HashMap<>();
		combinedMap.put("3A", summary3ARespbody);
		combinedMap.put("3B", summary3BRespbody);
		combinedMap.put("3C", summary3CRespbody);
		combinedMap.put("3D", summary3DRespbody);
		combinedMap.put("3E", summary3ERespbody);
		combinedMap.put("4A", summary4ARespbody);
		combinedMap.put("4B", summary4BRespbody);
		combinedMap.put("4C", summary4CRespbody);
		combinedMap5.put("5", summary5Respbody);
		combinedMap6.put("6", summary6Respbody);

		JsonElement summaryAspVRespbody = gson.toJsonTree(combinedMap);
		JsonElement summaryLateFeeRespbody = gson.toJsonTree(combinedMap5);
		JsonElement taxSummaryRespbody = gson.toJsonTree(combinedMap6);
		
		Map<String, JsonElement> combinedMap2 = new HashMap<>();

		combinedMap2.put("aspValues", summaryAspVRespbody);
		combinedMap2.put("lateFee", summaryLateFeeRespbody);
		combinedMap2.put("taxPayment", taxSummaryRespbody);

		return combinedMap2;

	}
}
