resources:
  repositories:
  - repository: templates
    type: git
    name: SAPDigiGST/DevOps
    ref: refs/heads/main
  
variables:
- name: moduleName
  value: "digigstui"  


name: $(Build.BuildId)

jobs:
- job: Building_DigiGSTUI
  displayName: 'Building DigiGST UI module'
  pool:
    name: 'SAP-CF'
  steps:
  - checkout: templates
  - template: DiGiGST-Build-Pipelines/Pipeline-SAP-UI.yaml@templates  # Template reference with repository