sap.ui.define(function () {
	"use strict";
	return {
		getObject: function () {
			return {
				"sno": "",
				"gstr1SubCategory": "",
				"gstr1TableNo": "",
				"docNo": "",
				"docDate": "",
				"docType": "",
				"fiYear": "",
				"plantCode": "",
				"supplierGstin": "",
				"custGstin": "",
				"ecomCustGSTIN": "",
				"reverseCharge": "",
				"pos": "",
				"custOrSuppCode": "",
				"custOrSuppName": "",
				"sourceIdentifier": "",
				"sourceFileName": "",
				"originalDocNo": "",
				"originalDocDate": "",
				"isError": "",
				"isInfo": "",
				"docAmount": "",
				"isProcessed": "",
				"accountVoucherNo": "",
				"accountVoucherDate": "",
				"division": "",
				"subDivision": "",
				"profitCentre1": "",
				"profitCentre2": "",
				"crDrReason": "",
				"crDrPreGst": "",
				"userDefinedField1": "",
				"userDefinedField2": "",
				"userDefinedField3": "",
				"returnPeriod": "",
				"isDeleted": "",
				"origSupplierGstin": "",
				"billOfEntryNo": "",
				"billOfEntryDate": "",
				"cifValue": "",
				"customDuty": "",

				"eligibilityInd": "",
				"commonSupplyInd": "",
				"availableIgst": "",
				"availableCgst": "",
				"availableSgst": "",
				"availableCess": "",
				"itcReversalId": "",
				"paymentVoucherNum": "",
				"paymentDate": "",
				"contractNo": "",
				"contractDate": "",
				"contractValue": "",
				"id": "",
				"itemNo": "",
				"hsnsacCode": "",
				"supplyType": "",
				"productCode": "",
				"itemDesc": "",
				"itemType": "",
				"itemUqc": "",
				"itemQty": 0,
				"glAccountCode": "",
				"igstRate": "",
				"cgstRate": "",
				"sgstRate": "",
				"igstAmt": 0,
				"cgstAmt": 0,
				"sgstAmt": 0,
				"cessAmtAdvalorem": "",
				"cessAmtSpecfic": "",
				"cessRateAdvalorem": "",
				"cessRateSpecific": "",
				"taxableVal": 0,

				"lineItems": []
			};
		}
	};
});