package com.ey.advisory.inwardEinvoice.initiateRecon;

import lombok.Data;

/**
 * @author Hema G M
 *
 */

@Data
public class InwardEInvoiceReconReportDto {

	//need to declare string variables for following column values - Matching Score	Match Reason	Mismatch Reason	Report Category	Report Type	Previous Report Type (E-INV)	Previous Report Type (PR)	Tax Period (E-INV)	Tax Period (PR)	Calendar Month	Recipient GSTIN (E-INV)	Recipient GSTIN (PR)	Supplier GSTIN (E-INV)	Supplier GSTIN (PR)	Supplier Trade Name (E-INV)	Supplier Legal Name (E-INV)	Supplier Name (PR)	Document Type (E-INV)	Document Type (PR)	Document Number (E-INV)	Document Number (PR)	Document Date (E-INV)	Document Date (PR)	POS (E-INV)	POS (PR)	Taxable Value (E-INV)	Taxable Value (PR)	IGST (E-INV)	IGST (PR)	CGST (E-INV)	CGST (PR)	SGST (E-INV)	SGST (PR)	Cess (E-INV)	Cess (PR)	Total Tax (E-INV)	Total Tax (PR)	Invoice Value (E-INV)	Invoice Value (PR)	Reverse Charge Flag (E-INV)	Reverse Charge Flag (PR)	Eligibility Indicator (PR)	Available IGST (PR)	Available CGST (PR)	Available SGST (PR)	Available Cess (PR)	ITC Reversal Identifier (PR)	ITC Entitlement (PR)	IRN (E-INV)	IRN (PR)	IRN Date (E-INV)	IRN Date (PR)	IRN Status (E-INV)	IRN Cancellation Date (E-INV)	Cancellation Reason (E-INV)	Acknowledgment Number (E-INV)	IRP Name (E-INV)	IRN Get Call Date Time (E-INV)	Supplier GSTIN Status	Supplier GSTIN Cancellation Date	Org Doc Number (E-INV)	Org Doc Number (PR)	Org Doc Date (E-INV)	Org Doc Date (PR)	Org Supplier GSTIN (PR)	Supply Type (E-INV)	Supply Type (PR)	EWB Number (E-INV)	EWB Number (PR)	EWB Date (E-INV)	EWB Date (PR)	Valid Upto (E-INV)	Port Code (E-INV)	Shipping Bill Number (E-INV)	Shipping Bill Date (E-INV)	Currency Code (E-INV)	Export Duty (E-INV)	Country Code (E-INV)	UserID (PR)	Source Identifier (PR)	Source File Name (PR)	Company Code (PR)	Plant Code (PR)	Division (PR)	Sub Division (PR)	Location (PR)	Purchase Organisation (PR)	Profit Centre 1 (PR)	Profit Centre 2 (PR)	Profit Centre 3 (PR)	Profit Centre 4 (PR)	Profit Centre 5 (PR)	Profit Centre 6 (PR)	Profit Centre 7 (PR)	Profit Centre 8 (PR)	HSN (E-INV)	HSN (PR)	Product Code (PR)	Product Description (E-INV)	Product Description (PR)	Category Of Product (PR)	UQC (PR)	Quantity (E-INV)	Quantity (PR)	Accounting Voucher Number (PR)	Accounting Voucher Date (PR)	Customer PO Reference Number (E-INV)	Customer PO Reference Number (PR)	Customer PO Reference Date (E-INV)	Customer PO Reference Date (PR)	Purchase Order Value (PR)	Supplier Code (PR)	Supplier Type (PR)	Supplier Address 1 (PR)	Supplier Address 2 (PR)	Supplier Location (PR)	Supplier Pincode (PR)	Vendor Type	HSN (Vendor Master)	Vendor Risk Category	Vendor Payment Terms (Days)	Vendor Remarks	User Defined Field 1 (PR)	User Defined Field 2 (PR)	User Defined Field 3 (PR)	User Defined Field 4 (PR)	User Defined Field 5 (PR)	User Defined Field 6 (PR)	User Defined Field 7 (PR)	User Defined Field 8 (PR)	User Defined Field 9 (PR)	User Defined Field 10 (PR)	User Defined Field 11 (PR)	User Defined Field 12 (PR)	User Defined Field 13 (PR)	User Defined Field 14 (PR)	User Defined Field 15 (PR)	User Defined Field 28 (PR)	RequestID	ID (PR)	ID (E-INV)	InvoiceKey (PR)	InvoiceKey (E-INV)	ReferenceID (PR)	ReferenceID (E-INV)

	private String matchingScore;
	private String matchReason;
	private String mismatchReason;
	private String reportCategory;
	private String reportType;
	private String previousReportTypeEINV;
	private String previousReportTypePR;
	private String taxPeriodEINV;
	private String taxPeriodPR;
	private String calendarMonth;
	private String recipientGSTINEINV;
	private String recipientGSTINPR;
	private String supplierGSTINEINV;
	private String supplierGSTINPR;
	private String supplierTradeNameEINV;
	private String supplierLegalNameEINV;
	private String supplierNamePR;
	private String documentTypeEINV;
	private String documentTypePR;
	private String documentNumberEINV;
	private String documentNumberPR;
	private String documentDateEINV;
	private String documentDatePR;
	private String posEINV;
	private String posPR;
	private String taxableValueEINV;
	private String taxableValuePR;
	private String igstEINV;
	private String igstPR;
	private String cgstEINV;
	private String cgstPR;
	private String sgstEINV;
	private String sgstPR;
	private String cessEINV;
	private String cessPR;
	private String totalTaxEINV;
private String totalTaxPR;
private String invoiceValueEINV;
private String invoiceValuePR;
private String reverseChargeFlagEINV;
private String reverseChargeFlagPR;
private String eligibilityIndicatorPR;
private String availableIGSTPR;
private String availableCGSTPR;
private String availableSGSTPR;
private String availableCessPR;
private String itcReversalIdentifierPR;
private String itcEntitlementPR;
private String irnEINV;
private String irnPR;
private String irnDateEINV;
private String irnDatePR;
private String irnStatusEINV;
private String irnCancellationDateEINV;
private String cancellationReasonEINV;
private String acknowledgmentNumberEINV;
	private String irpNameEINV;
	private String irnGetCallDateTimeEINV;
	private String supplierGSTINStatus;
	private String supplierGSTINCancellationDate;
	private String orgDocNumberEINV;
	private String orgDocNumberPR;
	private String orgDocDateEINV;
	private String orgDocDatePR;
	private String orgSupplierGSTINPR;
	private String supplyTypeEINV;
	private String supplyTypePR;
	private String ewbNumberEINV;
	private String ewbNumberPR;
	private String ewbDateEINV;
	private String ewbDatePR;
	private String validUptoEINV;
	private String portCodeEINV;
	private String shippingBillNumberEINV;
	private String shippingBillDateEINV;
	private String currencyCodeEINV;
	private String exportDutyEINV;
	private String countryCodeEINV;
	private String userIDPR;
	private String sourceIdentifierPR;
	private String sourceFileNamePR;
	private String companyCodePR;
	private String plantCodePR;
	private String divisionPR;
	private String subDivisionPR;
	private String locationPR;
	private String purchaseOrganisationPR;
	private String profitCentre1PR;
	private String profitCentre2PR;
	private String profitCentre3PR;
	private String profitCentre4PR;
	private String profitCentre5PR;
	private String profitCentre6PR;
	private String profitCentre7PR;
	private String profitCentre8PR;
	private String hsnEINV;
	private String hsnPR;
	private String productCodePR;
	private String productDescriptionEINV;
	private String productDescriptionPR;
	private String categoryOfProductPR;
	private String uqcPR;
	private String quantityEINV;
	private String quantityPR;
	private String accountingVoucherNumberPR;
	private String accountingVoucherDatePR;
	private String customerPOReferenceNumberEINV;
	private String customerPOReferenceNumberPR;
	private String customerPOReferenceDateEINV;
	private String customerPOReferenceDatePR;
	private String purchaseOrderValuePR;
	private String supplierCodePR;
	private String supplierTypePR;
	private String supplierAddress1PR;
	private String supplierAddress2PR;
	private String supplierLocationPR;
	private String supplierPincodePR;
	private String vendorType;
	private String hsnVendorMaster;
	private String vendorRiskCategory;
	private String vendorPaymentTermsDays;
	private String vendorRemarks;
	private String userDefinedField1PR;
	private String userDefinedField2PR;
	private String userDefinedField3PR;
	private String userDefinedField4PR;
	private String userDefinedField5PR;
	private String userDefinedField6PR;
	private String userDefinedField7PR;
	private String userDefinedField8PR;
	private String userDefinedField9PR;
	private String userDefinedField10PR;
	private String userDefinedField11PR;
	private String userDefinedField12PR;
	private String userDefinedField13PR;
	private String userDefinedField14PR;
	private String userDefinedField15PR;
	private String userDefinedField28PR;
	private String requestID;
	private String idPR;
	private String idEINV;
	private String invoiceKeyPR;
	private String invoiceKeyEINV;
	private String referenceIDPR;
	private String referenceIDEINV;

}
