package com.ey.advisory.app.anx2.initiaterecon;

import lombok.Getter;
import lombok.Setter;

/**
 * @author Arun.KA
 *
 */

@Getter
@Setter
public class Anx2InitiateReconReportDto {

	private String userResponse;
	private String suggestedResponse;
	private String currentReportType;
	private String currentMismatchReason;
	private String forcedMatchResponse;
	private String iTCEntitlementAnx2;
	private String iTCEntitlementPR;
	private String informationReportReference;
	private String responseTaxPeriod;
	private String previousReportTypeANX2;
	private String previousReportTypePR;
	private String previousResponseANX2;
	private String previousResponsePR;
	private String savedResponseReportTypeANX2;
	private String digiGSTSavedResponseANX2;
	private String gSTNSavedResponseANX2;
	private String matchingScore;
	private String reconTaxPeriod;
	private String calendarMonthPR;
	private String dateofUploadANX2;
	private String orgMonthANX2;
	private String orgMonthPR;
	private String recipientGSTINANX2;
	private String recipientGSTINPR;
	private String supplierGSTINANX2;
	private String supplierGSTINPR;
	private String supplierNameANX2;
	private String supplierNamePR;
	private String docTypeANX2;
	private String docTypePR;
	private String documentNumberANX2;
	private String documentNumberPR;
	private String documentDateANX2;
	private String documentDatePR;
	private String pOSANX2;
	private String pOSPR;
	private String taxableValueANX2;
	private String taxableValuePR;
	private String totalTaxANX2;
	private String totalTaxPR;
	private String iGSTANX2;
	private String iGSTPR;
	private String cGSTANX2;
	private String cGSTPR;
	private String sGSTANX2;
	private String sGSTPR;
	private String cessANX2;
	private String cessPR;
	private String invoiceValueANX2;
	private String invoiceValuePR;
	private String availableIGST;
	private String availableCGST;
	private String availableSGST;
	private String availableCESS;
	private String tableTypeANX2;
	private String tableTypePR;
	private String cFSFlagANX2;
	private String claimRefundFlagANX2;
	private String claimRefundFlagPR;
	private String section7ofIGSTANX2;
	private String section7ofIGSTPR;
	private String autoPopulateToRefundANX2;
	private String autoPopulateToRefundPR;
	private String differentialPercentageANX2;
	private String differentialPercentagePR;
	private String orgDocTypeANX2;
	private String orgDocTypePR;
	private String orgDocNumberANX2;
	private String orgDocNumberPR;
	private String orgDocDateANX2;
	private String orgDocDatePR;
	private String orgSupplierGSTINPR;
	private String userID;
	private String sourceFileName;
	private String profitCentre;
	private String plant;
	private String division;
	private String location;
	private String purchaseOrganisation;
	private String userAccess1;
	private String userAccess2;
	private String userAccess3;
	private String userAccess4;
	private String userAccess5;
	private String userAccess6;
	private String glCodeTaxableValue;
	private String glCodeIGST;
	private String glCodeCGST;
	private String glCodeSGST;
	private String glCodeAdvaloremCess;
	private String glCodeSpecificCess;
	private String glCodeStateCess;
	private String supplyType;
	private String cRDRPreGST;
	private String supplierType;
	private String supplierCode;
	private String supplierAddress1;
	private String supplierAddress2;
	private String supplierAddress3;
	private String supplierAddress4;
	private String stateApplyingCess;
	private String portCode;
	private String billOfEntry;
	private String billOfEntryDate;
	private String cIFValue;
	private String customDuty;
	private String quantity;
	private String cessAmountAdvalorem;
	private String cessAmountSpecific;
	private String stateCessAmount;
	private String otherValue;
	private String purchaseVoucherNumber;
	private String purchaseVoucherDate;
	private String postingDate;
	private String paymentVoucherNumber;
	private String paymentDate;
	private String contractNumber;
	private String contractDate;
	private String contractValue;
	private String eWayBillNumber;
	private String eWayBillDate;
	private String userDefinedField1;
	private String userDefinedField2;
	private String userDefinedField3;
	private String userDefinedField4;
	private String userDefinedField5;
	private String userDefinedField6;
	private String userDefinedField7;
	private String userDefinedField8;
	private String userDefinedField9;
	private String userDefinedField10;
	private String userDefinedField11;
	private String userDefinedField12;
	private String userDefinedField13;
	private String userDefinedField14;
	private String userDefinedField15;
	private String matchingID;
	private String requestID;
	private String iDPR;
	private String iDA2;
	private String invoiceKeyPR;
	private String invoiceKeyA2;
	private String iDA2DOC_TYPE;
}			

						
