package com.ey.advisory.app.inward.einvoice;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import org.springframework.stereotype.Component;

import com.ey.advisory.common.AppException;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.Query;
import lombok.extern.slf4j.Slf4j;

/**
 * 
 * @author Ravindra V S
 *
 */
@Slf4j
@Component("EinvoicesDetailedLineItemScreenServiceImpl")
public class EinvoicesDetailedLineItemScreenServiceImpl
		implements EinvoicesDetailedLineItemScreenService {

	@PersistenceContext(unitName = "clientDataUnit")
	private EntityManager entityManager;
	
	@Override
	public List<EinvoiceDetailedLineItemReportDto> findTableData(
			String irnNum) {
		List<EinvoiceDetailedLineItemReportDto> respDto = new ArrayList<>();
		try {

			String condtion = queryCondition(irnNum);
			String queryString = createQuery(condtion);

			Query q = entityManager.createNativeQuery(queryString);

			q.setParameter("irnNum", irnNum);

			@SuppressWarnings("unchecked")
			List<Object[]> list = q.getResultList();

			respDto = list.stream().map(o -> convert(o))
					.collect(Collectors.toCollection(ArrayList::new));

			

		} catch (Exception ex) {
			String msg = String.format(
					"Error Occured while executing INV Mngt Screen query", ex);
			LOGGER.error(msg, ex);
			throw new AppException(msg, ex);
		}

		return respDto;
	}

	private static String queryCondition(String irnNum) {
		if (LOGGER.isDebugEnabled()) {
			String msg = " Begin EinvoicesDetailedLineItemScreenServiceImpl .queryCondition() ";
			LOGGER.debug(msg);
		}

		StringBuilder condition1 = new StringBuilder();


		if (!irnNum.isEmpty()) {
			condition1.append(" HDR.irn = :irnNum ");
		}

		return condition1.toString();
	}

	private static String createQuery(String condition) {

		StringBuilder query = new StringBuilder();
	
		query.append(
						 " SELECT HDR.IRN_GENERATION_PERIOD 			AS IRN_GENERATION_PERIOD , "
						+ " HDR.IRN_STATUS 		  			AS IRN_STATUS, "
						+ " HDR.IRN 				  			AS IRN_NUMBER, "
						+ " HDR.IRN_DATE_TIME			  		AS IRN_DATE, "
						+ " HDR.ACK_NUM 			  			AS ACKNOWLEDGMENT_NUMBER, "
						+ " HDR.IRN_CANCEL_DATE_TIME      		AS IRN_CANCELLATION_DATE, "
						+ " HDR.CANCELLATION_REASON   			AS CANCELLATION_REASON, "
						+ " HDR.CANCELLATION_REMARKS  			AS CANCELLATION_REMARKS, "
						+ " HDR.EWAY_BILL_NUMBER			  	AS E_WAY_BILL_NUMBER, "
						+ " HDR.EWAY_BILL_DATE 			  	AS E_WAY_BILL_DATE, "
						+ " HDR.VALID_UPTO            			AS VALID_UPTO, "
						+ " HDR.TAX_SCHEME            			AS TAX_SCHEME, "
						+ " HDR.SUPPLY_TYPE 		  			AS SUPPLYTYPE, "
						+ " HDR.DOC_TYPE 			  			AS DOCUMENTTYPE, "
						+ " HDR.DOC_NUM  			  			AS DOCUMENTNUMBER, "
						+ " HDR.DOC_DATE 			  			AS DOCUMENTDATE, "
						+ " HDR.REVERSECHARGEFLAG     			AS REVERSECHARGEFLAG, "
						+ " HDR.SUPPLIER_GSTIN 		  			AS SUPPLIERGSTIN, "
						+ " HDR.SUPPLIER_TRADENAME    			AS SUPPLIERTRADENAME, "
						+ " HDR.SUPPLIER_LEGALNAME    			AS SUPPLIERLEGALNAME, "
						+ " HDR.SUPPLIER_ADDRESS1     			AS SUPPLIERADDRESS1, "
						+ " HDR.SUPPLIER_ADDRESS2     			AS SUPPLIERADDRESS2, "
						+ " HDR.SUPPLIER_LOCATION     			AS SUPPLIERLOCATION, "
						+ " HDR.SUPPLIER_PINCODE      			AS SUPPLIERPINCODE, "
						+ " HDR.SUPPLIER_STATECODE    			AS SUPPLIERSTATECODE, "
						+ " HDR.SUPPLIER_PHONE        			AS SUPPLIERPHONE, "
						+ " HDR.SUPPLIER_EMAIL        			AS SUPPLIEREMAIL, "
						+ " HDR.CUSTOMER_GSTIN           			AS CUSTOMERGSTIN, "
						+ " HDR.CUSTOMER_TRADENAME    			AS CUSTOMERTRADENAME, "
						+ " HDR.CUSTOMER_LEGALNAME    			AS CUSTOMERLEGALNAME, "
						+ " HDR.CUSTOMER_ADDRESS1     			AS CUSTOMERADDRESS1, "
						+ " HDR.CUSTOMER_ADDRESS2     			AS CUSTOMERADDRESS2, "
						+ " HDR.CUSTOMER_LOCATION     			AS CUSTOMERLOCATION, "
						+ " HDR.CUSTOMER_PINCODE      			AS CUSTOMERPINCODE, "
						+ " HDR.CUSTOMER_STATECODE    			AS CUSTOMERSTATECODE, "
						+ " HDR.BILLING_POS           			AS BILLINGPOS, "
						+ " HDR.CUSTOMER_PHONE        			AS CUSTOMERPHONE, "
						+ " HDR.CUSTOMER_EMAIL        			AS CUSTOMEREMAIL, "
						+ " HDR.DISPATCHER_TRADENAME  			AS DISPATCHERTRADENAME, "
						+ " HDR.DISPATCHER_ADDRESS1   			AS DISPATCHERADDRESS1, "
						+ " HDR.DISPATCHER_ADDRESS2   			AS DISPATCHERADDRESS2, "
						+ " HDR.DISPATCHER_LOCATION   			AS DISPATCHERLOCATION, "
						+ " HDR.DISPATCHER_PINCODE    			AS DISPATCHERPINCODE, "
						+ " HDR.DISPATCHER_STATECODE  			AS DISPATCHERSTATECODE, "
						+ " HDR.SHIP_TO_GSTIN 		  			AS SHIPTOGSTIN, "
						+ " HDR.SHIP_TO_TRADENAME     			AS SHIPTOTRADENAME, "
						+ " HDR.SHIP_TO_LEGALNAME     			AS SHIPTOLEGALNAME, "
						+ " HDR.SHIP_TO_ADDRESS1      			AS SHIPTOADDRESS1, "
						+ " HDR.SHIP_TO_ADDRESS2      			AS SHIPTOADDRESS2, "
						+ " HDR.SHIP_TO_LOCATION      			AS SHIPTOLOCATION, "
						+ " HDR.SHIP_TO_PINCODE       			AS SHIPTOPINCODE, "
						+ " HDR.SHIP_TO_STATECODE     			AS SHIPTOSTATECODE, "
						+ " ITM.ITEM_SERIAL_NUMBER    			AS ITEMSERIALNUMBER, "
						+ " ITM.PRODUCT_SERIAL_NUMBER 			AS PRODUCTSERIALNUMBER, "
						+ " ITM.PRODUCT_DESCRIPTION   			AS PRODUCTDESCRIPTION, "
						+ " ITM.IS_SERVICE 			  			AS ISSERVICE, "
						+ " ITM.HSN 				  			AS HSN, "
						+ " ITM.BARCODE 			  			AS BARCODE, "
						+ " ITM.BATCH_NAME 			  			AS BATCHNAME, "
						+ " ITM.BATCH_EXPIRY_DATE     			AS BATCHEXPIRYDATE, "
						+ " ITM.WARRANTY_DATE 		  			AS WARRANTYDATE, "
						+ " ITM.ORDER_LINE_REFERENCE  			AS ORDERLINEREFERENCE, "
						+ " ITM.ATTRIBUTE_NAME        			AS ATTRIBUTENAME, "
						+ " ITM.ATTRIBUTE_VALUE       			AS ATTRIBUTEVALUE, "
						+ " ITM.ORIGIN_COUNTRY        			AS ORIGINCOUNTRY, "
						+ " ITM.UQC 				  			AS UQC, "
						+ " ITM.QUANTITY 			  			AS QUANTITY, "
						+ " ITM.FREE_QUANTITY 		  			AS FREEQUANTITY, "
						+ " ITM.UNIT_PRICE            			AS UNITPRICE, "
						+ " ITM.ITEM_AMOUNT           			AS ITEMAMOUNT, "
						+ " ITM.ITEM_DISCOUNT         			AS ITEMDISCOUNT, "
						+ " ITM.PRE_TAX_AMOUNT        			AS PRETAXAMOUNT, "
						+ " ITM.ITEM_ASSESSABLE_AMT   			AS ITEMASSESSABLEAMOUNT, "
						+ " ITM.IGST_RATE             			AS IGSTRATE, "
						+ " ITM.IGST_AMOUNT           			AS IGSTAMOUNT, "
						+ " ITM.CGST_RATE             			AS CGSTRATE, "
						+ " ITM.CGST_AMOUNT           			AS CGSTAMOUNT, "
						+ " ITM.SGST_RATE             			AS SGSTRATE, "
						+ " ITM.SGST_AMOUNT           			AS SGSTAMOUNT, "
						+ " ITM.CESS_ADVALOREM_RATE   			AS CESSADVALOREMRATE, "
						+ " ITM.CESS_ADVALOREM_AMOUNT 			AS CESSADVALOREMAMOUNT, "
						+ " ITM.CESS_SPECIFIC_AMOUNT  			AS CESSSPECIFICAMOUNT, "
						+ " ITM.STATE_CESS_ADVALOREM_RATE 		AS STATECESSADVALOREMRATE, "
						+ " ITM.STATE_CESS_ADVALOREM_AMOUNT 	AS STATECESSADVALOREMAMOUNT, "
						+ " ITM.STATE_CESS_SPECIFIC_AMOUNT 		AS STATECESSSPECIFICAMOUNT, "
						+ " ITM.ITEM_OTHER_CHARGES              AS ITEMOTHERCHARGES, "
						+ " ITM.TOTAL_ITEM_AMOUNT               AS TOTALITEMAMOUNT, "
						+ " HDR.INV_OTHER_CHARGES               AS INVOICEOTHERCHARGES, "
						+ " HDR.INV_ASSESSABLE_AMT              AS INVOICEASSESSABLEAMOUNT, "
						+ " HDR.INV_IGST_AMT                    AS INVOICEIGSTAMOUNT, "
						+ " HDR.INV_CGST_AMT                    AS INVOICECGSTAMOUNT, "
						+ " HDR.INV_SGST_AMT                    AS INVOICESGSTAMOUNT, "
						+ " HDR.INV_CESS_ADVALOREM_AMT          AS INVOICECESSADVALOREMAMOUNT, "
						+ " HDR.INV_CESS_SPECIFIC_AMT           AS INVOICECESSSPECIFICAMOUNT, "
						+ " HDR.INV_STATECESS_ADVALOREM_AMT     AS INVOICESTATECESSADVALOREMAMOUNT, "
						+ " HDR.INV_STATECESS_SPECIFIC_AMT      AS INVOICESTATECESSSPECIFICAMOUNT, "
						+ " HDR.DISCOUNT 					AS INVOICE_DISCOUNT, "
						+ " HDR.INV_VALUE     					AS INVOICEVALUE, "
						+ " HDR.ROUNDOFF      					AS ROUNDOFF, "
						+ " HDR.CURRENCY_CODE 					AS CURRENCYCODE, "
						+ " HDR.COUNTRY_CODE  					AS COUNTRYCODE, "
						+ " HDR.INVOICE_VALUE_FC 				AS INVOICEVALUEFC, "
						+ " HDR.PORT_CODE  					AS PORTCODE, "
						+ " HDR.SHIPPING_BILL_NUMBER 			AS SHIPPINGBILLNUMBER, "
						+ " HDR.SHIPPING_BILL_DATE   			AS SHIPPINGBILLDATE, "
						+ " HDR.INVOICE_REMARKS 	 			AS INVOICEREMARKS, "
						+ " HDR.INVOICE_PERIOD_START_DATE 		AS INVOICEPERIODSTARTDATE, "
						+ " HDR.INVOICE_PERIOD_END_DATE   		AS INVOICEPERIODENDDATE, "
						+ " ITM.PRECEEDING_INVOICE_NUMBER 		AS PRECEEDINGINVOICENUMBER, "
						+ " ITM.PRECEEDING_INVOICE_DATE   		AS PRECEEDINGINVOICEDATE, "
						+ " ITM.OTHER_REFERENCE           		AS OTHERREFERENCE, "
						+ " ITM.RECEIPT_ADVICE_REFERENCE  		AS RECEIPTADVICEREFERENCE, "
						+ " ITM.RECEIPT_ADVICE_DATE       		AS RECEIPTADVICEDATE, "
						+ " ITM.TENDER_REFERENCE   		  		AS TENDERREFERENCE, "
						+ " ITM.CONTRACT_REFERENCE 		  		AS CONTRACTREFERENCE, "
						+ " ITM.EXTERNAL_REFERENCE 		  		AS EXTERNALREFERENCE, "
						+ " ITM.PROJECT_REFERENCE  		  		AS PROJECTREFERENCE, "
						+ " ITM.CUSTOMER_PO_REFERENCE_NUMBER    AS CUSTOMERPOREFERENCENUMBER, "
						+ " ITM.CUSTOMER_PO_REFERENCE_DATE      AS CUSTOMERPOREFERENCEDATE, "
						+ " HDR.PAYEE_NAME 						AS PAYEENAME, "
						+ " HDR.MODE_OF_PAYMENT 				AS MODEOFPAYMENT, "
						+ " HDR.BRANCH_OR_IFSC_CODE 			AS BRANCHORIFSCCODE, "
						+ " HDR.PAYMENT_TERMS 					AS PAYMENTTERMS, "
						+ " HDR.PAYMENT_INSTRUCTION 			AS PAYMENTINSTRUCTION, "
						+ " HDR.CREDIT_TRANSFER 				AS CREDITTRANSFER, "
						+ " HDR.DIRECT_DEBIT   					AS DIRECTDEBIT, "
						+ " HDR.CREDIT_DAYS    					AS CREDITDAYS, "
						+ " HDR.PAID_AMOUNT    					AS PAIDAMOUNT, "
						+ " HDR.BALANCE_AMOUNT 					AS BALANCEAMOUNT, "
						+ " HDR.ACCOUNT_DETAIL 					AS ACCOUNTDETAIL, "
						+ " HDR.ECOM_GSTIN 						AS ECOMGSTIN, "
						+ " ITM.SUPPORTING_DOC_URL     			AS SUPPORTINGDOCURL, "
						+ " ITM.SUPPORTING_DOCUMENT    			AS SUPPORTINGDOCUMENT, "
						+ " ITM.ADDITIONAL_INFORMATION 			AS ADDITIONALINFORMATION, "
						+ " HDR.TRANSPORTER_ID         			AS TRANSPORTERID, "
						+ " HDR.TRANSPORTER_NAME 	   			AS TRANSPORTERNAME, "
						+ " HDR.TRANSPORT_MODE         			AS TRANSPORTMODE, "
						+ " HDR.TRANSPORT_DOCNO        			AS TRANSPORTDOCNO, "
						+ " HDR.TRANSPORT_DOCDATE 				AS TRANSPORTDOCDATE, "
						+ " HDR.DISTANCE  						 AS DISTANCE, "
						+ " HDR.VEHICLENO 							AS VEHICLENO, "
						+ " HDR.VEHICLE_TYPE 					AS VEHICLETYPE, "
						+ " HDR.SECTION7OFIGSTFLAG 				AS SECTION7OFIGSTFLAG, "
						+ " HDR.CLAIMREFUNDFLAG 				AS CLAIMREFUNDFLAG, "
						+ " HDR.EXPORT_DUTY 					AS EXPORTDUTY, "
						+ " HDR.CREATED_ON 					    AS IRN_GET_CALL_DATE_TIME, "
						+ " HDR.BATCH_ID                       AS BATCH_ID, "
						+ " HDR.ID       AS HEADER_ID, "
						+ " ITM.ID        AS ITEM_ID, "
						+ " HDR.IRP_NAME        AS IRP_NAME "
						+ " FROM  TBL_GETIRN_LIST LST INNER JOIN "
						+ " TBL_GETIRN_B2B_HEADER HDR ON LST.BATCH_ID = HDR.BATCH_ID  "
						+ " AND LST.IRN=HDR.IRN  AND LST.IRN_STATUS=HDR.IRN_STATUS "
						+ " LEFT JOIN TBL_GETIRN_B2B_ITEM ITM ON HDR.ID = ITM.HEADER_ID  "
						+ " WHERE " + condition
						+ " AND LST.IS_DELETE = FALSE  "
						+ " AND UPPER(LST.GET_DETAIL_IRN_STATUS) = 'SUCCESS' "
						+ "  UNION ALL "
						  + " SELECT HDR.IRN_GENERATION_PERIOD 			AS IRN_GENERATION_PERIOD , "
							+ " HDR.IRN_STATUS 		  			AS IRN_STATUS, "
							+ " HDR.IRN 				  			AS IRN_NUMBER, "
							+ " HDR.IRN_DATE_TIME			  		AS IRN_DATE, "
							+ " HDR.ACK_NUM 			  			AS ACKNOWLEDGMENT_NUMBER, "
							+ " HDR.IRN_CANCEL_DATE_TIME      		AS IRN_CANCELLATION_DATE, "
							+ " HDR.CANCELLATION_REASON   			AS CANCELLATION_REASON, "
							+ " HDR.CANCELLATION_REMARKS  			AS CANCELLATION_REMARKS, "
							+ " HDR.EWAY_BILL_NUMBER			  	AS E_WAY_BILL_NUMBER, "
							+ " HDR.EWAY_BILL_DATE 			  	AS E_WAY_BILL_DATE, "
							+ " HDR.VALID_UPTO            			AS VALID_UPTO, "
							+ " HDR.TAX_SCHEME            			AS TAX_SCHEME, "
							+ " HDR.SUPPLY_TYPE 		  			AS SUPPLYTYPE, "
							+ " HDR.DOC_TYPE 			  			AS DOCUMENTTYPE, "
							+ " HDR.DOC_NUM  			  			AS DOCUMENTNUMBER, "
							+ " HDR.DOC_DATE 			  			AS DOCUMENTDATE, "
							+ " HDR.REVERSECHARGEFLAG     			AS REVERSECHARGEFLAG, "
							+ " HDR.SUPPLIER_GSTIN 		  			AS SUPPLIERGSTIN, "
							+ " HDR.SUPPLIER_TRADENAME    			AS SUPPLIERTRADENAME, "
							+ " HDR.SUPPLIER_LEGALNAME    			AS SUPPLIERLEGALNAME, "
							+ " HDR.SUPPLIER_ADDRESS1     			AS SUPPLIERADDRESS1, "
							+ " HDR.SUPPLIER_ADDRESS2     			AS SUPPLIERADDRESS2, "
							+ " HDR.SUPPLIER_LOCATION     			AS SUPPLIERLOCATION, "
							+ " HDR.SUPPLIER_PINCODE      			AS SUPPLIERPINCODE, "
							+ " HDR.SUPPLIER_STATECODE    			AS SUPPLIERSTATECODE, "
							+ " HDR.SUPPLIER_PHONE        			AS SUPPLIERPHONE, "
							+ " HDR.SUPPLIER_EMAIL        			AS SUPPLIEREMAIL, "
							+ " HDR.CUSTOMER_GSTIN           			AS CUSTOMERGSTIN, "
							+ " HDR.CUSTOMER_TRADENAME    			AS CUSTOMERTRADENAME, "
							+ " HDR.CUSTOMER_LEGALNAME    			AS CUSTOMERLEGALNAME, "
							+ " HDR.CUSTOMER_ADDRESS1     			AS CUSTOMERADDRESS1, "
							+ " HDR.CUSTOMER_ADDRESS2     			AS CUSTOMERADDRESS2, "
							+ " HDR.CUSTOMER_LOCATION     			AS CUSTOMERLOCATION, "
							+ " HDR.CUSTOMER_PINCODE      			AS CUSTOMERPINCODE, "
							+ " HDR.CUSTOMER_STATECODE    			AS CUSTOMERSTATECODE, "
							+ " HDR.BILLING_POS           			AS BILLINGPOS, "
							+ " HDR.CUSTOMER_PHONE        			AS CUSTOMERPHONE, "
							+ " HDR.CUSTOMER_EMAIL        			AS CUSTOMEREMAIL, "
							+ " HDR.DISPATCHER_TRADENAME  			AS DISPATCHERTRADENAME, "
							+ " HDR.DISPATCHER_ADDRESS1   			AS DISPATCHERADDRESS1, "
							+ " HDR.DISPATCHER_ADDRESS2   			AS DISPATCHERADDRESS2, "
							+ " HDR.DISPATCHER_LOCATION   			AS DISPATCHERLOCATION, "
							+ " HDR.DISPATCHER_PINCODE    			AS DISPATCHERPINCODE, "
							+ " HDR.DISPATCHER_STATECODE  			AS DISPATCHERSTATECODE, "
							+ " HDR.SHIP_TO_GSTIN 		  			AS SHIPTOGSTIN, "
							+ " HDR.SHIP_TO_TRADENAME     			AS SHIPTOTRADENAME, "
							+ " HDR.SHIP_TO_LEGALNAME     			AS SHIPTOLEGALNAME, "
							+ " HDR.SHIP_TO_ADDRESS1      			AS SHIPTOADDRESS1, "
							+ " HDR.SHIP_TO_ADDRESS2      			AS SHIPTOADDRESS2, "
							+ " HDR.SHIP_TO_LOCATION      			AS SHIPTOLOCATION, "
							+ " HDR.SHIP_TO_PINCODE       			AS SHIPTOPINCODE, "
							+ " HDR.SHIP_TO_STATECODE     			AS SHIPTOSTATECODE, "
							+ " ITM.ITEM_SERIAL_NUMBER    			AS ITEMSERIALNUMBER, "
							+ " ITM.PRODUCT_SERIAL_NUMBER 			AS PRODUCTSERIALNUMBER, "
							+ " ITM.PRODUCT_DESCRIPTION   			AS PRODUCTDESCRIPTION, "
							+ " ITM.IS_SERVICE 			  			AS ISSERVICE, "
							+ " ITM.HSN 				  			AS HSN, "
							+ " ITM.BARCODE 			  			AS BARCODE, "
							+ " ITM.BATCH_NAME 			  			AS BATCHNAME, "
							+ " ITM.BATCH_EXPIRY_DATE     			AS BATCHEXPIRYDATE, "
							+ " ITM.WARRANTY_DATE 		  			AS WARRANTYDATE, "
							+ " ITM.ORDER_LINE_REFERENCE  			AS ORDERLINEREFERENCE, "
							+ " ITM.ATTRIBUTE_NAME        			AS ATTRIBUTENAME, "
							+ " ITM.ATTRIBUTE_VALUE       			AS ATTRIBUTEVALUE, "
							+ " ITM.ORIGIN_COUNTRY        			AS ORIGINCOUNTRY, "
							+ " ITM.UQC 				  			AS UQC, "
							+ " ITM.QUANTITY 			  			AS QUANTITY, "
							+ " ITM.FREE_QUANTITY 		  			AS FREEQUANTITY, "
							+ " ITM.UNIT_PRICE            			AS UNITPRICE, "
							+ " ITM.ITEM_AMOUNT           			AS ITEMAMOUNT, "
							+ " ITM.ITEM_DISCOUNT         			AS ITEMDISCOUNT, "
							+ " ITM.PRE_TAX_AMOUNT        			AS PRETAXAMOUNT, "
							+ " ITM.ITEM_ASSESSABLE_AMT   			AS ITEMASSESSABLEAMOUNT, "
							+ " ITM.IGST_RATE             			AS IGSTRATE, "
							+ " ITM.IGST_AMOUNT           			AS IGSTAMOUNT, "
							+ " ITM.CGST_RATE             			AS CGSTRATE, "
							+ " ITM.CGST_AMOUNT           			AS CGSTAMOUNT, "
							+ " ITM.SGST_RATE             			AS SGSTRATE, "
							+ " ITM.SGST_AMOUNT           			AS SGSTAMOUNT, "
							+ " ITM.CESS_ADVALOREM_RATE   			AS CESSADVALOREMRATE, "
							+ " ITM.CESS_ADVALOREM_AMOUNT 			AS CESSADVALOREMAMOUNT, "
							+ " ITM.CESS_SPECIFIC_AMOUNT  			AS CESSSPECIFICAMOUNT, "
							+ " ITM.STATE_CESS_ADVALOREM_RATE 		AS STATECESSADVALOREMRATE, "
							+ " ITM.STATE_CESS_ADVALOREM_AMOUNT 	AS STATECESSADVALOREMAMOUNT, "
							+ " ITM.STATE_CESS_SPECIFIC_AMOUNT 		AS STATECESSSPECIFICAMOUNT, "
							+ " ITM.ITEM_OTHER_CHARGES              AS ITEMOTHERCHARGES, "
							+ " ITM.TOTAL_ITEM_AMOUNT               AS TOTALITEMAMOUNT, "
							+ " HDR.INV_OTHER_CHARGES               AS INVOICEOTHERCHARGES, "
							+ " HDR.INV_ASSESSABLE_AMT              AS INVOICEASSESSABLEAMOUNT, "
							+ " HDR.INV_IGST_AMT                    AS INVOICEIGSTAMOUNT, "
							+ " HDR.INV_CGST_AMT                    AS INVOICECGSTAMOUNT, "
							+ " HDR.INV_SGST_AMT                    AS INVOICESGSTAMOUNT, "
							+ " HDR.INV_CESS_ADVALOREM_AMT          AS INVOICECESSADVALOREMAMOUNT, "
							+ " HDR.INV_CESS_SPECIFIC_AMT           AS INVOICECESSSPECIFICAMOUNT, "
							+ " HDR.INV_STATECESS_ADVALOREM_AMT     AS INVOICESTATECESSADVALOREMAMOUNT, "
							+ " HDR.INV_STATECESS_SPECIFIC_AMT      AS INVOICESTATECESSSPECIFICAMOUNT, "
							+ " HDR.DISCOUNT 					AS INVOICE_DISCOUNT, "
							+ " HDR.INV_VALUE     					AS INVOICEVALUE, "
							+ " HDR.ROUNDOFF      					AS ROUNDOFF, "
							+ " HDR.CURRENCY_CODE 					AS CURRENCYCODE, "
							+ " HDR.COUNTRY_CODE  					AS COUNTRYCODE, "
							+ " HDR.INVOICE_VALUE_FC 				AS INVOICEVALUEFC, "
							+ " HDR.PORT_CODE  					AS PORTCODE, "
							+ " HDR.SHIPPING_BILL_NUMBER 			AS SHIPPINGBILLNUMBER, "
							+ " HDR.SHIPPING_BILL_DATE   			AS SHIPPINGBILLDATE, "
							+ " HDR.INVOICE_REMARKS 	 			AS INVOICEREMARKS, "
							+ " HDR.INVOICE_PERIOD_START_DATE 		AS INVOICEPERIODSTARTDATE, "
							+ " HDR.INVOICE_PERIOD_END_DATE   		AS INVOICEPERIODENDDATE, "
							+ " ITM.PRECEEDING_INVOICE_NUMBER 		AS PRECEEDINGINVOICENUMBER, "
							+ " ITM.PRECEEDING_INVOICE_DATE   		AS PRECEEDINGINVOICEDATE, "
							+ " ITM.OTHER_REFERENCE           		AS OTHERREFERENCE, "
							+ " ITM.RECEIPT_ADVICE_REFERENCE  		AS RECEIPTADVICEREFERENCE, "
							+ " ITM.RECEIPT_ADVICE_DATE       		AS RECEIPTADVICEDATE, "
							+ " ITM.TENDER_REFERENCE   		  		AS TENDERREFERENCE, "
							+ " ITM.CONTRACT_REFERENCE 		  		AS CONTRACTREFERENCE, "
							+ " ITM.EXTERNAL_REFERENCE 		  		AS EXTERNALREFERENCE, "
							+ " ITM.PROJECT_REFERENCE  		  		AS PROJECTREFERENCE, "
							+ " ITM.CUSTOMER_PO_REFERENCE_NUMBER    AS CUSTOMERPOREFERENCENUMBER, "
							+ " ITM.CUSTOMER_PO_REFERENCE_DATE      AS CUSTOMERPOREFERENCEDATE, "
							+ " HDR.PAYEE_NAME 						AS PAYEENAME, "
							+ " HDR.MODE_OF_PAYMENT 				AS MODEOFPAYMENT, "
							+ " HDR.BRANCH_OR_IFSC_CODE 			AS BRANCHORIFSCCODE, "
							+ " HDR.PAYMENT_TERMS 					AS PAYMENTTERMS, "
							+ " HDR.PAYMENT_INSTRUCTION 			AS PAYMENTINSTRUCTION, "
							+ " HDR.CREDIT_TRANSFER 				AS CREDITTRANSFER, "
							+ " HDR.DIRECT_DEBIT   					AS DIRECTDEBIT, "
							+ " HDR.CREDIT_DAYS    					AS CREDITDAYS, "
							+ " HDR.PAID_AMOUNT    					AS PAIDAMOUNT, "
							+ " HDR.BALANCE_AMOUNT 					AS BALANCEAMOUNT, "
							+ " HDR.ACCOUNT_DETAIL 					AS ACCOUNTDETAIL, "
							+ " HDR.ECOM_GSTIN 						AS ECOMGSTIN, "
							+ " ITM.SUPPORTING_DOC_URL     			AS SUPPORTINGDOCURL, "
							+ " ITM.SUPPORTING_DOCUMENT    			AS SUPPORTINGDOCUMENT, "
							+ " ITM.ADDITIONAL_INFORMATION 			AS ADDITIONALINFORMATION, "
							+ " HDR.TRANSPORTER_ID         			AS TRANSPORTERID, "
							+ " HDR.TRANSPORTER_NAME 	   			AS TRANSPORTERNAME, "
							+ " HDR.TRANSPORT_MODE         			AS TRANSPORTMODE, "
							+ " HDR.TRANSPORT_DOCNO        			AS TRANSPORTDOCNO, "
							+ " HDR.TRANSPORT_DOCDATE 				AS TRANSPORTDOCDATE, "
							+ " HDR.DISTANCE  						 AS DISTANCE, "
							+ " HDR.VEHICLENO 							AS VEHICLENO, "
							+ " HDR.VEHICLE_TYPE 					AS VEHICLETYPE, "
							+ " HDR.SECTION7OFIGSTFLAG 				AS SECTION7OFIGSTFLAG, "
							+ " HDR.CLAIMREFUNDFLAG 				AS CLAIMREFUNDFLAG, "
							+ " HDR.EXPORT_DUTY 					AS EXPORTDUTY, "
							+ " HDR.CREATED_ON 					    AS IRN_GET_CALL_DATE_TIME, "
							+ " HDR.BATCH_ID                       AS BATCH_ID, "
							+ " HDR.ID       AS HEADER_ID, "
							+ " ITM.ID        AS ITEM_ID, "
							+ " HDR.IRP_NAME        AS IRP_NAME "
							+ " FROM  TBL_GETIRN_LIST LST INNER JOIN "
							+ " TBL_GETIRN_SEZWP_HEADER HDR ON LST.BATCH_ID = HDR.BATCH_ID  "
							+ " AND LST.IRN=HDR.IRN  AND LST.IRN_STATUS=HDR.IRN_STATUS "
							+ " LEFT JOIN TBL_GETIRN_SEZWP_ITEM ITM ON HDR.ID = ITM.HEADER_ID  "
							+ " WHERE " + condition
							+ " AND LST.IS_DELETE = FALSE  "
							+ " AND UPPER(LST.GET_DETAIL_IRN_STATUS) = 'SUCCESS' "
							+ " UNION ALL "
							  + " SELECT HDR.IRN_GENERATION_PERIOD 			AS IRN_GENERATION_PERIOD , "
								+ " HDR.IRN_STATUS 		  			AS IRN_STATUS, "
								+ " HDR.IRN 				  			AS IRN_NUMBER, "
								+ " HDR.IRN_DATE_TIME			  		AS IRN_DATE, "
								+ " HDR.ACK_NUM 			  			AS ACKNOWLEDGMENT_NUMBER, "
								+ " HDR.IRN_CANCEL_DATE_TIME      		AS IRN_CANCELLATION_DATE, "
								+ " HDR.CANCELLATION_REASON   			AS CANCELLATION_REASON, "
								+ " HDR.CANCELLATION_REMARKS  			AS CANCELLATION_REMARKS, "
								+ " HDR.EWAY_BILL_NUMBER			  	AS E_WAY_BILL_NUMBER, "
								+ " HDR.EWAY_BILL_DATE 			  	AS E_WAY_BILL_DATE, "
								+ " HDR.VALID_UPTO            			AS VALID_UPTO, "
								+ " HDR.TAX_SCHEME            			AS TAX_SCHEME, "
								+ " HDR.SUPPLY_TYPE 		  			AS SUPPLYTYPE, "
								+ " HDR.DOC_TYPE 			  			AS DOCUMENTTYPE, "
								+ " HDR.DOC_NUM  			  			AS DOCUMENTNUMBER, "
								+ " HDR.DOC_DATE 			  			AS DOCUMENTDATE, "
								+ " HDR.REVERSECHARGEFLAG     			AS REVERSECHARGEFLAG, "
								+ " HDR.SUPPLIER_GSTIN 		  			AS SUPPLIERGSTIN, "
								+ " HDR.SUPPLIER_TRADENAME    			AS SUPPLIERTRADENAME, "
								+ " HDR.SUPPLIER_LEGALNAME    			AS SUPPLIERLEGALNAME, "
								+ " HDR.SUPPLIER_ADDRESS1     			AS SUPPLIERADDRESS1, "
								+ " HDR.SUPPLIER_ADDRESS2     			AS SUPPLIERADDRESS2, "
								+ " HDR.SUPPLIER_LOCATION     			AS SUPPLIERLOCATION, "
								+ " HDR.SUPPLIER_PINCODE      			AS SUPPLIERPINCODE, "
								+ " HDR.SUPPLIER_STATECODE    			AS SUPPLIERSTATECODE, "
								+ " HDR.SUPPLIER_PHONE        			AS SUPPLIERPHONE, "
								+ " HDR.SUPPLIER_EMAIL        			AS SUPPLIEREMAIL, "
								+ " HDR.CUSTOMER_GSTIN           			AS CUSTOMERGSTIN, "
								+ " HDR.CUSTOMER_TRADENAME    			AS CUSTOMERTRADENAME, "
								+ " HDR.CUSTOMER_LEGALNAME    			AS CUSTOMERLEGALNAME, "
								+ " HDR.CUSTOMER_ADDRESS1     			AS CUSTOMERADDRESS1, "
								+ " HDR.CUSTOMER_ADDRESS2     			AS CUSTOMERADDRESS2, "
								+ " HDR.CUSTOMER_LOCATION     			AS CUSTOMERLOCATION, "
								+ " HDR.CUSTOMER_PINCODE      			AS CUSTOMERPINCODE, "
								+ " HDR.CUSTOMER_STATECODE    			AS CUSTOMERSTATECODE, "
								+ " HDR.BILLING_POS           			AS BILLINGPOS, "
								+ " HDR.CUSTOMER_PHONE        			AS CUSTOMERPHONE, "
								+ " HDR.CUSTOMER_EMAIL        			AS CUSTOMEREMAIL, "
								+ " HDR.DISPATCHER_TRADENAME  			AS DISPATCHERTRADENAME, "
								+ " HDR.DISPATCHER_ADDRESS1   			AS DISPATCHERADDRESS1, "
								+ " HDR.DISPATCHER_ADDRESS2   			AS DISPATCHERADDRESS2, "
								+ " HDR.DISPATCHER_LOCATION   			AS DISPATCHERLOCATION, "
								+ " HDR.DISPATCHER_PINCODE    			AS DISPATCHERPINCODE, "
								+ " HDR.DISPATCHER_STATECODE  			AS DISPATCHERSTATECODE, "
								+ " HDR.SHIP_TO_GSTIN 		  			AS SHIPTOGSTIN, "
								+ " HDR.SHIP_TO_TRADENAME     			AS SHIPTOTRADENAME, "
								+ " HDR.SHIP_TO_LEGALNAME     			AS SHIPTOLEGALNAME, "
								+ " HDR.SHIP_TO_ADDRESS1      			AS SHIPTOADDRESS1, "
								+ " HDR.SHIP_TO_ADDRESS2      			AS SHIPTOADDRESS2, "
								+ " HDR.SHIP_TO_LOCATION      			AS SHIPTOLOCATION, "
								+ " HDR.SHIP_TO_PINCODE       			AS SHIPTOPINCODE, "
								+ " HDR.SHIP_TO_STATECODE     			AS SHIPTOSTATECODE, "
								+ " ITM.ITEM_SERIAL_NUMBER    			AS ITEMSERIALNUMBER, "
								+ " ITM.PRODUCT_SERIAL_NUMBER 			AS PRODUCTSERIALNUMBER, "
								+ " ITM.PRODUCT_DESCRIPTION   			AS PRODUCTDESCRIPTION, "
								+ " ITM.IS_SERVICE 			  			AS ISSERVICE, "
								+ " ITM.HSN 				  			AS HSN, "
								+ " ITM.BARCODE 			  			AS BARCODE, "
								+ " ITM.BATCH_NAME 			  			AS BATCHNAME, "
								+ " ITM.BATCH_EXPIRY_DATE     			AS BATCHEXPIRYDATE, "
								+ " ITM.WARRANTY_DATE 		  			AS WARRANTYDATE, "
								+ " ITM.ORDER_LINE_REFERENCE  			AS ORDERLINEREFERENCE, "
								+ " ITM.ATTRIBUTE_NAME        			AS ATTRIBUTENAME, "
								+ " ITM.ATTRIBUTE_VALUE       			AS ATTRIBUTEVALUE, "
								+ " ITM.ORIGIN_COUNTRY        			AS ORIGINCOUNTRY, "
								+ " ITM.UQC 				  			AS UQC, "
								+ " ITM.QUANTITY 			  			AS QUANTITY, "
								+ " ITM.FREE_QUANTITY 		  			AS FREEQUANTITY, "
								+ " ITM.UNIT_PRICE            			AS UNITPRICE, "
								+ " ITM.ITEM_AMOUNT           			AS ITEMAMOUNT, "
								+ " ITM.ITEM_DISCOUNT         			AS ITEMDISCOUNT, "
								+ " ITM.PRE_TAX_AMOUNT        			AS PRETAXAMOUNT, "
								+ " ITM.ITEM_ASSESSABLE_AMT   			AS ITEMASSESSABLEAMOUNT, "
								+ " ITM.IGST_RATE             			AS IGSTRATE, "
								+ " ITM.IGST_AMOUNT           			AS IGSTAMOUNT, "
								+ " ITM.CGST_RATE             			AS CGSTRATE, "
								+ " ITM.CGST_AMOUNT           			AS CGSTAMOUNT, "
								+ " ITM.SGST_RATE             			AS SGSTRATE, "
								+ " ITM.SGST_AMOUNT           			AS SGSTAMOUNT, "
								+ " ITM.CESS_ADVALOREM_RATE   			AS CESSADVALOREMRATE, "
								+ " ITM.CESS_ADVALOREM_AMOUNT 			AS CESSADVALOREMAMOUNT, "
								+ " ITM.CESS_SPECIFIC_AMOUNT  			AS CESSSPECIFICAMOUNT, "
								+ " ITM.STATE_CESS_ADVALOREM_RATE 		AS STATECESSADVALOREMRATE, "
								+ " ITM.STATE_CESS_ADVALOREM_AMOUNT 	AS STATECESSADVALOREMAMOUNT, "
								+ " ITM.STATE_CESS_SPECIFIC_AMOUNT 		AS STATECESSSPECIFICAMOUNT, "
								+ " ITM.ITEM_OTHER_CHARGES              AS ITEMOTHERCHARGES, "
								+ " ITM.TOTAL_ITEM_AMOUNT               AS TOTALITEMAMOUNT, "
								+ " HDR.INV_OTHER_CHARGES               AS INVOICEOTHERCHARGES, "
								+ " HDR.INV_ASSESSABLE_AMT              AS INVOICEASSESSABLEAMOUNT, "
								+ " HDR.INV_IGST_AMT                    AS INVOICEIGSTAMOUNT, "
								+ " HDR.INV_CGST_AMT                    AS INVOICECGSTAMOUNT, "
								+ " HDR.INV_SGST_AMT                    AS INVOICESGSTAMOUNT, "
								+ " HDR.INV_CESS_ADVALOREM_AMT          AS INVOICECESSADVALOREMAMOUNT, "
								+ " HDR.INV_CESS_SPECIFIC_AMT           AS INVOICECESSSPECIFICAMOUNT, "
								+ " HDR.INV_STATECESS_ADVALOREM_AMT     AS INVOICESTATECESSADVALOREMAMOUNT, "
								+ " HDR.INV_STATECESS_SPECIFIC_AMT      AS INVOICESTATECESSSPECIFICAMOUNT, "
								+ " HDR.DISCOUNT 					AS INVOICE_DISCOUNT, "
								+ " HDR.INV_VALUE     					AS INVOICEVALUE, "
								+ " HDR.ROUNDOFF      					AS ROUNDOFF, "
								+ " HDR.CURRENCY_CODE 					AS CURRENCYCODE, "
								+ " HDR.COUNTRY_CODE  					AS COUNTRYCODE, "
								+ " HDR.INVOICE_VALUE_FC 				AS INVOICEVALUEFC, "
								+ " HDR.PORT_CODE  					AS PORTCODE, "
								+ " HDR.SHIPPING_BILL_NUMBER 			AS SHIPPINGBILLNUMBER, "
								+ " HDR.SHIPPING_BILL_DATE   			AS SHIPPINGBILLDATE, "
								+ " HDR.INVOICE_REMARKS 	 			AS INVOICEREMARKS, "
								+ " HDR.INVOICE_PERIOD_START_DATE 		AS INVOICEPERIODSTARTDATE, "
								+ " HDR.INVOICE_PERIOD_END_DATE   		AS INVOICEPERIODENDDATE, "
								+ " ITM.PRECEEDING_INVOICE_NUMBER 		AS PRECEEDINGINVOICENUMBER, "
								+ " ITM.PRECEEDING_INVOICE_DATE   		AS PRECEEDINGINVOICEDATE, "
								+ " ITM.OTHER_REFERENCE           		AS OTHERREFERENCE, "
								+ " ITM.RECEIPT_ADVICE_REFERENCE  		AS RECEIPTADVICEREFERENCE, "
								+ " ITM.RECEIPT_ADVICE_DATE       		AS RECEIPTADVICEDATE, "
								+ " ITM.TENDER_REFERENCE   		  		AS TENDERREFERENCE, "
								+ " ITM.CONTRACT_REFERENCE 		  		AS CONTRACTREFERENCE, "
								+ " ITM.EXTERNAL_REFERENCE 		  		AS EXTERNALREFERENCE, "
								+ " ITM.PROJECT_REFERENCE  		  		AS PROJECTREFERENCE, "
								+ " ITM.CUSTOMER_PO_REFERENCE_NUMBER    AS CUSTOMERPOREFERENCENUMBER, "
								+ " ITM.CUSTOMER_PO_REFERENCE_DATE      AS CUSTOMERPOREFERENCEDATE, "
								+ " HDR.PAYEE_NAME 						AS PAYEENAME, "
								+ " HDR.MODE_OF_PAYMENT 				AS MODEOFPAYMENT, "
								+ " HDR.BRANCH_OR_IFSC_CODE 			AS BRANCHORIFSCCODE, "
								+ " HDR.PAYMENT_TERMS 					AS PAYMENTTERMS, "
								+ " HDR.PAYMENT_INSTRUCTION 			AS PAYMENTINSTRUCTION, "
								+ " HDR.CREDIT_TRANSFER 				AS CREDITTRANSFER, "
								+ " HDR.DIRECT_DEBIT   					AS DIRECTDEBIT, "
								+ " HDR.CREDIT_DAYS    					AS CREDITDAYS, "
								+ " HDR.PAID_AMOUNT    					AS PAIDAMOUNT, "
								+ " HDR.BALANCE_AMOUNT 					AS BALANCEAMOUNT, "
								+ " HDR.ACCOUNT_DETAIL 					AS ACCOUNTDETAIL, "
								+ " HDR.ECOM_GSTIN 						AS ECOMGSTIN, "
								+ " ITM.SUPPORTING_DOC_URL     			AS SUPPORTINGDOCURL, "
								+ " ITM.SUPPORTING_DOCUMENT    			AS SUPPORTINGDOCUMENT, "
								+ " ITM.ADDITIONAL_INFORMATION 			AS ADDITIONALINFORMATION, "
								+ " HDR.TRANSPORTER_ID         			AS TRANSPORTERID, "
								+ " HDR.TRANSPORTER_NAME 	   			AS TRANSPORTERNAME, "
								+ " HDR.TRANSPORT_MODE         			AS TRANSPORTMODE, "
								+ " HDR.TRANSPORT_DOCNO        			AS TRANSPORTDOCNO, "
								+ " HDR.TRANSPORT_DOCDATE 				AS TRANSPORTDOCDATE, "
								+ " HDR.DISTANCE  						 AS DISTANCE, "
								+ " HDR.VEHICLENO 							AS VEHICLENO, "
								+ " HDR.VEHICLE_TYPE 					AS VEHICLETYPE, "
								+ " HDR.SECTION7OFIGSTFLAG 				AS SECTION7OFIGSTFLAG, "
								+ " HDR.CLAIMREFUNDFLAG 				AS CLAIMREFUNDFLAG, "
								+ " HDR.EXPORT_DUTY 					AS EXPORTDUTY, "
								+ " HDR.CREATED_ON 					    AS IRN_GET_CALL_DATE_TIME, "
								+ " HDR.BATCH_ID                       AS BATCH_ID, "
								+ " HDR.ID       AS HEADER_ID, "
								+ " ITM.ID        AS ITEM_ID, "
								+ " HDR.IRP_NAME        AS IRP_NAME "
								+ " FROM  TBL_GETIRN_LIST LST INNER JOIN "
								+ " TBL_GETIRN_SEZWOP_HEADER HDR ON LST.BATCH_ID = HDR.BATCH_ID  "
								+ " AND LST.IRN=HDR.IRN  AND LST.IRN_STATUS=HDR.IRN_STATUS "
								+ " LEFT JOIN TBL_GETIRN_SEZWOP_ITEM ITM ON HDR.ID = ITM.HEADER_ID  "
								+ " WHERE " + condition
								+ " AND LST.IS_DELETE = FALSE  "
								+ " AND UPPER(LST.GET_DETAIL_IRN_STATUS) = 'SUCCESS' "
							    + " UNION ALL "
								+ " SELECT HDR.IRN_GENERATION_PERIOD 			AS IRN_GENERATION_PERIOD , "
								+ " HDR.IRN_STATUS 		  			AS IRN_STATUS, "
								+ " HDR.IRN 				  			AS IRN_NUMBER, "
								+ " HDR.IRN_DATE_TIME			  		AS IRN_DATE, "
								+ " HDR.ACK_NUM 			  			AS ACKNOWLEDGMENT_NUMBER, "
								+ " HDR.IRN_CANCEL_DATE_TIME      		AS IRN_CANCELLATION_DATE, "
								+ " HDR.CANCELLATION_REASON   			AS CANCELLATION_REASON, "
								+ " HDR.CANCELLATION_REMARKS  			AS CANCELLATION_REMARKS, "
								+ " HDR.EWAY_BILL_NUMBER			  	AS E_WAY_BILL_NUMBER, "
								+ " HDR.EWAY_BILL_DATE 			  	AS E_WAY_BILL_DATE, "
								+ " HDR.VALID_UPTO            			AS VALID_UPTO, "
								+ " HDR.TAX_SCHEME            			AS TAX_SCHEME, "
								+ " HDR.SUPPLY_TYPE 		  			AS SUPPLYTYPE, "
								+ " HDR.DOC_TYPE 			  			AS DOCUMENTTYPE, "
								+ " HDR.DOC_NUM  			  			AS DOCUMENTNUMBER, "
								+ " HDR.DOC_DATE 			  			AS DOCUMENTDATE, "
								+ " HDR.REVERSECHARGEFLAG     			AS REVERSECHARGEFLAG, "
								+ " HDR.SUPPLIER_GSTIN 		  			AS SUPPLIERGSTIN, "
								+ " HDR.SUPPLIER_TRADENAME    			AS SUPPLIERTRADENAME, "
								+ " HDR.SUPPLIER_LEGALNAME    			AS SUPPLIERLEGALNAME, "
								+ " HDR.SUPPLIER_ADDRESS1     			AS SUPPLIERADDRESS1, "
								+ " HDR.SUPPLIER_ADDRESS2     			AS SUPPLIERADDRESS2, "
								+ " HDR.SUPPLIER_LOCATION     			AS SUPPLIERLOCATION, "
								+ " HDR.SUPPLIER_PINCODE      			AS SUPPLIERPINCODE, "
								+ " HDR.SUPPLIER_STATECODE    			AS SUPPLIERSTATECODE, "
								+ " HDR.SUPPLIER_PHONE        			AS SUPPLIERPHONE, "
								+ " HDR.SUPPLIER_EMAIL        			AS SUPPLIEREMAIL, "
								+ " HDR.CUSTOMER_GSTIN           			AS CUSTOMERGSTIN, "
								+ " HDR.CUSTOMER_TRADENAME    			AS CUSTOMERTRADENAME, "
								+ " HDR.CUSTOMER_LEGALNAME    			AS CUSTOMERLEGALNAME, "
								+ " HDR.CUSTOMER_ADDRESS1     			AS CUSTOMERADDRESS1, "
								+ " HDR.CUSTOMER_ADDRESS2     			AS CUSTOMERADDRESS2, "
								+ " HDR.CUSTOMER_LOCATION     			AS CUSTOMERLOCATION, "
								+ " HDR.CUSTOMER_PINCODE      			AS CUSTOMERPINCODE, "
								+ " HDR.CUSTOMER_STATECODE    			AS CUSTOMERSTATECODE, "
								+ " HDR.BILLING_POS           			AS BILLINGPOS, "
								+ " HDR.CUSTOMER_PHONE        			AS CUSTOMERPHONE, "
								+ " HDR.CUSTOMER_EMAIL        			AS CUSTOMEREMAIL, "
								+ " HDR.DISPATCHER_TRADENAME  			AS DISPATCHERTRADENAME, "
								+ " HDR.DISPATCHER_ADDRESS1   			AS DISPATCHERADDRESS1, "
								+ " HDR.DISPATCHER_ADDRESS2   			AS DISPATCHERADDRESS2, "
								+ " HDR.DISPATCHER_LOCATION   			AS DISPATCHERLOCATION, "
								+ " HDR.DISPATCHER_PINCODE    			AS DISPATCHERPINCODE, "
								+ " HDR.DISPATCHER_STATECODE  			AS DISPATCHERSTATECODE, "
								+ " HDR.SHIP_TO_GSTIN 		  			AS SHIPTOGSTIN, "
								+ " HDR.SHIP_TO_TRADENAME     			AS SHIPTOTRADENAME, "
								+ " HDR.SHIP_TO_LEGALNAME     			AS SHIPTOLEGALNAME, "
								+ " HDR.SHIP_TO_ADDRESS1      			AS SHIPTOADDRESS1, "
								+ " HDR.SHIP_TO_ADDRESS2      			AS SHIPTOADDRESS2, "
								+ " HDR.SHIP_TO_LOCATION      			AS SHIPTOLOCATION, "
								+ " HDR.SHIP_TO_PINCODE       			AS SHIPTOPINCODE, "
								+ " HDR.SHIP_TO_STATECODE     			AS SHIPTOSTATECODE, "
								+ " ITM.ITEM_SERIAL_NUMBER    			AS ITEMSERIALNUMBER, "
								+ " ITM.PRODUCT_SERIAL_NUMBER 			AS PRODUCTSERIALNUMBER, "
								+ " ITM.PRODUCT_DESCRIPTION   			AS PRODUCTDESCRIPTION, "
								+ " ITM.IS_SERVICE 			  			AS ISSERVICE, "
								+ " ITM.HSN 				  			AS HSN, "
								+ " ITM.BARCODE 			  			AS BARCODE, "
								+ " ITM.BATCH_NAME 			  			AS BATCHNAME, "
								+ " ITM.BATCH_EXPIRY_DATE     			AS BATCHEXPIRYDATE, "
								+ " ITM.WARRANTY_DATE 		  			AS WARRANTYDATE, "
								+ " ITM.ORDER_LINE_REFERENCE  			AS ORDERLINEREFERENCE, "
								+ " ITM.ATTRIBUTE_NAME        			AS ATTRIBUTENAME, "
								+ " ITM.ATTRIBUTE_VALUE       			AS ATTRIBUTEVALUE, "
								+ " ITM.ORIGIN_COUNTRY        			AS ORIGINCOUNTRY, "
								+ " ITM.UQC 				  			AS UQC, "
								+ " ITM.QUANTITY 			  			AS QUANTITY, "
								+ " ITM.FREE_QUANTITY 		  			AS FREEQUANTITY, "
								+ " ITM.UNIT_PRICE            			AS UNITPRICE, "
								+ " ITM.ITEM_AMOUNT           			AS ITEMAMOUNT, "
								+ " ITM.ITEM_DISCOUNT         			AS ITEMDISCOUNT, "
								+ " ITM.PRE_TAX_AMOUNT        			AS PRETAXAMOUNT, "
								+ " ITM.ITEM_ASSESSABLE_AMT   			AS ITEMASSESSABLEAMOUNT, "
								+ " ITM.IGST_RATE             			AS IGSTRATE, "
								+ " ITM.IGST_AMOUNT           			AS IGSTAMOUNT, "
								+ " ITM.CGST_RATE             			AS CGSTRATE, "
								+ " ITM.CGST_AMOUNT           			AS CGSTAMOUNT, "
								+ " ITM.SGST_RATE             			AS SGSTRATE, "
								+ " ITM.SGST_AMOUNT           			AS SGSTAMOUNT, "
								+ " ITM.CESS_ADVALOREM_RATE   			AS CESSADVALOREMRATE, "
								+ " ITM.CESS_ADVALOREM_AMOUNT 			AS CESSADVALOREMAMOUNT, "
								+ " ITM.CESS_SPECIFIC_AMOUNT  			AS CESSSPECIFICAMOUNT, "
								+ " ITM.STATE_CESS_ADVALOREM_RATE 		AS STATECESSADVALOREMRATE, "
								+ " ITM.STATE_CESS_ADVALOREM_AMOUNT 	AS STATECESSADVALOREMAMOUNT, "
								+ " ITM.STATE_CESS_SPECIFIC_AMOUNT 		AS STATECESSSPECIFICAMOUNT, "
								+ " ITM.ITEM_OTHER_CHARGES              AS ITEMOTHERCHARGES, "
								+ " ITM.TOTAL_ITEM_AMOUNT               AS TOTALITEMAMOUNT, "
								+ " HDR.INV_OTHER_CHARGES               AS INVOICEOTHERCHARGES, "
								+ " HDR.INV_ASSESSABLE_AMT              AS INVOICEASSESSABLEAMOUNT, "
								+ " HDR.INV_IGST_AMT                    AS INVOICEIGSTAMOUNT, "
								+ " HDR.INV_CGST_AMT                    AS INVOICECGSTAMOUNT, "
								+ " HDR.INV_SGST_AMT                    AS INVOICESGSTAMOUNT, "
								+ " HDR.INV_CESS_ADVALOREM_AMT          AS INVOICECESSADVALOREMAMOUNT, "
								+ " HDR.INV_CESS_SPECIFIC_AMT           AS INVOICECESSSPECIFICAMOUNT, "
								+ " HDR.INV_STATECESS_ADVALOREM_AMT     AS INVOICESTATECESSADVALOREMAMOUNT, "
								+ " HDR.INV_STATECESS_SPECIFIC_AMT      AS INVOICESTATECESSSPECIFICAMOUNT, "
								+ " HDR.DISCOUNT 					AS INVOICE_DISCOUNT, "
								+ " HDR.INV_VALUE     					AS INVOICEVALUE, "
								+ " HDR.ROUNDOFF      					AS ROUNDOFF, "
								+ " HDR.CURRENCY_CODE 					AS CURRENCYCODE, "
								+ " HDR.COUNTRY_CODE  					AS COUNTRYCODE, "
								+ " HDR.INVOICE_VALUE_FC 				AS INVOICEVALUEFC, "
								+ " HDR.PORT_CODE  					AS PORTCODE, "
								+ " HDR.SHIPPING_BILL_NUMBER 			AS SHIPPINGBILLNUMBER, "
								+ " HDR.SHIPPING_BILL_DATE   			AS SHIPPINGBILLDATE, "
								+ " HDR.INVOICE_REMARKS 	 			AS INVOICEREMARKS, "
								+ " HDR.INVOICE_PERIOD_START_DATE 		AS INVOICEPERIODSTARTDATE, "
								+ " HDR.INVOICE_PERIOD_END_DATE   		AS INVOICEPERIODENDDATE, "
								+ " ITM.PRECEEDING_INVOICE_NUMBER 		AS PRECEEDINGINVOICENUMBER, "
								+ " ITM.PRECEEDING_INVOICE_DATE   		AS PRECEEDINGINVOICEDATE, "
								+ " ITM.OTHER_REFERENCE           		AS OTHERREFERENCE, "
								+ " ITM.RECEIPT_ADVICE_REFERENCE  		AS RECEIPTADVICEREFERENCE, "
								+ " ITM.RECEIPT_ADVICE_DATE       		AS RECEIPTADVICEDATE, "
								+ " ITM.TENDER_REFERENCE   		  		AS TENDERREFERENCE, "
								+ " ITM.CONTRACT_REFERENCE 		  		AS CONTRACTREFERENCE, "
								+ " ITM.EXTERNAL_REFERENCE 		  		AS EXTERNALREFERENCE, "
								+ " ITM.PROJECT_REFERENCE  		  		AS PROJECTREFERENCE, "
								+ " ITM.CUSTOMER_PO_REFERENCE_NUMBER    AS CUSTOMERPOREFERENCENUMBER, "
								+ " ITM.CUSTOMER_PO_REFERENCE_DATE      AS CUSTOMERPOREFERENCEDATE, "
								+ " HDR.PAYEE_NAME 						AS PAYEENAME, "
								+ " HDR.MODE_OF_PAYMENT 				AS MODEOFPAYMENT, "
								+ " HDR.BRANCH_OR_IFSC_CODE 			AS BRANCHORIFSCCODE, "
								+ " HDR.PAYMENT_TERMS 					AS PAYMENTTERMS, "
								+ " HDR.PAYMENT_INSTRUCTION 			AS PAYMENTINSTRUCTION, "
								+ " HDR.CREDIT_TRANSFER 				AS CREDITTRANSFER, "
								+ " HDR.DIRECT_DEBIT   					AS DIRECTDEBIT, "
								+ " HDR.CREDIT_DAYS    					AS CREDITDAYS, "
								+ " HDR.PAID_AMOUNT    					AS PAIDAMOUNT, "
								+ " HDR.BALANCE_AMOUNT 					AS BALANCEAMOUNT, "
								+ " HDR.ACCOUNT_DETAIL 					AS ACCOUNTDETAIL, "
								+ " HDR.ECOM_GSTIN 						AS ECOMGSTIN, "
								+ " ITM.SUPPORTING_DOC_URL     			AS SUPPORTINGDOCURL, "
								+ " ITM.SUPPORTING_DOCUMENT    			AS SUPPORTINGDOCUMENT, "
								+ " ITM.ADDITIONAL_INFORMATION 			AS ADDITIONALINFORMATION, "
								+ " HDR.TRANSPORTER_ID         			AS TRANSPORTERID, "
								+ " HDR.TRANSPORTER_NAME 	   			AS TRANSPORTERNAME, "
								+ " HDR.TRANSPORT_MODE         			AS TRANSPORTMODE, "
								+ " HDR.TRANSPORT_DOCNO        			AS TRANSPORTDOCNO, "
								+ " HDR.TRANSPORT_DOCDATE 				AS TRANSPORTDOCDATE, "
								+ " HDR.DISTANCE  						 AS DISTANCE, "
								+ " HDR.VEHICLENO 							AS VEHICLENO, "
								+ " HDR.VEHICLE_TYPE 					AS VEHICLETYPE, "
								+ " HDR.SECTION7OFIGSTFLAG 				AS SECTION7OFIGSTFLAG, "
								+ " HDR.CLAIMREFUNDFLAG 				AS CLAIMREFUNDFLAG, "
								+ " HDR.EXPORT_DUTY 					AS EXPORTDUTY, "
								+ " HDR.CREATED_ON 					    AS IRN_GET_CALL_DATE_TIME, "
								+ " HDR.BATCH_ID                       AS BATCH_ID, "
								+ " HDR.ID       AS HEADER_ID, "
								+ " ITM.ID        AS ITEM_ID, "
								+ " HDR.IRP_NAME        AS IRP_NAME "
								+ " FROM  TBL_GETIRN_LIST LST INNER JOIN "
								+ " TBL_GETIRN_DEXP_HEADER HDR ON LST.BATCH_ID = HDR.BATCH_ID  "
								+ " AND LST.IRN=HDR.IRN  AND LST.IRN_STATUS=HDR.IRN_STATUS "
								+ " LEFT JOIN TBL_GETIRN_DEXP_ITEM ITM ON HDR.ID = ITM.HEADER_ID  "
								+ " WHERE " + condition
								+ " AND LST.IS_DELETE = FALSE  "
								+ " AND UPPER(LST.GET_DETAIL_IRN_STATUS) = 'SUCCESS' "
							    + " UNION ALL "
								
								+ " SELECT HDR.IRN_GENERATION_PERIOD 			AS IRN_GENERATION_PERIOD , "
								+ " HDR.IRN_STATUS 		  			AS IRN_STATUS, "
								+ " HDR.IRN 				  			AS IRN_NUMBER, "
								+ " HDR.IRN_DATE_TIME			  		AS IRN_DATE, "
								+ " HDR.ACK_NUM 			  			AS ACKNOWLEDGMENT_NUMBER, "
								+ " HDR.IRN_CANCEL_DATE_TIME      		AS IRN_CANCELLATION_DATE, "
								+ " HDR.CANCELLATION_REASON   			AS CANCELLATION_REASON, "
								+ " HDR.CANCELLATION_REMARKS  			AS CANCELLATION_REMARKS, "
								+ " HDR.EWAY_BILL_NUMBER			  	AS E_WAY_BILL_NUMBER, "
								+ " HDR.EWAY_BILL_DATE 			  	AS E_WAY_BILL_DATE, "
								+ " HDR.VALID_UPTO            			AS VALID_UPTO, "
								+ " HDR.TAX_SCHEME            			AS TAX_SCHEME, "
								+ " HDR.SUPPLY_TYPE 		  			AS SUPPLYTYPE, "
								+ " HDR.DOC_TYPE 			  			AS DOCUMENTTYPE, "
								+ " HDR.DOC_NUM  			  			AS DOCUMENTNUMBER, "
								+ " HDR.DOC_DATE 			  			AS DOCUMENTDATE, "
								+ " HDR.REVERSECHARGEFLAG     			AS REVERSECHARGEFLAG, "
								+ " HDR.SUPPLIER_GSTIN 		  			AS SUPPLIERGSTIN, "
								+ " HDR.SUPPLIER_TRADENAME    			AS SUPPLIERTRADENAME, "
								+ " HDR.SUPPLIER_LEGALNAME    			AS SUPPLIERLEGALNAME, "
								+ " HDR.SUPPLIER_ADDRESS1     			AS SUPPLIERADDRESS1, "
								+ " HDR.SUPPLIER_ADDRESS2     			AS SUPPLIERADDRESS2, "
								+ " HDR.SUPPLIER_LOCATION     			AS SUPPLIERLOCATION, "
								+ " HDR.SUPPLIER_PINCODE      			AS SUPPLIERPINCODE, "
								+ " HDR.SUPPLIER_STATECODE    			AS SUPPLIERSTATECODE, "
								+ " HDR.SUPPLIER_PHONE        			AS SUPPLIERPHONE, "
								+ " HDR.SUPPLIER_EMAIL        			AS SUPPLIEREMAIL, "
								+ " HDR.CUSTOMER_GSTIN           			AS CUSTOMERGSTIN, "
								+ " HDR.CUSTOMER_TRADENAME    			AS CUSTOMERTRADENAME, "
								+ " HDR.CUSTOMER_LEGALNAME    			AS CUSTOMERLEGALNAME, "
								+ " HDR.CUSTOMER_ADDRESS1     			AS CUSTOMERADDRESS1, "
								+ " HDR.CUSTOMER_ADDRESS2     			AS CUSTOMERADDRESS2, "
								+ " HDR.CUSTOMER_LOCATION     			AS CUSTOMERLOCATION, "
								+ " HDR.CUSTOMER_PINCODE      			AS CUSTOMERPINCODE, "
								+ " HDR.CUSTOMER_STATECODE    			AS CUSTOMERSTATECODE, "
								+ " HDR.BILLING_POS           			AS BILLINGPOS, "
								+ " HDR.CUSTOMER_PHONE        			AS CUSTOMERPHONE, "
								+ " HDR.CUSTOMER_EMAIL        			AS CUSTOMEREMAIL, "
								+ " HDR.DISPATCHER_TRADENAME  			AS DISPATCHERTRADENAME, "
								+ " HDR.DISPATCHER_ADDRESS1   			AS DISPATCHERADDRESS1, "
								+ " HDR.DISPATCHER_ADDRESS2   			AS DISPATCHERADDRESS2, "
								+ " HDR.DISPATCHER_LOCATION   			AS DISPATCHERLOCATION, "
								+ " HDR.DISPATCHER_PINCODE    			AS DISPATCHERPINCODE, "
								+ " HDR.DISPATCHER_STATECODE  			AS DISPATCHERSTATECODE, "
								+ " HDR.SHIP_TO_GSTIN 		  			AS SHIPTOGSTIN, "
								+ " HDR.SHIP_TO_TRADENAME     			AS SHIPTOTRADENAME, "
								+ " HDR.SHIP_TO_LEGALNAME     			AS SHIPTOLEGALNAME, "
								+ " HDR.SHIP_TO_ADDRESS1      			AS SHIPTOADDRESS1, "
								+ " HDR.SHIP_TO_ADDRESS2      			AS SHIPTOADDRESS2, "
								+ " HDR.SHIP_TO_LOCATION      			AS SHIPTOLOCATION, "
								+ " HDR.SHIP_TO_PINCODE       			AS SHIPTOPINCODE, "
								+ " HDR.SHIP_TO_STATECODE     			AS SHIPTOSTATECODE, "
								+ " ITM.ITEM_SERIAL_NUMBER    			AS ITEMSERIALNUMBER, "
								+ " ITM.PRODUCT_SERIAL_NUMBER 			AS PRODUCTSERIALNUMBER, "
								+ " ITM.PRODUCT_DESCRIPTION   			AS PRODUCTDESCRIPTION, "
								+ " ITM.IS_SERVICE 			  			AS ISSERVICE, "
								+ " ITM.HSN 				  			AS HSN, "
								+ " ITM.BARCODE 			  			AS BARCODE, "
								+ " ITM.BATCH_NAME 			  			AS BATCHNAME, "
								+ " ITM.BATCH_EXPIRY_DATE     			AS BATCHEXPIRYDATE, "
								+ " ITM.WARRANTY_DATE 		  			AS WARRANTYDATE, "
								+ " ITM.ORDER_LINE_REFERENCE  			AS ORDERLINEREFERENCE, "
								+ " ITM.ATTRIBUTE_NAME        			AS ATTRIBUTENAME, "
								+ " ITM.ATTRIBUTE_VALUE       			AS ATTRIBUTEVALUE, "
								+ " ITM.ORIGIN_COUNTRY        			AS ORIGINCOUNTRY, "
								+ " ITM.UQC 				  			AS UQC, "
								+ " ITM.QUANTITY 			  			AS QUANTITY, "
								+ " ITM.FREE_QUANTITY 		  			AS FREEQUANTITY, "
								+ " ITM.UNIT_PRICE            			AS UNITPRICE, "
								+ " ITM.ITEM_AMOUNT           			AS ITEMAMOUNT, "
								+ " ITM.ITEM_DISCOUNT         			AS ITEMDISCOUNT, "
								+ " ITM.PRE_TAX_AMOUNT        			AS PRETAXAMOUNT, "
								+ " ITM.ITEM_ASSESSABLE_AMT   			AS ITEMASSESSABLEAMOUNT, "
								+ " ITM.IGST_RATE             			AS IGSTRATE, "
								+ " ITM.IGST_AMOUNT           			AS IGSTAMOUNT, "
								+ " ITM.CGST_RATE             			AS CGSTRATE, "
								+ " ITM.CGST_AMOUNT           			AS CGSTAMOUNT, "
								+ " ITM.SGST_RATE             			AS SGSTRATE, "
								+ " ITM.SGST_AMOUNT           			AS SGSTAMOUNT, "
								+ " ITM.CESS_ADVALOREM_RATE   			AS CESSADVALOREMRATE, "
								+ " ITM.CESS_ADVALOREM_AMOUNT 			AS CESSADVALOREMAMOUNT, "
								+ " ITM.CESS_SPECIFIC_AMOUNT  			AS CESSSPECIFICAMOUNT, "
								+ " ITM.STATE_CESS_ADVALOREM_RATE 		AS STATECESSADVALOREMRATE, "
								+ " ITM.STATE_CESS_ADVALOREM_AMOUNT 	AS STATECESSADVALOREMAMOUNT, "
								+ " ITM.STATE_CESS_SPECIFIC_AMOUNT 		AS STATECESSSPECIFICAMOUNT, "
								+ " ITM.ITEM_OTHER_CHARGES              AS ITEMOTHERCHARGES, "
								+ " ITM.TOTAL_ITEM_AMOUNT               AS TOTALITEMAMOUNT, "
								+ " HDR.INV_OTHER_CHARGES               AS INVOICEOTHERCHARGES, "
								+ " HDR.INV_ASSESSABLE_AMT              AS INVOICEASSESSABLEAMOUNT, "
								+ " HDR.INV_IGST_AMT                    AS INVOICEIGSTAMOUNT, "
								+ " HDR.INV_CGST_AMT                    AS INVOICECGSTAMOUNT, "
								+ " HDR.INV_SGST_AMT                    AS INVOICESGSTAMOUNT, "
								+ " HDR.INV_CESS_ADVALOREM_AMT          AS INVOICECESSADVALOREMAMOUNT, "
								+ " HDR.INV_CESS_SPECIFIC_AMT           AS INVOICECESSSPECIFICAMOUNT, "
								+ " HDR.INV_STATECESS_ADVALOREM_AMT     AS INVOICESTATECESSADVALOREMAMOUNT, "
								+ " HDR.INV_STATECESS_SPECIFIC_AMT      AS INVOICESTATECESSSPECIFICAMOUNT, "
								+ " HDR.DISCOUNT 					AS INVOICE_DISCOUNT, "
								+ " HDR.INV_VALUE     					AS INVOICEVALUE, "
								+ " HDR.ROUNDOFF      					AS ROUNDOFF, "
								+ " HDR.CURRENCY_CODE 					AS CURRENCYCODE, "
								+ " HDR.COUNTRY_CODE  					AS COUNTRYCODE, "
								+ " HDR.INVOICE_VALUE_FC 				AS INVOICEVALUEFC, "
								+ " HDR.PORT_CODE  					AS PORTCODE, "
								+ " HDR.SHIPPING_BILL_NUMBER 			AS SHIPPINGBILLNUMBER, "
								+ " HDR.SHIPPING_BILL_DATE   			AS SHIPPINGBILLDATE, "
								+ " HDR.INVOICE_REMARKS 	 			AS INVOICEREMARKS, "
								+ " HDR.INVOICE_PERIOD_START_DATE 		AS INVOICEPERIODSTARTDATE, "
								+ " HDR.INVOICE_PERIOD_END_DATE   		AS INVOICEPERIODENDDATE, "
								+ " ITM.PRECEEDING_INVOICE_NUMBER 		AS PRECEEDINGINVOICENUMBER, "
								+ " ITM.PRECEEDING_INVOICE_DATE   		AS PRECEEDINGINVOICEDATE, "
								+ " ITM.OTHER_REFERENCE           		AS OTHERREFERENCE, "
								+ " ITM.RECEIPT_ADVICE_REFERENCE  		AS RECEIPTADVICEREFERENCE, "
								+ " ITM.RECEIPT_ADVICE_DATE       		AS RECEIPTADVICEDATE, "
								+ " ITM.TENDER_REFERENCE   		  		AS TENDERREFERENCE, "
								+ " ITM.CONTRACT_REFERENCE 		  		AS CONTRACTREFERENCE, "
								+ " ITM.EXTERNAL_REFERENCE 		  		AS EXTERNALREFERENCE, "
								+ " ITM.PROJECT_REFERENCE  		  		AS PROJECTREFERENCE, "
								+ " ITM.CUSTOMER_PO_REFERENCE_NUMBER    AS CUSTOMERPOREFERENCENUMBER, "
								+ " ITM.CUSTOMER_PO_REFERENCE_DATE      AS CUSTOMERPOREFERENCEDATE, "
								+ " HDR.PAYEE_NAME 						AS PAYEENAME, "
								+ " HDR.MODE_OF_PAYMENT 				AS MODEOFPAYMENT, "
								+ " HDR.BRANCH_OR_IFSC_CODE 			AS BRANCHORIFSCCODE, "
								+ " HDR.PAYMENT_TERMS 					AS PAYMENTTERMS, "
								+ " HDR.PAYMENT_INSTRUCTION 			AS PAYMENTINSTRUCTION, "
								+ " HDR.CREDIT_TRANSFER 				AS CREDITTRANSFER, "
								+ " HDR.DIRECT_DEBIT   					AS DIRECTDEBIT, "
								+ " HDR.CREDIT_DAYS    					AS CREDITDAYS, "
								+ " HDR.PAID_AMOUNT    					AS PAIDAMOUNT, "
								+ " HDR.BALANCE_AMOUNT 					AS BALANCEAMOUNT, "
								+ " HDR.ACCOUNT_DETAIL 					AS ACCOUNTDETAIL, "
								+ " HDR.ECOM_GSTIN 						AS ECOMGSTIN, "
								+ " ITM.SUPPORTING_DOC_URL     			AS SUPPORTINGDOCURL, "
								+ " ITM.SUPPORTING_DOCUMENT    			AS SUPPORTINGDOCUMENT, "
								+ " ITM.ADDITIONAL_INFORMATION 			AS ADDITIONALINFORMATION, "
								+ " HDR.TRANSPORTER_ID         			AS TRANSPORTERID, "
								+ " HDR.TRANSPORTER_NAME 	   			AS TRANSPORTERNAME, "
								+ " HDR.TRANSPORT_MODE         			AS TRANSPORTMODE, "
								+ " HDR.TRANSPORT_DOCNO        			AS TRANSPORTDOCNO, "
								+ " HDR.TRANSPORT_DOCDATE 				AS TRANSPORTDOCDATE, "
								+ " HDR.DISTANCE  						 AS DISTANCE, "
								+ " HDR.VEHICLENO 							AS VEHICLENO, "
								+ " HDR.VEHICLE_TYPE 					AS VEHICLETYPE, "
								+ " HDR.SECTION7OFIGSTFLAG 				AS SECTION7OFIGSTFLAG, "
								+ " HDR.CLAIMREFUNDFLAG 				AS CLAIMREFUNDFLAG, "
								+ " HDR.EXPORT_DUTY 					AS EXPORTDUTY, "
								+ " HDR.CREATED_ON 					    AS IRN_GET_CALL_DATE_TIME, "
								+ " HDR.BATCH_ID                       AS BATCH_ID, "
								+ " HDR.ID       AS HEADER_ID, "
								+ " ITM.ID        AS ITEM_ID, "
								+ " HDR.IRP_NAME        AS IRP_NAME "
								+ " FROM  TBL_GETIRN_LIST LST INNER JOIN "
								+ " TBL_GETIRN_EXPWP_HEADER HDR ON LST.BATCH_ID = HDR.BATCH_ID  "
								+ " AND LST.IRN=HDR.IRN  AND LST.IRN_STATUS=HDR.IRN_STATUS "
								+ " LEFT JOIN TBL_GETIRN_EXPWP_ITEM ITM ON HDR.ID = ITM.HEADER_ID  "
								+ " WHERE " + condition
								+ " AND LST.IS_DELETE = FALSE  "
								+ " AND UPPER(LST.GET_DETAIL_IRN_STATUS) = 'SUCCESS' "
							    + " UNION ALL "
								
								+ " SELECT HDR.IRN_GENERATION_PERIOD 			AS IRN_GENERATION_PERIOD , "
								+ " HDR.IRN_STATUS 		  			AS IRN_STATUS, "
								+ " HDR.IRN 				  			AS IRN_NUMBER, "
								+ " HDR.IRN_DATE_TIME			  		AS IRN_DATE, "
								+ " HDR.ACK_NUM 			  			AS ACKNOWLEDGMENT_NUMBER, "
								+ " HDR.IRN_CANCEL_DATE_TIME      		AS IRN_CANCELLATION_DATE, "
								+ " HDR.CANCELLATION_REASON   			AS CANCELLATION_REASON, "
								+ " HDR.CANCELLATION_REMARKS  			AS CANCELLATION_REMARKS, "
								+ " HDR.EWAY_BILL_NUMBER			  	AS E_WAY_BILL_NUMBER, "
								+ " HDR.EWAY_BILL_DATE 			  	AS E_WAY_BILL_DATE, "
								+ " HDR.VALID_UPTO            			AS VALID_UPTO, "
								+ " HDR.TAX_SCHEME            			AS TAX_SCHEME, "
								+ " HDR.SUPPLY_TYPE 		  			AS SUPPLYTYPE, "
								+ " HDR.DOC_TYPE 			  			AS DOCUMENTTYPE, "
								+ " HDR.DOC_NUM  			  			AS DOCUMENTNUMBER, "
								+ " HDR.DOC_DATE 			  			AS DOCUMENTDATE, "
								+ " HDR.REVERSECHARGEFLAG     			AS REVERSECHARGEFLAG, "
								+ " HDR.SUPPLIER_GSTIN 		  			AS SUPPLIERGSTIN, "
								+ " HDR.SUPPLIER_TRADENAME    			AS SUPPLIERTRADENAME, "
								+ " HDR.SUPPLIER_LEGALNAME    			AS SUPPLIERLEGALNAME, "
								+ " HDR.SUPPLIER_ADDRESS1     			AS SUPPLIERADDRESS1, "
								+ " HDR.SUPPLIER_ADDRESS2     			AS SUPPLIERADDRESS2, "
								+ " HDR.SUPPLIER_LOCATION     			AS SUPPLIERLOCATION, "
								+ " HDR.SUPPLIER_PINCODE      			AS SUPPLIERPINCODE, "
								+ " HDR.SUPPLIER_STATECODE    			AS SUPPLIERSTATECODE, "
								+ " HDR.SUPPLIER_PHONE        			AS SUPPLIERPHONE, "
								+ " HDR.SUPPLIER_EMAIL        			AS SUPPLIEREMAIL, "
								+ " HDR.CUSTOMER_GSTIN           			AS CUSTOMERGSTIN, "
								+ " HDR.CUSTOMER_TRADENAME    			AS CUSTOMERTRADENAME, "
								+ " HDR.CUSTOMER_LEGALNAME    			AS CUSTOMERLEGALNAME, "
								+ " HDR.CUSTOMER_ADDRESS1     			AS CUSTOMERADDRESS1, "
								+ " HDR.CUSTOMER_ADDRESS2     			AS CUSTOMERADDRESS2, "
								+ " HDR.CUSTOMER_LOCATION     			AS CUSTOMERLOCATION, "
								+ " HDR.CUSTOMER_PINCODE      			AS CUSTOMERPINCODE, "
								+ " HDR.CUSTOMER_STATECODE    			AS CUSTOMERSTATECODE, "
								+ " HDR.BILLING_POS           			AS BILLINGPOS, "
								+ " HDR.CUSTOMER_PHONE        			AS CUSTOMERPHONE, "
								+ " HDR.CUSTOMER_EMAIL        			AS CUSTOMEREMAIL, "
								+ " HDR.DISPATCHER_TRADENAME  			AS DISPATCHERTRADENAME, "
								+ " HDR.DISPATCHER_ADDRESS1   			AS DISPATCHERADDRESS1, "
								+ " HDR.DISPATCHER_ADDRESS2   			AS DISPATCHERADDRESS2, "
								+ " HDR.DISPATCHER_LOCATION   			AS DISPATCHERLOCATION, "
								+ " HDR.DISPATCHER_PINCODE    			AS DISPATCHERPINCODE, "
								+ " HDR.DISPATCHER_STATECODE  			AS DISPATCHERSTATECODE, "
								+ " HDR.SHIP_TO_GSTIN 		  			AS SHIPTOGSTIN, "
								+ " HDR.SHIP_TO_TRADENAME     			AS SHIPTOTRADENAME, "
								+ " HDR.SHIP_TO_LEGALNAME     			AS SHIPTOLEGALNAME, "
								+ " HDR.SHIP_TO_ADDRESS1      			AS SHIPTOADDRESS1, "
								+ " HDR.SHIP_TO_ADDRESS2      			AS SHIPTOADDRESS2, "
								+ " HDR.SHIP_TO_LOCATION      			AS SHIPTOLOCATION, "
								+ " HDR.SHIP_TO_PINCODE       			AS SHIPTOPINCODE, "
								+ " HDR.SHIP_TO_STATECODE     			AS SHIPTOSTATECODE, "
								+ " ITM.ITEM_SERIAL_NUMBER    			AS ITEMSERIALNUMBER, "
								+ " ITM.PRODUCT_SERIAL_NUMBER 			AS PRODUCTSERIALNUMBER, "
								+ " ITM.PRODUCT_DESCRIPTION   			AS PRODUCTDESCRIPTION, "
								+ " ITM.IS_SERVICE 			  			AS ISSERVICE, "
								+ " ITM.HSN 				  			AS HSN, "
								+ " ITM.BARCODE 			  			AS BARCODE, "
								+ " ITM.BATCH_NAME 			  			AS BATCHNAME, "
								+ " ITM.BATCH_EXPIRY_DATE     			AS BATCHEXPIRYDATE, "
								+ " ITM.WARRANTY_DATE 		  			AS WARRANTYDATE, "
								+ " ITM.ORDER_LINE_REFERENCE  			AS ORDERLINEREFERENCE, "
								+ " ITM.ATTRIBUTE_NAME        			AS ATTRIBUTENAME, "
								+ " ITM.ATTRIBUTE_VALUE       			AS ATTRIBUTEVALUE, "
								+ " ITM.ORIGIN_COUNTRY        			AS ORIGINCOUNTRY, "
								+ " ITM.UQC 				  			AS UQC, "
								+ " ITM.QUANTITY 			  			AS QUANTITY, "
								+ " ITM.FREE_QUANTITY 		  			AS FREEQUANTITY, "
								+ " ITM.UNIT_PRICE            			AS UNITPRICE, "
								+ " ITM.ITEM_AMOUNT           			AS ITEMAMOUNT, "
								+ " ITM.ITEM_DISCOUNT         			AS ITEMDISCOUNT, "
								+ " ITM.PRE_TAX_AMOUNT        			AS PRETAXAMOUNT, "
								+ " ITM.ITEM_ASSESSABLE_AMT   			AS ITEMASSESSABLEAMOUNT, "
								+ " ITM.IGST_RATE             			AS IGSTRATE, "
								+ " ITM.IGST_AMOUNT           			AS IGSTAMOUNT, "
								+ " ITM.CGST_RATE             			AS CGSTRATE, "
								+ " ITM.CGST_AMOUNT           			AS CGSTAMOUNT, "
								+ " ITM.SGST_RATE             			AS SGSTRATE, "
								+ " ITM.SGST_AMOUNT           			AS SGSTAMOUNT, "
								+ " ITM.CESS_ADVALOREM_RATE   			AS CESSADVALOREMRATE, "
								+ " ITM.CESS_ADVALOREM_AMOUNT 			AS CESSADVALOREMAMOUNT, "
								+ " ITM.CESS_SPECIFIC_AMOUNT  			AS CESSSPECIFICAMOUNT, "
								+ " ITM.STATE_CESS_ADVALOREM_RATE 		AS STATECESSADVALOREMRATE, "
								+ " ITM.STATE_CESS_ADVALOREM_AMOUNT 	AS STATECESSADVALOREMAMOUNT, "
								+ " ITM.STATE_CESS_SPECIFIC_AMOUNT 		AS STATECESSSPECIFICAMOUNT, "
								+ " ITM.ITEM_OTHER_CHARGES              AS ITEMOTHERCHARGES, "
								+ " ITM.TOTAL_ITEM_AMOUNT               AS TOTALITEMAMOUNT, "
								+ " HDR.INV_OTHER_CHARGES               AS INVOICEOTHERCHARGES, "
								+ " HDR.INV_ASSESSABLE_AMT              AS INVOICEASSESSABLEAMOUNT, "
								+ " HDR.INV_IGST_AMT                    AS INVOICEIGSTAMOUNT, "
								+ " HDR.INV_CGST_AMT                    AS INVOICECGSTAMOUNT, "
								+ " HDR.INV_SGST_AMT                    AS INVOICESGSTAMOUNT, "
								+ " HDR.INV_CESS_ADVALOREM_AMT          AS INVOICECESSADVALOREMAMOUNT, "
								+ " HDR.INV_CESS_SPECIFIC_AMT           AS INVOICECESSSPECIFICAMOUNT, "
								+ " HDR.INV_STATECESS_ADVALOREM_AMT     AS INVOICESTATECESSADVALOREMAMOUNT, "
								+ " HDR.INV_STATECESS_SPECIFIC_AMT      AS INVOICESTATECESSSPECIFICAMOUNT, "
								+ " HDR.DISCOUNT 					AS INVOICE_DISCOUNT, "
								+ " HDR.INV_VALUE     					AS INVOICEVALUE, "
								+ " HDR.ROUNDOFF      					AS ROUNDOFF, "
								+ " HDR.CURRENCY_CODE 					AS CURRENCYCODE, "
								+ " HDR.COUNTRY_CODE  					AS COUNTRYCODE, "
								+ " HDR.INVOICE_VALUE_FC 				AS INVOICEVALUEFC, "
								+ " HDR.PORT_CODE  					AS PORTCODE, "
								+ " HDR.SHIPPING_BILL_NUMBER 			AS SHIPPINGBILLNUMBER, "
								+ " HDR.SHIPPING_BILL_DATE   			AS SHIPPINGBILLDATE, "
								+ " HDR.INVOICE_REMARKS 	 			AS INVOICEREMARKS, "
								+ " HDR.INVOICE_PERIOD_START_DATE 		AS INVOICEPERIODSTARTDATE, "
								+ " HDR.INVOICE_PERIOD_END_DATE   		AS INVOICEPERIODENDDATE, "
								+ " ITM.PRECEEDING_INVOICE_NUMBER 		AS PRECEEDINGINVOICENUMBER, "
								+ " ITM.PRECEEDING_INVOICE_DATE   		AS PRECEEDINGINVOICEDATE, "
								+ " ITM.OTHER_REFERENCE           		AS OTHERREFERENCE, "
								+ " ITM.RECEIPT_ADVICE_REFERENCE  		AS RECEIPTADVICEREFERENCE, "
								+ " ITM.RECEIPT_ADVICE_DATE       		AS RECEIPTADVICEDATE, "
								+ " ITM.TENDER_REFERENCE   		  		AS TENDERREFERENCE, "
								+ " ITM.CONTRACT_REFERENCE 		  		AS CONTRACTREFERENCE, "
								+ " ITM.EXTERNAL_REFERENCE 		  		AS EXTERNALREFERENCE, "
								+ " ITM.PROJECT_REFERENCE  		  		AS PROJECTREFERENCE, "
								+ " ITM.CUSTOMER_PO_REFERENCE_NUMBER    AS CUSTOMERPOREFERENCENUMBER, "
								+ " ITM.CUSTOMER_PO_REFERENCE_DATE      AS CUSTOMERPOREFERENCEDATE, "
								+ " HDR.PAYEE_NAME 						AS PAYEENAME, "
								+ " HDR.MODE_OF_PAYMENT 				AS MODEOFPAYMENT, "
								+ " HDR.BRANCH_OR_IFSC_CODE 			AS BRANCHORIFSCCODE, "
								+ " HDR.PAYMENT_TERMS 					AS PAYMENTTERMS, "
								+ " HDR.PAYMENT_INSTRUCTION 			AS PAYMENTINSTRUCTION, "
								+ " HDR.CREDIT_TRANSFER 				AS CREDITTRANSFER, "
								+ " HDR.DIRECT_DEBIT   					AS DIRECTDEBIT, "
								+ " HDR.CREDIT_DAYS    					AS CREDITDAYS, "
								+ " HDR.PAID_AMOUNT    					AS PAIDAMOUNT, "
								+ " HDR.BALANCE_AMOUNT 					AS BALANCEAMOUNT, "
								+ " HDR.ACCOUNT_DETAIL 					AS ACCOUNTDETAIL, "
								+ " HDR.ECOM_GSTIN 						AS ECOMGSTIN, "
								+ " ITM.SUPPORTING_DOC_URL     			AS SUPPORTINGDOCURL, "
								+ " ITM.SUPPORTING_DOCUMENT    			AS SUPPORTINGDOCUMENT, "
								+ " ITM.ADDITIONAL_INFORMATION 			AS ADDITIONALINFORMATION, "
								+ " HDR.TRANSPORTER_ID         			AS TRANSPORTERID, "
								+ " HDR.TRANSPORTER_NAME 	   			AS TRANSPORTERNAME, "
								+ " HDR.TRANSPORT_MODE         			AS TRANSPORTMODE, "
								+ " HDR.TRANSPORT_DOCNO        			AS TRANSPORTDOCNO, "
								+ " HDR.TRANSPORT_DOCDATE 				AS TRANSPORTDOCDATE, "
								+ " HDR.DISTANCE  						 AS DISTANCE, "
								+ " HDR.VEHICLENO 							AS VEHICLENO, "
								+ " HDR.VEHICLE_TYPE 					AS VEHICLETYPE, "
								+ " HDR.SECTION7OFIGSTFLAG 				AS SECTION7OFIGSTFLAG, "
								+ " HDR.CLAIMREFUNDFLAG 				AS CLAIMREFUNDFLAG, "
								+ " HDR.EXPORT_DUTY 					AS EXPORTDUTY, "
								+ " HDR.CREATED_ON 					    AS IRN_GET_CALL_DATE_TIME, "
								+ " HDR.BATCH_ID                       AS BATCH_ID, "
								+ " HDR.ID       AS HEADER_ID, "
								+ " ITM.ID        AS ITEM_ID, "
								+ " HDR.IRP_NAME        AS IRP_NAME "
								+ " FROM  TBL_GETIRN_LIST LST INNER JOIN "
								+ " TBL_GETIRN_EXPWOP_HEADER HDR ON LST.BATCH_ID = HDR.BATCH_ID  "
								+ " AND LST.IRN=HDR.IRN  AND LST.IRN_STATUS=HDR.IRN_STATUS "
								+ " LEFT JOIN TBL_GETIRN_EXPWOP_ITEM ITM ON HDR.ID = ITM.HEADER_ID  "
								+ " WHERE " + condition
								+ " AND LST.IS_DELETE = FALSE  "
								+ " AND UPPER(LST.GET_DETAIL_IRN_STATUS) = 'SUCCESS' ");
		return query.toString();
	}

	private EinvoiceDetailedLineItemReportDto convert(Object[] arr) {
		if (LOGGER.isDebugEnabled()) {
			String str = "Converting generic object to"
					+ " EinvoiceDetailedLineItemReportDto object";
			LOGGER.debug(str);
		}

		EinvoiceDetailedLineItemReportDto obj = new EinvoiceDetailedLineItemReportDto();

		obj.setIRNGenerationPeriod((arr[0] != null) ? arr[0].toString() : null);
		if (arr[1] != null && ("ACT".equalsIgnoreCase(arr[1].toString()))
				|| ("CNL".equalsIgnoreCase(arr[1].toString()))) {
			if ("ACT".equalsIgnoreCase(arr[1].toString())) {
				obj.setIRNStatus("Active");
			} else {
				obj.setIRNStatus("Cancelled");
			}
		}
		obj.setIRNNumber((arr[2] != null) ? arr[2].toString() : null);
		obj.setIRNDate((arr[3] != null) ? arr[3].toString() : null);
		obj.setAcknowledgmentNumber((arr[4] != null) ? arr[4].toString() : null);
		obj.setIRNCancellationDate((arr[5] != null) ? removeMilliseconds(arr[5].toString()) : null);
		obj.setCancellationReason((arr[6] != null) ? arr[6].toString() : null);
		obj.setCancellationRemarks((arr[7] != null) ? arr[7].toString() : null);
		obj.setEWayBillNumber((arr[8] != null) ? arr[8].toString() : null);
		obj.setEWayBillDate((arr[9] != null) ? removeMilliseconds(arr[9].toString()) : null);
		obj.setValidUpto((arr[10] != null) ? removeMilliseconds(arr[10].toString()) : null);
		obj.setTaxScheme((arr[11] != null) ? arr[11].toString() : null);
		obj.setSupplyType((arr[12] != null) ? arr[12].toString() : null);
		obj.setDocumentType((arr[13] != null) ? arr[13].toString() : null);
		obj.setDocumentNumber((arr[14] != null) ? arr[14].toString() : null);
		obj.setDocumentDate((arr[15] != null) ? arr[15].toString() : null);
		obj.setReverseChargeFlag((arr[16] != null) ? arr[16].toString() : null);
		obj.setSupplierGSTIN((arr[17] != null) ? arr[17].toString() : null);
		obj.setSupplierTradeName((arr[18] != null) ? arr[18].toString() : null);
		obj.setSupplierLegalName((arr[19] != null) ? arr[19].toString() : null);
		obj.setSupplierAddress1((arr[20] != null) ? arr[20].toString() : null);
		obj.setSupplierAddress2((arr[21] != null) ? arr[21].toString() : null);
		obj.setSupplierLocation((arr[22] != null) ? arr[22].toString() : null);
		obj.setSupplierPincode((arr[23] != null) ? arr[23].toString() : null);
		obj.setSupplierStateCode((arr[24] != null) ? arr[24].toString() : null);
		obj.setSupplierPhone((arr[25] != null) ? arr[25].toString() : null);
		obj.setSupplierEmail((arr[26] != null) ? arr[26].toString() : null);
		obj.setCustomerGSTIN((arr[27] != null) ? arr[27].toString() : null);
		obj.setCustomerTradeName((arr[28] != null) ? arr[28].toString() : null);
		obj.setCustomerLegalName((arr[29] != null) ? arr[29].toString() : null);
		obj.setCustomerAddress1((arr[30] != null) ? arr[30].toString() : null);
		obj.setCustomerAddress2((arr[31] != null) ? arr[31].toString() : null);
		obj.setCustomerLocation((arr[32] != null) ? arr[32].toString() : null);
		obj.setCustomerPincode((arr[33] != null) ? arr[33].toString() : null);
		obj.setCustomerStateCode((arr[34] != null) ? arr[34].toString() : null);
		obj.setBillingPOS((arr[35] != null) ? arr[35].toString() : null);
		obj.setCustomerPhone((arr[36] != null) ? arr[36].toString() : null);
		obj.setCustomerEmail((arr[37] != null) ? arr[37].toString() : null);
		obj.setDispatcherTradeName((arr[38] != null) ? arr[38].toString() : null);
		obj.setDispatcherAddress1((arr[39] != null) ? arr[39].toString() : null);
		obj.setDispatcherAddress2((arr[40] != null) ? arr[40].toString() : null);
		obj.setDispatcherLocation((arr[41] != null) ? arr[41].toString() : null);
		obj.setDispatcherPincode((arr[42] != null) ? arr[42].toString() : null);
		obj.setDispatcherStateCode((arr[43] != null) ? arr[43].toString() : null);
		obj.setShipToGSTIN((arr[44] != null) ? arr[44].toString() : null);
		obj.setShipToTradeName((arr[45] != null) ? arr[45].toString() : null);
		obj.setShipToLegalName((arr[46] != null) ? arr[46].toString() : null);
		obj.setShipToAddress1((arr[47] != null) ? arr[47].toString() : null);
		obj.setShipToAddress2((arr[48] != null) ? arr[48].toString() : null);
		obj.setShipToLocation((arr[49] != null) ? arr[49].toString() : null);
		obj.setShipToPincode((arr[50] != null) ? arr[50].toString() : null);
		obj.setShipToStateCode((arr[51] != null) ? arr[51].toString() : null);
		obj.setItemSerialNumber((arr[52] != null) ? arr[52].toString() : null);
		obj.setProductSerialNumber((arr[53] != null) ? arr[53].toString() : null);
		obj.setProductDescription((arr[54] != null) ? arr[54].toString() : null);
		obj.setIsService((arr[55] != null) ? arr[55].toString() : null);
		obj.setHSN((arr[56] != null) ? arr[56].toString() : null);
		obj.setBarcode((arr[57] != null) ? arr[57].toString() : null);
		obj.setBatchName((arr[58] != null) ? arr[58].toString() : null);
		obj.setBatchExpiryDate((arr[59] != null) ? arr[59].toString() : null);
		obj.setWarrantyDate((arr[60] != null) ? arr[60].toString() : null);
		obj.setOrderLineReference((arr[61] != null) ? arr[61].toString() : null);
		obj.setAttributeName((arr[62] != null) ? arr[62].toString() : null);
		obj.setAttributeValue((arr[63] != null) ? arr[63].toString() : null);
		obj.setOriginCountry((arr[64] != null) ? arr[64].toString() : null);
		obj.setUQC((arr[65] != null) ? arr[65].toString() : null);
		obj.setQuantity((arr[66] != null) ? arr[66].toString() : null);
		obj.setFreeQuantity((arr[67] != null) ? arr[67].toString() : null);
		obj.setUnitPrice((arr[68] != null) ? arr[68].toString() : null);
		obj.setItemAmount((arr[69] != null) ? arr[69].toString() : null);
		obj.setItemDiscount((arr[70] != null) ? arr[70].toString() : null);
		obj.setPreTaxAmount((arr[71] != null) ? arr[71].toString() : null);
		obj.setItemAssessableAmount((arr[72] != null) ? arr[72].toString() : null);
		obj.setIGSTRate((arr[73] != null) ? RemoveDecimalPoint(arr[73].toString()) : null);
		obj.setIGSTAmount((arr[74] != null) ? arr[74].toString() : null);
		obj.setCGSTRate((arr[75] != null) ? RemoveDecimalPoint(arr[75].toString()) : null);
		obj.setCGSTAmount((arr[76] != null) ? arr[76].toString() : null);
		obj.setSGSTRate((arr[77] != null) ? RemoveDecimalPoint(arr[77].toString()) : null);
		obj.setSGSTAmount((arr[78] != null) ? arr[78].toString() : null);
		obj.setCessAdvaloremRate((arr[79] != null) ? RemoveDecimalPoint(arr[79].toString()) : null);
		obj.setCessAdvaloremAmount((arr[80] != null) ? arr[80].toString() : null);
		obj.setCessSpecificAmount((arr[81] != null) ? arr[81].toString() : null);
		obj.setStateCessAdvaloremRate((arr[82] != null) ? RemoveDecimalPoint(arr[82].toString()) : null);
		obj.setStateCessAdvaloremAmount((arr[83] != null) ? arr[83].toString() : null);
		obj.setStateCessSpecificAmount((arr[84] != null) ? arr[84].toString() : null);
		obj.setItemOtherCharges((arr[85] != null) ? arr[85].toString() : null);
		obj.setTotalItemAmount((arr[86] != null) ? arr[86].toString() : null);
		obj.setInvoiceOtherCharges((arr[87] != null) ? arr[87].toString() : null);
		obj.setInvoiceAssessableAmount((arr[88] != null) ? arr[88].toString() : null);
		obj.setInvoiceIGSTAmount((arr[89] != null) ? arr[89].toString() : null);
		obj.setInvoiceCGSTAmount((arr[90] != null) ? arr[90].toString() : null);
		obj.setInvoiceSGSTAmount((arr[91] != null) ? arr[91].toString() : null);
		obj.setInvoiceCessAdvaloremAmount((arr[92] != null) ? arr[92].toString() : null);
		obj.setInvoiceCessSpecificAmount((arr[93] != null) ? arr[93].toString() : null);
		obj.setInvoiceStateCessAdvaloremAmount((arr[94] != null) ? arr[94].toString() : null);
		obj.setInvoiceStateCessSpecificAmount((arr[95] != null) ? arr[95].toString() : null);
		obj.setInvoiceDiscount((arr[96] != null) ? arr[96].toString() : null);
		obj.setInvoiceValue((arr[97] != null) ? arr[97].toString() : null);
		obj.setRoundOff((arr[98] != null) ? arr[98].toString() : null);
		obj.setCurrencyCode((arr[99] != null) ? arr[99].toString() : null);
		obj.setCountryCode((arr[100] != null) ? arr[100].toString() : null);
		obj.setInvoiceValueFC((arr[101] != null) ? arr[101].toString() : null);
		obj.setPortCode((arr[102] != null) ? arr[102].toString() : null);
		obj.setShippingBillNumber((arr[103] != null) ? arr[103].toString() : null);
		obj.setShippingBillDate((arr[104] != null) ? arr[104].toString() : null);
		obj.setInvoiceRemarks((arr[105] != null) ? arr[105].toString() : null);
		obj.setInvoicePeriodStartDate((arr[106] != null) ? arr[106].toString() : null);
		obj.setInvoicePeriodEndDate((arr[107] != null) ? arr[107].toString() : null);
		obj.setPreceedingInvoiceNumber((arr[108] != null) ? arr[108].toString() : null);
		obj.setPreceedingInvoiceDate((arr[109] != null) ? arr[109].toString() : null);
		obj.setOtherReference((arr[110] != null) ? arr[110].toString() : null);
		obj.setReceiptAdviceReference((arr[111] != null) ? arr[111].toString() : null);
		obj.setReceiptAdviceDate((arr[112] != null) ? arr[112].toString() : null);
		obj.setTenderReference((arr[113] != null) ? arr[113].toString() : null);
		obj.setContractReference((arr[114] != null) ? arr[114].toString() : null);
		obj.setExternalReference((arr[115] != null) ? arr[115].toString() : null);
		obj.setProjectReference((arr[116] != null) ? arr[116].toString() : null);
		obj.setCustomerPOReferenceNumber((arr[117] != null) ? arr[117].toString() : null);
		obj.setCustomerPOReferenceDate((arr[118] != null) ? arr[118].toString() : null);
		obj.setPayeeName((arr[119] != null) ? arr[119].toString() : null);
		obj.setModeOfPayment((arr[120] != null) ? arr[120].toString() : null);
		obj.setBranchOrIFSCCode((arr[121] != null) ? arr[121].toString() : null);
		obj.setPaymentTerms((arr[122] != null) ? arr[122].toString() : null);
		obj.setPaymentInstruction((arr[123] != null) ? arr[123].toString() : null);
		obj.setCreditTransfer((arr[124] != null) ? arr[124].toString() : null);
		obj.setDirectDebit((arr[125] != null) ? arr[125].toString() : null);
		obj.setCreditDays((arr[126] != null) ? arr[126].toString() : null);
		obj.setPaidAmount((arr[127] != null) ? arr[127].toString() : null);
		obj.setBalanceAmount((arr[128] != null) ? arr[128].toString() : null);
		obj.setAccountDetail((arr[129] != null) ? arr[129].toString() : null);
		obj.setEcomGSTIN((arr[130] != null) ? arr[130].toString() : null);
		obj.setSupportingDocURL((arr[131] != null) ? arr[131].toString() : null);
		obj.setSupportingDocument((arr[132] != null) ? arr[132].toString() : null);
		obj.setAdditionalInformation((arr[133] != null) ? arr[133].toString() : null);
		obj.setTransporterID((arr[134] != null) ? arr[134].toString() : null);
		obj.setTransporterName((arr[135] != null) ? arr[135].toString() : null);
		obj.setTransportMode((arr[136] != null) ? arr[136].toString() : null);
		obj.setTransportDocNo((arr[137] != null) ? arr[137].toString() : null);
		obj.setTransportDocDate((arr[138] != null) ? arr[138].toString() : null);
		obj.setDistance((arr[139] != null) ? arr[139].toString() : null);
		obj.setVehicleNo((arr[140] != null) ? arr[140].toString() : null);
		obj.setVehicleType((arr[141] != null) ? arr[141].toString() : null);
		obj.setSection7OfIGSTFlag((arr[142] != null) ? arr[142].toString() : null);
		obj.setClaimRefundFlag((arr[143] != null) ? arr[143].toString() : null);
		obj.setExportDuty((arr[144] != null) ? arr[144].toString() : null);
		obj.setIRNGetCallDateTime((arr[145] != null) ? removeMilliseconds(arr[145].toString()) : null);
		obj.setIrpName((arr[149] != null) ? arr[149].toString() : null);
		return obj;
	}
	
	public String removeMilliseconds(String dateTimeString) {
        int dotIndex = dateTimeString.lastIndexOf('.');
        if (dotIndex != -1) {
            return dateTimeString.substring(0, dotIndex);
        } else {
            return dateTimeString;
        }
    }
	
	
	public String RemoveDecimalPoint(String num) {
		 String formattedValue = "";
		if (num != null) {
            double doubleValue = Double.parseDouble(num);
            DecimalFormat decimalFormat = new DecimalFormat("#.##");
            formattedValue = decimalFormat.format(doubleValue);
		}
		return formattedValue;
    }
}
