package com.ey.advisory.app.inward.einvoice;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class InwardEinvoiceDataDto {

	    private String irnGenerationPeriod;
	    private String irnStatus;
	    private String irnNumber;
	    private LocalDateTime irnDate;
	    private Long acknowledgmentNumber;
	    private LocalDateTime irnCancellationDate;
	    private String cancellationReason;
	    private String cancellationRemarks;
	    private Long eWayBillNumber;
	    private LocalDateTime eWayBillDate;
	    private LocalDateTime validUpto;
	    private String taxScheme;
	    private String supplyType;
	    private String documentType;
	    private String documentNumber;
	    private LocalDate documentDate;
	    private String reverseChargeFlag;
	    private String supplierGstin;
	    private String supplierTradeName;
	    private String supplierLegalName;
	    private String supplierAddress1;
	    private String supplierAddress2;
	    private String supplierLocation;
	    private String supplierPincode;
	    private String supplierStateCode;
	    private String supplierPhone;
	    private String supplierEmail;
	    private String customerGstin;
	    private String customerTradeName;
	    private String customerLegalName;
	    private String customerAddress1;
	    private String customerAddress2;
	    private String customerLocation;
	    private String customerPincode;
	    private String customerStateCode;
	    private String billingPos;
	    private String customerPhone;
	    private String customerEmail;
	    private String dispatcherTradeName;
	    private String dispatcherAddress1;
	    private String dispatcherAddress2;
	    private String dispatcherLocation;
	    private Integer dispatcherPincode;
	    private String dispatcherStateCode;
	    private String shipToGstin;
	    private String shipToTradeName;
	    private String shipToLegalName;
	    private String shipToAddress1;
	    private String shipToAddress2;
	    private String shipToLocation;
	    private Integer shipToPincode;
	    private String shipToStateCode;
	    private String itemSerialNumber;
	    private String productSerialNumber;
	    private String productDescription;
	    private String isService;
	    private String hsn;
	    private String barcode;
	    private String batchName;
	    private LocalDate batchExpiryDate;
	    private LocalDate warrantyDate;
	    private String orderLineReference;
	    private String attributeName;
	    private String attributeValue;
	    private String originCountry;
	    private String uqc;
	    private BigDecimal quantity;
	    private BigDecimal freeQuantity;
	    private BigDecimal unitPrice;
	    private BigDecimal itemAmount;
	    private BigDecimal itemDiscount;
	    private BigDecimal preTaxAmount;
	    private BigDecimal itemAssessableAmount;
	    private BigDecimal igstRate;
	    private BigDecimal igstAmount;
	    private BigDecimal cgstRate;
	    private BigDecimal cgstAmount;
	    private BigDecimal sgstRate;
	    private BigDecimal sgstAmount;
	    private BigDecimal cessAdValoremRate;
	    private BigDecimal cessAdValoremAmount;
	    private BigDecimal cessSpecificAmount;
	    private BigDecimal stateCessAdValoremRate;
	    private BigDecimal stateCessAdValoremAmount;
	    private BigDecimal stateCessSpecificAmount;
	    private BigDecimal itemOtherCharges;
	    private BigDecimal totalItemAmount;
	    private BigDecimal invoiceOtherCharges;
	    private BigDecimal invoiceAssessableAmount;
	    private BigDecimal invoiceIgstAmount;
	    private BigDecimal invoiceCgstAmount;
	    private BigDecimal invoiceSgstAmount;
	    private BigDecimal invoiceCessAdValoremAmount;
	    private BigDecimal invoiceCessSpecificAmount;
	    private BigDecimal invoiceStateCessAdValoremAmount;
	    private BigDecimal invoiceStateCessSpecificAmount;
	    private BigDecimal invoiceDiscount;
	    private BigDecimal invoiceValue;
	    private BigDecimal roundOff;
	    private String currencyCode;
	    private String countryCode;
	    private BigDecimal invoiceValueFc;
	    private String portCode;
	    private String shippingBillNumber;
	    private LocalDate shippingBillDate;
	    private String invoiceRemarks;
	    private LocalDate invoicePeriodStartDate;
	    private LocalDate invoicePeriodEndDate;
	    private String precedingInvoiceNumber;
	    private LocalDate precedingInvoiceDate;
	    private String otherReference;
	    private String receiptAdviceReference;
	    private LocalDate receiptAdviceDate;
	    private String tenderReference;
	    private String contractReference;
	    private String externalReference;
	    private String projectReference;
	    private String customerPoReferenceNumber;
	    private LocalDate customerPoReferenceDate;
	    private String payeeName;
	    private String modeOfPayment;
	    private String branchOrIfscCode;
	    private String paymentTerms;
	    private String paymentInstruction;
	    private String creditTransfer;
	    private String directDebit;
	    private Integer creditDays;
	    private BigDecimal paidAmount;
	    private BigDecimal balanceAmount;
	    private String accountDetail;
	    private String ecomGstin;
	    private String supportingDocUrl;
	    private String supportingDocument;
	    private String additionalInformation;
	    private String transporterId;
	    private String transporterName;
	    private String transportMode;
	    private String transportDocNo;
	    private LocalDate transportDocDate;
	    private Integer distance;
	    private String vehicleNo;
	    private String vehicleType;
	    private String section7OfIgstFlag;
	    private String claimRefundFlag;
	    private BigDecimal exportDuty;
	    private LocalDate irnGetCallDateTime;
	    private String sourceIrp;


}
