package com.ey.advisory.app.services.daos.get2a;

import java.util.List;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.Query;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import com.ey.advisory.app.docs.dto.GetAnx2DetailStatusReqDto;

@Component("GetGstr2aDetailStatusFetchDaoImpl")
public class GetGstr2aDetailStatusFetchDaoImpl
		implements GetGstr2aDetailStatusFetchDao {

	private static final Logger LOGGER = LoggerFactory
			.getLogger(GetGstr2aDetailStatusFetchDaoImpl.class);

	@PersistenceContext(unitName = "clientDataUnit")
	private EntityManager entityManager;

	@Override
	public List<Object[]> findDataByCriteria(
			GetAnx2DetailStatusReqDto criteria) {

		List<String> gstin = criteria.getGstin();
		String taxPeriod = criteria.getTaxPeriod();
		StringBuilder queryStr = createQueryString(gstin, taxPeriod);

		Query query = entityManager.createNativeQuery(queryStr.toString());
		if (CollectionUtils.isNotEmpty(gstin)) {
			query.setParameter("gstin", gstin);
		}

		if (StringUtils.isNotEmpty(taxPeriod)) {
			query.setParameter("taxPeriod", taxPeriod);
		}

		List<Object[]> itemsList = query.getResultList();
		return itemsList;
	}

	private StringBuilder createQueryString(List<String> gstin,
			String taxPeriod) {

		StringBuilder queryBuilder = new StringBuilder();

		if (StringUtils.isNotEmpty(taxPeriod)) {
			queryBuilder.append(" WHERE RETURN_PERIOD = :taxPeriod");
		}
		if (CollectionUtils.isNotEmpty(gstin)) {
			queryBuilder.append(" AND CUST_GSTIN IN (:gstin) ");
		}
		String condition = queryBuilder.toString();
		StringBuilder buffer = new StringBuilder();
		buffer.append(
				" SELECT CUST_GSTIN ,RETURN_PERIOD ,B2B_STATUS ,B2B_LAST_UPDATED ,B2BA_STATUS ,B2BA_LAST_UPDATED ,CDN_STATUS ,CDN_LAST_UPDATED ,CDNA_STATUS ,CDNA_LAST_UPDATED ,ISD_STATUS ,ISD_LAST_UPDATED ,ISDA_STATUS ,ISDA_LAST_UPDATED, IMPG_STATUS , IMPG_LAST_UPDATED,IMPGSEZ_STATUS ,IMPGSEZ_LAST_UPDATED,AMDHIST_STATUS ,AMDHIST_LAST_UPDATED FROM ( SELECT CUST_GSTIN ,RETURN_PERIOD ,CASE WHEN GET_TYPE='B2B' THEN STATUS END B2B_STATUS ,CASE WHEN GET_TYPE='B2B' THEN LAST_UPDATED END B2B_LAST_UPDATED ,'' AS B2BA_STATUS, '' AS B2BA_LAST_UPDATED , '' AS CDN_STATUS , '' AS CDN_LAST_UPDATED , '' AS CDNA_STATUS , '' AS CDNA_LAST_UPDATED , '' AS ISD_STATUS , '' AS ISD_LAST_UPDATED , '' AS ISDA_STATUS , '' AS ISDA_LAST_UPDATED, '' AS IMPG_STATUS , '' AS IMPG_LAST_UPDATED,'' AS IMPGSEZ_STATUS , '' AS IMPGSEZ_LAST_UPDATED, '' AS AMDHIST_STATUS , '' AS AMDHIST_LAST_UPDATED FROM ( SELECT BT.GSTIN AS CUST_GSTIN , BT.RETURN_PERIOD AS RETURN_PERIOD ,GET_TYPE ,STATUS ,MAX(BT.CREATED_ON) LAST_UPDATED FROM GETANX1_BATCH_TABLE BT WHERE BT.IS_DELETE=FALSE AND BT.API_SECTION='GSTR2A' AND BT.GET_TYPE IN ('B2B') GROUP BY BT.GSTIN,BT.RETURN_PERIOD,STATUS,GET_TYPE) ");
		if (!condition.equals("")) {
			buffer.append(condition);
		}
		buffer.append(
				" GROUP BY CUST_GSTIN,RETURN_PERIOD,STATUS,GET_TYPE,LAST_UPDATED UNION ALL SELECT CUST_GSTIN ,RETURN_PERIOD , '' AS B2B_STATUS , '' AS B2B_LAST_UPDATED , CASE WHEN GET_TYPE='B2BA' THEN STATUS END B2BA_STATUS , CASE WHEN GET_TYPE='B2BA' THEN LAST_UPDATED END B2BA_LAST_UPDATED , '' AS CDN_STATUS , '' AS CDN_LAST_UPDATED , '' AS CDNA_STATUS , '' AS CDNA_LAST_UPDATED , '' AS ISD_STATUS , '' AS ISD_LAST_UPDATED , '' AS ISDA_STATUS , '' AS ISDA_LAST_UPDATED, '' AS IMPG_STATUS , '' AS IMPG_LAST_UPDATED,'' AS IMPGSEZ_STATUS , '' AS IMPGSEZ_LAST_UPDATED, '' AS AMDHIST_STATUS , '' AS AMDHIST_LAST_UPDATED FROM ( SELECT BT.GSTIN AS CUST_GSTIN , BT.RETURN_PERIOD AS RETURN_PERIOD ,GET_TYPE ,STATUS ,MAX(BT.CREATED_ON) LAST_UPDATED FROM GETANX1_BATCH_TABLE BT WHERE BT.GET_TYPE IN ('B2BA') AND BT.IS_DELETE=FALSE AND BT.API_SECTION='GSTR2A' GROUP BY BT.GSTIN,BT.RETURN_PERIOD,STATUS,GET_TYPE) ");
		if (!condition.equals("")) {
			buffer.append(condition);
		}
		buffer.append(
				" GROUP BY CUST_GSTIN,RETURN_PERIOD,STATUS,GET_TYPE,LAST_UPDATED UNION ALL SELECT CUST_GSTIN ,RETURN_PERIOD , '' AS B2B_STATUS , '' AS B2B_LAST_UPDATED , '' AS B2BA_STATUS , '' AS B2BA_LAST_UPDATED , CASE WHEN GET_TYPE='CDN' THEN STATUS END CDN_STATUS , CASE WHEN GET_TYPE='CDN' THEN LAST_UPDATED END CDN_LAST_UPDATED , '' AS CDNA_STATUS , '' AS CDNA_LAST_UPDATED , '' AS ISD_STATUS , '' AS ISD_LAST_UPDATED , '' AS ISDA_STATUS , '' AS ISDA_LAST_UPDATED, '' AS IMPG_STATUS , '' AS IMPG_LAST_UPDATED,'' AS IMPGSEZ_STATUS , '' AS IMPGSEZ_LAST_UPDATED, '' AS AMDHIST_STATUS , '' AS AMDHIST_LAST_UPDATED FROM ( SELECT BT.GSTIN AS CUST_GSTIN , BT.RETURN_PERIOD AS RETURN_PERIOD , GET_TYPE , STATUS , MAX(BT.CREATED_ON) LAST_UPDATED FROM GETANX1_BATCH_TABLE BT WHERE BT.IS_DELETE=FALSE AND BT.API_SECTION='GSTR2A' AND BT.GET_TYPE IN ('CDN') GROUP BY BT.GSTIN,BT.RETURN_PERIOD,STATUS,GET_TYPE) ");
		if (!condition.equals("")) {
			buffer.append(condition);
		}
		buffer.append(
				" GROUP BY CUST_GSTIN,RETURN_PERIOD,STATUS,GET_TYPE,LAST_UPDATED UNION ALL SELECT CUST_GSTIN , RETURN_PERIOD , '' AS B2B_STATUS , '' AS B2B_LAST_UPDATED , '' AS B2BA_STATUS , '' AS B2BA_LAST_UPDATED , '' AS CDN_STATUS , '' AS CDN_LAST_UPDATED , CASE WHEN GET_TYPE='CDNA' THEN STATUS END CDNA_STATUS , CASE WHEN GET_TYPE='CDNA' THEN LAST_UPDATED END CDNA_LAST_UPDATED , '' AS ISD_STATUS , '' AS ISD_LAST_UPDATED , '' AS ISDA_STATUS , '' AS ISDA_LAST_UPDATED, '' AS IMPG_STATUS , '' AS IMPG_LAST_UPDATED,'' AS IMPGSEZ_STATUS , '' AS IMPGSEZ_LAST_UPDATED, '' AS AMDHIST_STATUS , '' AS AMDHIST_LAST_UPDATED FROM ( SELECT BT.GSTIN AS CUST_GSTIN , BT.RETURN_PERIOD AS RETURN_PERIOD ,GET_TYPE ,STATUS,MAX(BT.CREATED_ON) LAST_UPDATED FROM GETANX1_BATCH_TABLE BT WHERE BT.IS_DELETE=FALSE AND BT.API_SECTION='GSTR2A' AND BT.GET_TYPE IN ('CDNA') GROUP BY BT.GSTIN,BT.RETURN_PERIOD,STATUS,GET_TYPE) ");
		if (!condition.equals("")) {
			buffer.append(condition);
		}
		buffer.append(
				" GROUP BY CUST_GSTIN,RETURN_PERIOD,STATUS,GET_TYPE,LAST_UPDATED UNION ALL SELECT CUST_GSTIN ,RETURN_PERIOD , '' AS B2B_STATUS , '' AS B2B_LAST_UPDATED , '' AS B2BA_STATUS , '' AS B2BA_LAST_UPDATED , '' AS CDN_STATUS , '' AS CDN_LAST_UPDATED , '' AS CDNA_STATUS , '' AS CDNA_LAST_UPDATED , CASE WHEN GET_TYPE='ISD' THEN STATUS END ISD_STATUS , CASE WHEN GET_TYPE='ISD' THEN LAST_UPDATED END ISD_LAST_UPDATED , '' AS ISDA_STATUS , '' AS ISDA_LAST_UPDATED, '' AS IMPG_STATUS , '' AS IMPG_LAST_UPDATED,'' AS IMPGSEZ_STATUS , '' AS IMPGSEZ_LAST_UPDATED, '' AS AMDHIST_STATUS , '' AS AMDHIST_LAST_UPDATED FROM ( SELECT BT.GSTIN AS CUST_GSTIN , BT.RETURN_PERIOD AS RETURN_PERIOD ,GET_TYPE ,STATUS ,MAX(BT.CREATED_ON) LAST_UPDATED FROM GETANX1_BATCH_TABLE BT WHERE BT.IS_DELETE=FALSE AND BT.API_SECTION='GSTR2A' AND BT.GET_TYPE IN ('ISD') GROUP BY BT.GSTIN,BT.RETURN_PERIOD,STATUS,GET_TYPE) ");
		if (!condition.equals("")) {
			buffer.append(condition);
		}
		buffer.append(
				" GROUP BY CUST_GSTIN,RETURN_PERIOD,STATUS,GET_TYPE,LAST_UPDATED UNION ALL SELECT CUST_GSTIN ,RETURN_PERIOD , '' AS B2B_STATUS , '' AS B2B_LAST_UPDATED , '' AS B2BA_STATUS , '' AS B2BA_LAST_UPDATED , '' AS CDN_STATUS , '' AS CDN_LAST_UPDATED , '' AS CDNA_STATUS , '' AS CDNA_LAST_UPDATED , '' AS ISD_STATUS , '' AS ISD_LAST_UPDATED , CASE WHEN GET_TYPE='ISDA' THEN STATUS END ISDA_STATUS , CASE WHEN GET_TYPE='ISDA' THEN LAST_UPDATED END ISDA_LAST_UPDATED, '' AS IMPG_STATUS , '' AS IMPG_LAST_UPDATED,'' AS IMPGSEZ_STATUS , '' AS IMPGSEZ_LAST_UPDATED, '' AS AMDHIST_STATUS , '' AS AMDHIST_LAST_UPDATED FROM ( SELECT BT.GSTIN AS CUST_GSTIN , BT.RETURN_PERIOD AS RETURN_PERIOD ,GET_TYPE ,STATUS ,MAX(BT.CREATED_ON) LAST_UPDATED FROM GETANX1_BATCH_TABLE BT WHERE BT.IS_DELETE=FALSE AND BT.API_SECTION='GSTR2A' AND BT.GET_TYPE IN ('ISDA') GROUP BY BT.GSTIN,BT.RETURN_PERIOD,STATUS,GET_TYPE) ");
		if (!condition.equals("")) {
			buffer.append(condition);
		}
		buffer.append(
				" GROUP BY CUST_GSTIN,RETURN_PERIOD,STATUS,GET_TYPE,LAST_UPDATED UNION ALL SELECT CUST_GSTIN ,RETURN_PERIOD , '' AS B2B_STATUS , '' AS B2B_LAST_UPDATED , '' AS B2BA_STATUS , '' AS B2BA_LAST_UPDATED , '' AS CDN_STATUS , '' AS CDN_LAST_UPDATED , '' AS CDNA_STATUS , '' AS CDNA_LAST_UPDATED , '' AS ISD_STATUS , '' AS ISD_LAST_UPDATED , '' AS ISDA_STATUS , '' AS ISDA_LAST_UPDATED, CASE WHEN GET_TYPE='IMPG' THEN STATUS END IMPG_STATUS , CASE WHEN GET_TYPE='IMPG' THEN LAST_UPDATED END IMPG_LAST_UPDATED , '' AS IMPGSEZ_STATUS , '' AS IMPGSEZ_LAST_UPDATED, '' AS AMDHIST_STATUS , '' AS AMDHIST_LAST_UPDATED FROM ( SELECT BT.GSTIN AS CUST_GSTIN , BT.RETURN_PERIOD AS RETURN_PERIOD ,GET_TYPE ,STATUS , MAX(BT.CREATED_ON) LAST_UPDATED FROM GETANX1_BATCH_TABLE BT WHERE BT.IS_DELETE=FALSE AND BT.API_SECTION='GSTR2A' AND BT.GET_TYPE IN ('IMPG') GROUP BY BT.GSTIN,BT.RETURN_PERIOD,STATUS,GET_TYPE) ");
		if (!condition.equals("")) {
			buffer.append(condition);
		}
		buffer.append(
				" GROUP BY CUST_GSTIN,RETURN_PERIOD,STATUS,GET_TYPE,LAST_UPDATED UNION ALL SELECT CUST_GSTIN ,RETURN_PERIOD , '' AS B2B_STATUS , '' AS B2B_LAST_UPDATED , '' AS B2BA_STATUS , '' AS B2BA_LAST_UPDATED , '' AS CDN_STATUS , '' AS CDN_LAST_UPDATED , '' AS CDNA_STATUS , '' AS CDNA_LAST_UPDATED , '' AS ISD_STATUS , '' AS ISD_LAST_UPDATED , '' AS ISDA_STATUS , '' AS ISDA_LAST_UPDATED, '' AS IMPG_STATUS , '' AS IMPG_LAST_UPDATED, CASE WHEN GET_TYPE='IMPGSEZ' THEN STATUS END IMPGSEZ_STATUS , CASE WHEN GET_TYPE='IMPGSEZ' THEN LAST_UPDATED END IMPGSEZ_LAST_UPDATED , '' AS AMDHIST_STATUS , '' AS AMDHIST_LAST_UPDATED FROM ( SELECT BT.GSTIN AS CUST_GSTIN , BT.RETURN_PERIOD AS RETURN_PERIOD ,GET_TYPE ,STATUS , MAX(BT.CREATED_ON) LAST_UPDATED FROM GETANX1_BATCH_TABLE BT WHERE BT.IS_DELETE=FALSE AND BT.API_SECTION='GSTR2A' AND BT.GET_TYPE IN ('IMPGSEZ') GROUP BY BT.GSTIN,BT.RETURN_PERIOD,STATUS,GET_TYPE) ");
		if (!condition.equals("")) {
			buffer.append(condition);
		}
		buffer.append(
				" GROUP BY CUST_GSTIN,RETURN_PERIOD,STATUS,GET_TYPE,LAST_UPDATED UNION ALL SELECT CUST_GSTIN ,RETURN_PERIOD , '' AS B2B_STATUS , '' AS B2B_LAST_UPDATED , '' AS B2BA_STATUS , '' AS B2BA_LAST_UPDATED , '' AS CDN_STATUS , '' AS CDN_LAST_UPDATED , '' AS CDNA_STATUS , '' AS CDNA_LAST_UPDATED , '' AS ISD_STATUS , '' AS ISD_LAST_UPDATED , '' AS ISDA_STATUS , '' AS ISDA_LAST_UPDATED, '' AS IMPG_STATUS , '' AS IMPG_LAST_UPDATED, '' IMPGSEZ_STATUS , '' IMPGSEZ_LAST_UPDATED , CASE WHEN GET_TYPE='AMDHIST' THEN STATUS END AMDHIST_STATUS , CASE WHEN GET_TYPE='AMDHIST' THEN LAST_UPDATED END AMDHIST_LAST_UPDATED FROM ( SELECT BT.GSTIN AS CUST_GSTIN , BT.RETURN_PERIOD AS RETURN_PERIOD ,GET_TYPE ,STATUS , MAX(BT.CREATED_ON) LAST_UPDATED FROM GETANX1_BATCH_TABLE BT WHERE BT.IS_DELETE=FALSE AND BT.API_SECTION='GSTR2A' AND BT.GET_TYPE IN ('AMDHIST') GROUP BY BT.GSTIN,BT.RETURN_PERIOD,STATUS,GET_TYPE) ");
		if (!condition.equals("")) {
			buffer.append(condition);
		}
		buffer.append(
				" GROUP BY CUST_GSTIN,RETURN_PERIOD,STATUS,GET_TYPE,LAST_UPDATED)");

		return buffer;
	}

}
