package com.ey.advisory.app.gstr2bpr.reconresponse.upload;

import lombok.Data;

@Data
public class GSTR2bprAutoReconRespUploadDTO {

	private String suggestedResponse;
	private String userResponse;
	private String taxPeriodforGSTR3B;
	private String responseRemarks;
	private String matchingScoreOutof12;
	private String matchReason;
	private String mismatchReason;
	private String reportType;
	private String reportCategory;
	private String previousReportType2B;
	private String previousReportTypePR;
	private String taxPeriod2B;
	private String taxPeriodPR;
	private String calendarMonth;
	private String recipientGstin2B;
	private String recipientGstinPR;
	private String supplierGstin2B;
	private String supplierGstinPR;
	private String supplierLegalName2B;
	private String supplierTradeName2B;
	private String supplierNamePR;
	private String docType2B;
	private String docTypePR;
	private String documentNumber2B;
	private String documentNumberPR;
	private String documentDate2B;
	private String documentDatePR;
	private String gSTPercent2B;
	private String gSTPercentPR;
	private String pos2B;
	private String posPR;
	private String taxableValue2B;
	private String taxableValuePR;
	private String igst2B;
	private String igstPR;
	private String cgst2B;
	private String cgstPR;
	private String sgst2B;
	private String sgstPR;
	private String cess2B;
	private String cessPR;
	private String totalTax2B;
	private String totalTaxPR;
	private String invoiceValue2B;
	private String invoiceValuePR;
	private String availableIGST;
	private String availableCGST;
	private String availableSGST;
	private String availableCESS;
	private String tableType2B;
	private String gSTR1FilingStatus;
	private String gSTR1FilingDate;
	private String gSTR1FilingPeriod;
	private String gSTR3BFilingStatus;
	private String cancellationDate;
	private String orgInvAmendmentPeriod;
	private String orgAmendmentType;
	private String cDNDelinkingFlag;
	private String reverseChargeFlag2B;
	private String reverseChargeFlagPR;
	private String differentialPercentage2B;
	private String differentialPercentagePR;
	private String orgDocNumber2B;
	private String orgDocNumberPR;
	private String orgDocDate2B;
	private String orgDocDatePR;
	private String orgSupplierGstinPR;
	private String orgSupplierNamePR;
	private String cRDRPreGST2B;
	private String cRDRPreGSTPR;
	private String boeReferenceDate;
	private String portCode2B;
	private String billOfEntry2B;
	private String billOfEntryDate2B;
	private String boeAmended;
	private String userID;
	private String sourceFileName;
	private String sourceIdentifier;
	private String profitCentre1;
	private String plant;
	private String division;
	private String location;
	private String purchaseOrganisation;
	private String profitCentre2;
	private String profitCentre3;
	private String profitCentre4;
	private String profitCentre5;
	private String profitCentre6;
	private String profitCentre7;
	private String gLCodeAssessableValue;
	private String gLCodeIGST;
	private String gLCodeCGST;
	private String gLCodeSGST;
	private String gLCodeAdvaloremCess;
	private String gLCodeSpecificCess;
	private String gLCodeStateCessAdvalorem;
	private String supplyType2B;
	private String supplyTypePR;
	private String supplierType;
	private String supplierCode;
	private String supplierAddress1;
	private String supplierAddress2;
	private String supplierLocation;
	private String supplierPincode;
	private String stateApplyingCess;
	private String portCodePR;
	private String billOfEntryPR;
	private String billOfEntryDatePR;
	private String cIFValue;
	private String customDuty;
	private String hSNorSAC;
	private String productCode;
	private String productDescription;
	private String categoryOfProduct;
	private String uqc;
	private String quantity;
	private String advaloremCessRate;
	private String advaloremCessAmount;
	private String specificCessRate;
	private String specificCessAmount;
	private String stateCessAdvaloremRate;
	private String stateCessAdvaloremAmount;
	private String itemOtherCharges;
	private String claimRefundFlag;
	private String autoPopulateToRefund;
	private String adjustementReferenceNo;
	private String adjustementReferenceDate;
	private String eligibilityIndicator;
	private String commonSupplyIndicator;
	private String iTCEntitlement;
	private String iTCReversalIdentifier;
	private String reasonForCreditDebitNote;
	private String accountingVoucherNumber;
	private String accountingVoucherDate;
	private String glPostingDate;
	private String customerPORefNumber;
	private String customerPORefDate;
	private String purchaseOrderValue;
	private String userDefinedField1;
	private String userDefinedField2;
	private String userDefinedField3;
	private String userDefinedField4;
	private String userDefinedField5;
	private String userDefinedField6;
	private String userDefinedField7;
	private String userDefinedField8;
	private String userDefinedField9;
	private String userDefinedField10;
	private String userDefinedField11;
	private String userDefinedField12;
	private String userDefinedField13;
	private String userDefinedField14;
	private String userDefinedField15;
	private String userDefinedField28;
	private String eWayBillNumber;
	private String eWayBillDate;
	private String matchingID;
	private String requestID;
	private String iDPR;
	private String iD2B;
	private String invoiceKeyPR;
	private String invoiceKeyA2;
	private String invoiceKeyUploadPR;
	private String invoiceKeyUpload2B;
	private String referenceIDPR;
	private String referenceID2B;
	private String generationDate2B;
	private String itcAvailability2B;
	private String reasonForItcUnavailability2B;
	private String sourceTypeofIrn;
	private String irn2B;
	private String irnPR;
	private String irnDate2B;
	private String irnDatePR;

	
	//newly added Sprint Feb 2023
	private String itcReversedTaxPeriod;
	private String itcReclaimedTaxPeriod;
	private String gstr3bFilingDate;
	private String supplierGSTINStatus;
	private String billOfEntryCreatedDate2B;
	private String vendorTaxPaidVariance;
	private String vendorType;
	private String hsnVendor;
	private String vendorRiskCategory;
	private String vendorPaymentTermsDays;
	private String vendorRemarks;
	private String systemDefinedField1;
	private String systemDefinedField2;
	private String systemDefinedField3;
	private String systemDefinedField4;
	private String systemDefinedField5;
	
	
 	//IMS 
 	private String imsUserResponse;
 	private String imsResponseRemark;
 	private String actionGstn;
 	private String pendingActionbloacked;
 	private String imsGetCallDateTime;
 	private String actionDigi;
 	private String actionDigiDateTime;
 	private String imsSaveToGstn;
 	private String activeInIms;
 	private String imsTotalTaxDiff;
 	private String imsTotalTaxPRGreater2B;
 	private String imsTotalTax2BGreaterPR;
 	private String imsUniqueId;
 	private String amountSource2B;
 	
	// private String taxableValueAdjusted;
	// private String integratedTaxAmountAdjusted;
	// private String centralTaxAmountAdjusted;
	// private String stateUTTaxAmountAdjusted;
	// private String advaloremCessAmountAdjusted;
	// private String specificCessAmountAdjusted;
	// private String stateCessAmountAdjusted;
	// private String contractNumber;
	// private String contractDate;
	// private String erpReportType;
	// private String approvalStatus;
	// private String supplierPan2B;
	// private String supplierPanPR;
	// private String cFSFlag2B;// removed
	// new added
	// private String supplyTypePR;
	// new logic
	// private String boeReferenceDate;
	// private String portCode2B;
	// private String billOfEntry2B;
	// private String billOfEntryDate2B;
	// private String boeAmended;
	// private String matchReason;
	// private String reportCategory;
	// private String supplierTradeName2B;
	// private String reconGeneratedDate;
	// private String eInvoiceApplicability;
	// private String supplierReturnFilingPeriodicity;
	// private String recordStatus;
	// private String keyDescription;
	// 115-240 format
	// 2B data in 2B
	// private String taxPeriod2B;
	// private String sourceType;
	// private String previousSourceType;
	// private String generationDate2B;

}
