sap.ui.define(function () {
	"use strict";

	return {
		getObject: function () {
			return {
				"view": "",
				"returnType": "",
				"an1Gstr1SubCategory": "",
				"an1Gstr1TableNo": "",
				"totalTaxes": 0,
				"userId": "",
				"sourceFileName": "",
				"profitCentre": "",
				"plantCode": "",
				"division": "",
				"location": "",
				"salesOrgnization": "",
				"distChannel": "",
				"userAccess1": "",
				"userAccess2": "",
				"userAccess3": "",
				"userAccess4": "",
				"userAccess5": "",
				"userAccess6": "",
				"returnPeriod": "",
				"supplierGstin": "",
				"docType": "",
				"docNo": "",
				"docDate": "",
				"originalDocType": "",
				"crDrPreGst": false,
				"custGstin": "",
				"custOrSuppType": "",
				"diffPercent": "",
				"origCgstin": "",
				"custOrSuppName": "",
				"custOrSuppCode": "",
				"custOrSuppAddress1": "",
				"custOrSuppAddress2": "",
				"custOrSuppAddress3": "",
				"custOrSuppAddress4": "",
				"billToState": "",
				"shipToState": "",
				"pos": "",
				"stateApplyingCess": "",
				"portCode": "",
				"shippingBillNo": "",
				"shippingBillDate": "",
				"sec7OfIgstFlag": "",
				"reverseCharge": "",
				"tcsFlag": "",
				"ecomGSTIN": "",
				"claimRefundFlag": "",
				"autoPopToRefundFlag": "",
				"accountVoucherNo": "",
				"accountVoucherDate": "",
				"eWayBillNo": "",
				"eWayBillDate": "",
				// "dataOriginTypeCode": "A",
				// "derivedTaxperiod": 201903,
				// "docAmount": 62000.00,
				// "fiYear": "201920",
				// "hciReceivedOn": "2019-07-30",
				// "id": 107963,
				// "initiatedOn": "2019-07-30",
				// "isDeleted": false "isError": false,
				// "isGstnError": false,
				// "isInfo": false,
				// "isProcessed": true,
				// "isSaved": false,
				// "isSent": false,
				// "isSubmitted": false,
				// "javaBeforeSavingOn": "2019-07-30",
				// "javaReqReceivedOn": "2019-07-30",
				// "sourceIdentifier": "P",
				// "subDivision": "SD1",
				"glCodeTaxableVal": "",
				"glCodeIgst": "",
				"glCodeCgst": "",
				"glCodeSgst": "",
				"glCodeAdvCess": "",
				"glCodeSpCess": "",
				"glCodeStateCess": "",
				"supplyType": "",
				"originalDocNo": "",
				"originalDocDate": "",
				"itemNo": "",
				"fob": "",
				"exportDuty": "",
				"hsnsacCode": "",
				"productCode": "",
				"itemDesc": "",
				"itemType": "",
				"itemUqc": "",
				"itemQty": 0,
				"taxableVal": 0,
				"igstRate": 0,
				"igstAmt": 0,
				"cgstRate": 0,
				"cgstAmt": 0,
				"sgstRate": 0,
				"sgstAmt": 0,
				"cessRateAdvalorem": 0,
				"cessAmtAdvalorem": 0,
				"cessRateSpecific": 0,
				"cessAmtSpecfic": 0,
				"stateCessRate": 0,
				"stateCessAmt": 0,
				"otherValues": 0,
				"lineItemAmt": 0,
				"adjustmentRefNo": "",
				"adjustmentRefDate": "",
				"adjustedTaxableValue": "",
				"adjustedIgstAmt": 0,
				"adjustedCgstAmt": 0,
				"adjustedSgstAmt": 0,
				"adjustedCessAmtAdvalorem": 0,
				"adjustedCessAmtSpecific": 0,
				"adjustedCessAmt": 0,
				"tcsAmount": "",
				"itcFlag": "",
				"crDrReason": "",
				"userDefinedField1": "",
				"userDefinedField2": "",
				"userDefinedField3": "",
				"userDefinedField4": "",
				"userDefinedField5": "",
				"userDefinedField6": "",
				"userDefinedField7": "",
				"userDefinedField8": "",
				"userDefinedField9": "",
				"userDefinedField10": "",
				"userDefinedField11": "",
				"userDefinedField12": "",
				"userDefinedField13": "",
				"userDefinedField14": "",
				"userDefinedField15": "",
				"lineItems": []
			};
		}
	};
});